# ResNet50 Deep Features with SVM and Random Forest

This notebook implements hybrid brain tumour MRI classification using fixed ImageNet-pretrained ResNet50 deep features with Support Vector Machine and Random Forest classifiers, evaluated using the predefined five-fold cross-validation assignments.

In [1]:
# ============================================================
# RESNET50 + RF — LOCAL PC STEP 1
# VERIFY LOCAL PROJECT FILES
#
# PURPOSE:
#   Confirm that the local VS Code notebook can see:
#
#   1. the existing ResNet50 feature cache
#   2. the shared repeated 10 × 5 CV split file
#
# Nothing is trained.
# Nothing is modified.
# Nothing is deleted.
# ============================================================

from pathlib import Path


# ============================================================
# 1. LOCAL PROJECT ROOT
# ============================================================

PROJECT_ROOT = Path(
    r"C:\Users\kwsta\OneDrive\Desktop\Desetation project"
    r"\brain-tumour-mri-classification"
)


# ============================================================
# 2. EXISTING LOCAL DIRECTORIES
# ============================================================

FEATURE_CACHE_DIR = (
    PROJECT_ROOT
    / "extracted_features"
)


REPEATED_SPLITS_DIR = (
    PROJECT_ROOT
    / "repeated_cv"
    / "splits"
)


SHARED_REPEATED_SPLIT_FILE = (
    REPEATED_SPLITS_DIR
    / "repeated_stratified_5fold_assignments.csv"
)


# ============================================================
# 3. BASIC PATH VALIDATION
# ============================================================

assert PROJECT_ROOT.exists(), (
    f"Project root not found:\n{PROJECT_ROOT}"
)


assert FEATURE_CACHE_DIR.exists(), (
    f"Feature directory not found:\n{FEATURE_CACHE_DIR}"
)


assert REPEATED_SPLITS_DIR.exists(), (
    f"Repeated-CV split directory not found:\n"
    f"{REPEATED_SPLITS_DIR}"
)


assert SHARED_REPEATED_SPLIT_FILE.exists(), (
    "Shared repeated-CV split file not found:\n"
    f"{SHARED_REPEATED_SPLIT_FILE}"
)


# ============================================================
# 4. FIND LOCAL NPZ FEATURE FILES
#
# We are deliberately NOT guessing the filename.
# ============================================================

npz_files = sorted(
    FEATURE_CACHE_DIR.glob("*.npz")
)


resnet_npz_files = [
    path
    for path in npz_files
    if "resnet" in path.name.lower()
]


# ============================================================
# 5. DISPLAY
# ============================================================

print("=" * 80)

print(
    "RESNET50 + RF — LOCAL PC FILE CHECK"
)

print("=" * 80)


print(
    "\nProject root:"
)

print(
    PROJECT_ROOT
)


print(
    "\nFeature-cache directory:"
)

print(
    FEATURE_CACHE_DIR
)


print(
    "\nShared repeated-CV split:"
)

print(
    SHARED_REPEATED_SPLIT_FILE
)


print(
    "\nShared split exists:",
    SHARED_REPEATED_SPLIT_FILE.exists(),
)


print(
    "\nAll NPZ files found in extracted_features:",
    len(npz_files),
)


for path in npz_files:

    print(
        "   ",
        path.name,
    )


print(
    "\nResNet-related NPZ files found:",
    len(resnet_npz_files),
)


for path in resnet_npz_files:

    print(
        "   ",
        path.name,
    )


print(
    "\nLOCAL PC STEP 1: PASSED"
)

================================================================================
RESNET50 + RF — LOCAL PC FILE CHECK
================================================================================

Project root:
C:\Users\kwsta\OneDrive\Desktop\Desetation project\brain-tumour-mri-classification

Feature-cache directory:
C:\Users\kwsta\OneDrive\Desktop\Desetation project\brain-tumour-mri-classification\extracted_features

Shared repeated-CV split:
C:\Users\kwsta\OneDrive\Desktop\Desetation project\brain-tumour-mri-classification\repeated_cv\splits\repeated_stratified_5fold_assignments.csv

Shared split exists: True

All NPZ files found in extracted_features: 3
    hog_glcm_testing_features.npz
    hog_glcm_training_features.npz
    training_resnet50_features.npz

ResNet-related NPZ files found: 1
    training_resnet50_features.npz

LOCAL PC STEP 1: PASSED

In [2]:
# ============================================================
# RESNET50 + RF — LOCAL PC STEP 2
# LOAD AND VERIFY EXISTING FEATURE CACHE + SHARED SPLITS
#
# PURPOSE:
#   Confirm that the local files contain exactly the data
#   required by the ResNet50 + RF experiment.
#
# Nothing is trained.
# Nothing is modified.
# Nothing is deleted.
# ============================================================

import numpy as np
import pandas as pd


# ============================================================
# 1. EXACT LOCAL INPUT FILES
# ============================================================

RESNET50_FEATURE_CACHE_FILE = (
    FEATURE_CACHE_DIR
    / "training_resnet50_features.npz"
)


REPEATED_SPLIT_FILE = (
    SHARED_REPEATED_SPLIT_FILE
)


assert RESNET50_FEATURE_CACHE_FILE.exists()

assert REPEATED_SPLIT_FILE.exists()


# ============================================================
# 2. INSPECT RESNET50 FEATURE CACHE
# ============================================================

resnet50_cache = np.load(
    RESNET50_FEATURE_CACHE_FILE,
    allow_pickle=True,
)


print("=" * 80)

print(
    "RESNET50 + RF — LOCAL PC INPUT VALIDATION"
)

print("=" * 80)


print(
    "\nResNet50 cache:"
)

print(
    RESNET50_FEATURE_CACHE_FILE
)


print(
    "\nNPZ keys:"
)

print(
    resnet50_cache.files
)


print(
    "\nArrays inside cache:"
)


for key in resnet50_cache.files:

    value = resnet50_cache[
        key
    ]


    print(
        f"  {key}: "
        f"shape={value.shape}, "
        f"dtype={value.dtype}"
    )


# ============================================================
# 3. LOAD SHARED 10 × 5 SPLIT FILE
# ============================================================

repeated_folds_df = pd.read_csv(
    REPEATED_SPLIT_FILE
)


print(
    "\nShared repeated-CV file:"
)

print(
    REPEATED_SPLIT_FILE
)


print(
    "\nShared split shape:",
    repeated_folds_df.shape,
)


print(
    "\nShared split columns:"
)

print(
    repeated_folds_df.columns.tolist()
)


print(
    "\nFirst 5 rows:"
)

print(
    repeated_folds_df.head()
)


# ============================================================
# 4. CORE STRUCTURAL VALIDATION
# ============================================================

assert len(
    repeated_folds_df
) == 56000, (
    "Expected exactly 56,000 repeated-CV assignment rows."
)


assert (
    repeated_folds_df[
        "repeat"
    ]
    .nunique()
    == 10
), (
    "Expected exactly 10 repeats."
)


assert (
    repeated_folds_df[
        "fold"
    ]
    .nunique()
    == 5
), (
    "Expected exactly 5 outer folds."
)


print(
    "\nRepeated-CV structure:"
)


print(
    "Repeats:",
    sorted(
        repeated_folds_df[
            "repeat"
        ]
        .unique()
        .tolist()
    ),
)


print(
    "Folds:",
    sorted(
        repeated_folds_df[
            "fold"
        ]
        .unique()
        .tolist()
    ),
)


print(
    "\nLOCAL PC STEP 2: PASSED"
)

================================================================================
RESNET50 + RF — LOCAL PC INPUT VALIDATION
================================================================================

ResNet50 cache:
C:\Users\kwsta\OneDrive\Desktop\Desetation project\brain-tumour-mri-classification\extracted_features\training_resnet50_features.npz

NPZ keys:
['features', 'class_indices', 'fold_assignments', 'relative_paths']

Arrays inside cache:
  features: shape=(5600, 2048), dtype=float32
  class_indices: shape=(5600,), dtype=int32
  fold_assignments: shape=(5600,), dtype=int32
  relative_paths: shape=(5600,), dtype=object

Shared repeated-CV file:
C:\Users\kwsta\OneDrive\Desktop\Desetation project\brain-tumour-mri-classification\repeated_cv\splits\repeated_stratified_5fold_assignments.csv

Shared split shape: (56000, 6)

Shared split columns:
['relative_path', 'class', 'label', 'repeat', 'fold', 'split_seed']

First 5 rows:
                    relative_path   class  label  repeat  fold  split_seed
0     Training/glioma/Tr-gl_1.png  glioma      0       1     3      202601
1    Training/glioma/Tr-gl_10.png  glioma      0       1     4      202601
2   Training/glioma/Tr-gl_100.png  glioma      0       1     4      202601
3  Training/glioma/Tr-gl_1000.png  glioma      0       1     3      202601
4  Training/glioma/Tr-gl_1001.png  glioma      0       1     4      202601

Repeated-CV structure:
Repeats: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Folds: [1, 2, 3, 4, 5]

LOCAL PC STEP 2: PASSED

In [3]:
# ============================================================
# RESNET50 + RF — LOCAL PC STEP 3
# LOAD + ALIGN RESNET50 FEATURES TO THE SHARED CV SPLITS
#
# PURPOSE:
#   Create the exact variables required by the repeated
#   ResNet50 + RF experiment:
#
#       training_features
#       training_class_indices
#       training_relative_paths
#       repeated_folds_df
#
# IMPORTANT:
#   - The OLD fold_assignments inside the NPZ are ignored.
#   - The shared repeated_stratified_5fold_assignments.csv
#     remains authoritative.
#   - Nothing is trained.
#   - Testing is not accessed.
# ============================================================

import numpy as np
import pandas as pd


# ============================================================
# 1. EXPERIMENT CONSTANTS
# ============================================================

FEATURE_DIMENSION = 2048


CLASS_NAMES = [
    "glioma",
    "meningioma",
    "notumor",
    "pituitary",
]


INDEX_TO_CLASS = {
    0: "glioma",
    1: "meningioma",
    2: "notumor",
    3: "pituitary",
}


# ============================================================
# 2. LOAD EXISTING RESNET50 CACHE
# ============================================================

with np.load(
    RESNET50_FEATURE_CACHE_FILE,
    allow_pickle=True,
) as feature_cache:

    training_features = np.asarray(
        feature_cache[
            "features"
        ],
        dtype=np.float32,
    )


    training_class_indices = np.asarray(
        feature_cache[
            "class_indices"
        ],
        dtype=np.int32,
    )


    training_relative_paths = np.asarray(
        feature_cache[
            "relative_paths"
        ],
        dtype=str,
    )


# ============================================================
# 3. STRICT FEATURE-CACHE VALIDATION
# ============================================================

assert training_features.shape == (
    5600,
    2048,
)


assert training_features.dtype == np.float32


assert np.isfinite(
    training_features
).all()


assert training_class_indices.shape == (
    5600,
)


assert set(
    np.unique(
        training_class_indices
    ).tolist()
) == {
    0,
    1,
    2,
    3,
}


assert training_relative_paths.shape == (
    5600,
)


assert (
    len(
        np.unique(
            training_relative_paths
        )
    )
    == 5600
)


# ============================================================
# 4. VALIDATE FEATURE-CACHE CLASS BALANCE
# ============================================================

feature_class_counts = np.bincount(
    training_class_indices,
    minlength=4,
)


assert np.array_equal(
    feature_class_counts,
    np.array(
        [
            1400,
            1400,
            1400,
            1400,
        ]
    ),
)


# ============================================================
# 5. RELOAD AUTHORITATIVE SHARED REPEATED-CV FILE
# ============================================================

repeated_folds_df = pd.read_csv(
    REPEATED_SPLIT_FILE
)


assert repeated_folds_df.shape == (
    56000,
    6,
)


required_split_columns = {
    "relative_path",
    "class",
    "label",
    "repeat",
    "fold",
    "split_seed",
}


assert required_split_columns.issubset(
    repeated_folds_df.columns
)


# ============================================================
# 6. VERIFY THE 5,600 UNIQUE TRAINING IMAGES ARE IDENTICAL
#
# This is critical:
#
#   Feature cache:
#       exactly 5,600 training images
#
#   Shared repeated CV:
#       the same 5,600 images repeated once for each of
#       the 10 repeats = 56,000 rows
# ============================================================

shared_unique_paths = (
    repeated_folds_df[
        "relative_path"
    ]
    .astype(str)
    .drop_duplicates()
    .to_numpy()
)


assert len(
    shared_unique_paths
) == 5600


feature_path_set = set(
    training_relative_paths.tolist()
)


shared_path_set = set(
    shared_unique_paths.tolist()
)


missing_from_feature_cache = (
    shared_path_set
    - feature_path_set
)


extra_in_feature_cache = (
    feature_path_set
    - shared_path_set
)


assert not missing_from_feature_cache, (
    "Some shared-CV paths are missing from the "
    "ResNet50 feature cache:\n"
    f"{list(missing_from_feature_cache)[:10]}"
)


assert not extra_in_feature_cache, (
    "Some ResNet50 feature-cache paths are not present "
    "in the shared CV assignments:\n"
    f"{list(extra_in_feature_cache)[:10]}"
)


# ============================================================
# 7. VERIFY LABELS MATCH BETWEEN CACHE AND SHARED SPLITS
# ============================================================

feature_label_lookup = {

    relative_path:
        int(
            label
        )

    for relative_path, label
    in zip(
        training_relative_paths,
        training_class_indices,
    )
}


shared_path_labels = (
    repeated_folds_df[
        [
            "relative_path",
            "label",
        ]
    ]
    .drop_duplicates()
    .copy()
)


assert len(
    shared_path_labels
) == 5600


shared_path_labels[
    "cache_label"
] = (
    shared_path_labels[
        "relative_path"
    ]
    .map(
        feature_label_lookup
    )
)


assert (
    shared_path_labels[
        "cache_label"
    ]
    .notna()
    .all()
)


label_mismatches = (
    shared_path_labels[
        shared_path_labels[
            "label"
        ]
        .astype(int)
        != shared_path_labels[
            "cache_label"
        ]
        .astype(int)
    ]
)


assert len(
    label_mismatches
) == 0, (
    "Feature-cache labels do not match the shared "
    "repeated-CV labels."
)


# ============================================================
# 8. VERIFY REPEAT / FOLD STRUCTURE
# ============================================================

assert (
    repeated_folds_df[
        "repeat"
    ]
    .nunique()
    == 10
)


assert (
    repeated_folds_df[
        "fold"
    ]
    .nunique()
    == 5
)


for repeat_number in range(
    1,
    11,
):

    repeat_df = (
        repeated_folds_df[
            repeated_folds_df[
                "repeat"
            ]
            == repeat_number
        ]
    )


    assert len(
        repeat_df
    ) == 5600


    assert (
        repeat_df[
            "relative_path"
        ]
        .nunique()
        == 5600
    )


    for fold_number in range(
        1,
        6,
    ):

        validation_df = (
            repeat_df[
                repeat_df[
                    "fold"
                ]
                == fold_number
            ]
        )


        assert len(
            validation_df
        ) == 1120


        fold_class_counts = (
            validation_df[
                "label"
            ]
            .astype(int)
            .value_counts()
            .sort_index()
            .to_numpy()
        )


        assert np.array_equal(
            fold_class_counts,
            np.array(
                [
                    280,
                    280,
                    280,
                    280,
                ]
            ),
        )


# ============================================================
# 9. DISPLAY
# ============================================================

print("=" * 80)

print(
    "RESNET50 + RF — LOCAL FEATURE ALIGNMENT"
)

print("=" * 80)


print(
    "\nTraining features:",
    training_features.shape,
    training_features.dtype,
)


print(
    "Training labels:",
    training_class_indices.shape,
)


print(
    "Training relative paths:",
    training_relative_paths.shape,
)


print(
    "\nFeature-cache class counts:",
    feature_class_counts.tolist(),
)


print(
    "\nShared repeated-CV rows:",
    len(
        repeated_folds_df
    ),
)


print(
    "Unique shared training paths:",
    len(
        shared_unique_paths
    ),
)


print(
    "Paths missing from feature cache:",
    len(
        missing_from_feature_cache
    ),
)


print(
    "Extra paths in feature cache:",
    len(
        extra_in_feature_cache
    ),
)


print(
    "Label mismatches:",
    len(
        label_mismatches
    ),
)


print(
    "\nOuter structure:"
)


print(
    "10 repeats × 5 folds"
)


print(
    "Each validation fold: 1,120 images"
)


print(
    "Each class per validation fold: 280"
)


print(
    "\nOLD NPZ fold_assignments: IGNORED"
)


print(
    "Shared repeated split file: AUTHORITATIVE"
)


print(
    "Testing partition: NOT ACCESSED"
)


print(
    "\nRESNET50 + RF — LOCAL PC STEP 3: PASSED"
)

================================================================================
RESNET50 + RF — LOCAL FEATURE ALIGNMENT
================================================================================

Training features: (5600, 2048) float32
Training labels: (5600,)
Training relative paths: (5600,)

Feature-cache class counts: [1400, 1400, 1400, 1400]

Shared repeated-CV rows: 56000
Unique shared training paths: 5600
Paths missing from feature cache: 0
Extra paths in feature cache: 0
Label mismatches: 0

Outer structure:
10 repeats × 5 folds
Each validation fold: 1,120 images
Each class per validation fold: 280

OLD NPZ fold_assignments: IGNORED
Shared repeated split file: AUTHORITATIVE
Testing partition: NOT ACCESSED

RESNET50 + RF — LOCAL PC STEP 3: PASSED

In [4]:
# ============================================================
# RESNET50 + RF — LOCAL PC STEP 4
# CREATE + VALIDATE SHARED OUTER-PARTITION FUNCTION
#
# PURPOSE:
#   Recreate make_hybrid_outer_partition() locally using:
#
#       training_features
#       training_class_indices
#       training_relative_paths
#       repeated_folds_df
#
# The shared repeated-CV CSV remains authoritative.
#
# Nothing is trained.
# Nothing is saved.
# Testing is not accessed.
# ============================================================

import numpy as np


# ============================================================
# 1. CREATE FAST FEATURE-CACHE PATH LOOKUP
#
# Maps:
#
#   relative_path -> row number in the 5,600 × 2,048 cache
# ============================================================

training_path_to_index = {

    relative_path:
        int(index)

    for index, relative_path
    in enumerate(
        training_relative_paths
    )
}


assert len(
    training_path_to_index
) == 5600


# ============================================================
# 2. SHARED OUTER-PARTITION CONSTRUCTOR
# ============================================================

def make_hybrid_outer_partition(
    repeat_number,
    fold_number,
):

    # --------------------------------------------------------
    # Validate requested repeat / fold
    # --------------------------------------------------------

    assert repeat_number in range(
        1,
        11,
    ), (
        "repeat_number must be between 1 and 10."
    )


    assert fold_number in range(
        1,
        6,
    ), (
        "fold_number must be between 1 and 5."
    )


    # --------------------------------------------------------
    # Extract this complete repeat
    # --------------------------------------------------------

    repeat_df = (
        repeated_folds_df[
            repeated_folds_df[
                "repeat"
            ]
            == repeat_number
        ]
        .copy()
    )


    assert len(
        repeat_df
    ) == 5600


    assert (
        repeat_df[
            "relative_path"
        ]
        .nunique()
        == 5600
    )


    # --------------------------------------------------------
    # Split seed
    #
    # Every row in a repeat must use the same split seed.
    # --------------------------------------------------------

    split_seeds = (
        repeat_df[
            "split_seed"
        ]
        .astype(int)
        .unique()
    )


    assert len(
        split_seeds
    ) == 1


    split_seed = int(
        split_seeds[0]
    )


    expected_split_seed = (
        202600
        + repeat_number
    )


    assert (
        split_seed
        == expected_split_seed
    )


    # --------------------------------------------------------
    # Outer validation:
    #
    # exactly the requested shared fold
    # --------------------------------------------------------

    outer_validation_df = (
        repeat_df[
            repeat_df[
                "fold"
            ]
            == fold_number
        ]
        .copy()
    )


    # --------------------------------------------------------
    # Outer training:
    #
    # the remaining four shared folds
    # --------------------------------------------------------

    outer_training_df = (
        repeat_df[
            repeat_df[
                "fold"
            ]
            != fold_number
        ]
        .copy()
    )


    # --------------------------------------------------------
    # Structural validation
    # --------------------------------------------------------

    assert len(
        outer_training_df
    ) == 4480


    assert len(
        outer_validation_df
    ) == 1120


    assert (
        outer_training_df[
            "relative_path"
        ]
        .nunique()
        == 4480
    )


    assert (
        outer_validation_df[
            "relative_path"
        ]
        .nunique()
        == 1120
    )


    training_paths = (
        outer_training_df[
            "relative_path"
        ]
        .astype(str)
        .to_numpy()
    )


    validation_paths = (
        outer_validation_df[
            "relative_path"
        ]
        .astype(str)
        .to_numpy()
    )


    # --------------------------------------------------------
    # Ensure outer training / validation are disjoint
    # --------------------------------------------------------

    assert set(
        training_paths.tolist()
    ).isdisjoint(
        set(
            validation_paths.tolist()
        )
    )


    # --------------------------------------------------------
    # Convert shared paths into feature-cache row indices
    # --------------------------------------------------------

    missing_training_paths = [

        relative_path

        for relative_path
        in training_paths

        if relative_path
        not in training_path_to_index
    ]


    missing_validation_paths = [

        relative_path

        for relative_path
        in validation_paths

        if relative_path
        not in training_path_to_index
    ]


    assert not missing_training_paths, (
        "Outer-training paths are missing from the "
        "ResNet50 feature cache."
    )


    assert not missing_validation_paths, (
        "Outer-validation paths are missing from the "
        "ResNet50 feature cache."
    )


    outer_training_indices = np.asarray(
        [
            training_path_to_index[
                relative_path
            ]
            for relative_path
            in training_paths
        ],
        dtype=np.int64,
    )


    outer_validation_indices = np.asarray(
        [
            training_path_to_index[
                relative_path
            ]
            for relative_path
            in validation_paths
        ],
        dtype=np.int64,
    )


    # --------------------------------------------------------
    # Extract cached ResNet50 features
    # --------------------------------------------------------

    outer_training_features = (
        training_features[
            outer_training_indices
        ]
    )


    outer_validation_features = (
        training_features[
            outer_validation_indices
        ]
    )


    # --------------------------------------------------------
    # Labels from the feature cache
    # --------------------------------------------------------

    outer_training_labels = (
        training_class_indices[
            outer_training_indices
        ]
        .astype(
            np.int32,
            copy=False,
        )
    )


    outer_validation_labels = (
        training_class_indices[
            outer_validation_indices
        ]
        .astype(
            np.int32,
            copy=False,
        )
    )


    # --------------------------------------------------------
    # Verify labels also match authoritative split CSV
    # --------------------------------------------------------

    expected_training_labels = (
        outer_training_df[
            "label"
        ]
        .astype(int)
        .to_numpy()
    )


    expected_validation_labels = (
        outer_validation_df[
            "label"
        ]
        .astype(int)
        .to_numpy()
    )


    assert np.array_equal(
        outer_training_labels,
        expected_training_labels,
    )


    assert np.array_equal(
        outer_validation_labels,
        expected_validation_labels,
    )


    # --------------------------------------------------------
    # Exact expected shapes
    # --------------------------------------------------------

    assert outer_training_features.shape == (
        4480,
        2048,
    )


    assert outer_validation_features.shape == (
        1120,
        2048,
    )


    # --------------------------------------------------------
    # Exact class balance
    # --------------------------------------------------------

    outer_training_class_counts = (
        np.bincount(
            outer_training_labels,
            minlength=4,
        )
    )


    outer_validation_class_counts = (
        np.bincount(
            outer_validation_labels,
            minlength=4,
        )
    )


    assert np.array_equal(
        outer_training_class_counts,
        np.array(
            [
                1120,
                1120,
                1120,
                1120,
            ]
        ),
    )


    assert np.array_equal(
        outer_validation_class_counts,
        np.array(
            [
                280,
                280,
                280,
                280,
            ]
        ),
    )


    # --------------------------------------------------------
    # Return SAME keys expected by Hybrid RF runner
    # --------------------------------------------------------

    return {

        "repeat":
            int(
                repeat_number
            ),

        "fold":
            int(
                fold_number
            ),

        "split_seed":
            int(
                split_seed
            ),

        "outer_training_features":
            outer_training_features,

        "outer_training_labels":
            outer_training_labels,

        "outer_training_paths":
            training_paths,

        "outer_validation_features":
            outer_validation_features,

        "outer_validation_labels":
            outer_validation_labels,

        "outer_validation_paths":
            validation_paths,
    }


# ============================================================
# 3. VALIDATE REPEAT 1 / FOLD 1
# ============================================================

local_test_partition = (
    make_hybrid_outer_partition(
        repeat_number=1,
        fold_number=1,
    )
)


# ============================================================
# 4. STRICT R1/F1 VALIDATION
# ============================================================

assert (
    local_test_partition[
        "split_seed"
    ]
    == 202601
)


assert (
    local_test_partition[
        "outer_training_features"
    ]
    .shape
    == (
        4480,
        2048,
    )
)


assert (
    local_test_partition[
        "outer_validation_features"
    ]
    .shape
    == (
        1120,
        2048,
    )
)


assert np.array_equal(
    np.bincount(
        local_test_partition[
            "outer_training_labels"
        ],
        minlength=4,
    ),
    np.array(
        [
            1120,
            1120,
            1120,
            1120,
        ]
    ),
)


assert np.array_equal(
    np.bincount(
        local_test_partition[
            "outer_validation_labels"
        ],
        minlength=4,
    ),
    np.array(
        [
            280,
            280,
            280,
            280,
        ]
    ),
)


# ============================================================
# 5. DISPLAY
# ============================================================

print("=" * 80)

print(
    "RESNET50 + RF — LOCAL OUTER PARTITION CHECK"
)

print("=" * 80)


print(
    "\nRepeat:",
    local_test_partition[
        "repeat"
    ],
)


print(
    "Fold:",
    local_test_partition[
        "fold"
    ],
)


print(
    "Split seed:",
    local_test_partition[
        "split_seed"
    ],
)


print(
    "\nOuter-training features:",
    local_test_partition[
        "outer_training_features"
    ]
    .shape,
)


print(
    "Outer-validation features:",
    local_test_partition[
        "outer_validation_features"
    ]
    .shape,
)


print(
    "\nOuter-training class counts:",
    np.bincount(
        local_test_partition[
            "outer_training_labels"
        ],
        minlength=4,
    )
    .tolist(),
)


print(
    "Outer-validation class counts:",
    np.bincount(
        local_test_partition[
            "outer_validation_labels"
        ],
        minlength=4,
    )
    .tolist(),
)


print(
    "\nTraining/validation overlap:",
    len(
        set(
            local_test_partition[
                "outer_training_paths"
            ]
            .tolist()
        )
        &
        set(
            local_test_partition[
                "outer_validation_paths"
            ]
            .tolist()
        )
    ),
)


print(
    "\nShared repeated-CV assignments: USED"
)


print(
    "Old NPZ fold assignments: IGNORED"
)


print(
    "Testing partition: NOT ACCESSED"
)


print(
    "\nRESNET50 + RF — LOCAL PC STEP 4: PASSED"
)


# ============================================================
# 6. CLEAN UP VALIDATION PARTITION ONLY
#
# The function itself remains available for the RF runner.
# ============================================================

del local_test_partition

================================================================================
RESNET50 + RF — LOCAL OUTER PARTITION CHECK
================================================================================

Repeat: 1
Fold: 1
Split seed: 202601

Outer-training features: (4480, 2048)
Outer-validation features: (1120, 2048)

Outer-training class counts: [1120, 1120, 1120, 1120]
Outer-validation class counts: [280, 280, 280, 280]

Training/validation overlap: 0

Shared repeated-CV assignments: USED
Old NPZ fold assignments: IGNORED
Testing partition: NOT ACCESSED

RESNET50 + RF — LOCAL PC STEP 4: PASSED

In [5]:
# ============================================================
# RESNET50 + RF — LOCAL PC STEP 5
# RF SEEDS + LOCAL RESULTS / CHECKPOINT DIRECTORY
#
# PURPOSE:
#   Prepare the local VS Code RF experiment so it uses:
#
#       - the SAME inner-CV seeds as Colab
#       - the SAME RF model seeds as Colab
#       - the SAME RF search seeds as Colab
#
#   but saves all outputs locally on this PC.
#
# IMPORTANT:
#   - Colab continues saving to Google Drive.
#   - This VS Code copy saves ONLY to the local PC.
#   - The two runs therefore cannot overwrite each other.
#   - Nothing is trained in this cell.
# ============================================================

from pathlib import Path


# ============================================================
# 1. REPEATED NESTED-CV CONSTANTS
# ============================================================

NUMBER_OF_REPEATS = 10

NUMBER_OF_OUTER_FOLDS = 5

NUMBER_OF_INNER_FOLDS = 3


# ============================================================
# 2. INNER-CV SEED
#
# SAME schedule as Colab:
#
#   R1/F1 = 303101
# ============================================================

BASE_INNER_CV_SEED = 303000


def get_hybrid_inner_cv_seed(
    repeat_number,
    fold_number,
):

    return (
        BASE_INNER_CV_SEED
        + repeat_number * 100
        + fold_number
    )


# ============================================================
# 3. RANDOM FOREST MODEL SEED
#
# SAME schedule as Colab:
#
#   R1/F1 = 404101
# ============================================================

BASE_RF_MODEL_SEED = 404000


def get_hybrid_rf_model_seed(
    repeat_number,
    fold_number,
):

    return (
        BASE_RF_MODEL_SEED
        + repeat_number * 100
        + fold_number
    )


# ============================================================
# 4. RANDOM FOREST SEARCH SEED
#
# SAME schedule as Colab:
#
#   R1/F1 = 414101
# ============================================================

BASE_RF_SEARCH_SEED = 414000


def get_hybrid_rf_search_seed(
    repeat_number,
    fold_number,
):

    return (
        BASE_RF_SEARCH_SEED
        + repeat_number * 100
        + fold_number
    )


# ============================================================
# 5. STRICT SEED VALIDATION
# ============================================================

assert (
    get_hybrid_inner_cv_seed(
        1,
        1,
    )
    == 303101
)


assert (
    get_hybrid_rf_model_seed(
        1,
        1,
    )
    == 404101
)


assert (
    get_hybrid_rf_search_seed(
        1,
        1,
    )
    == 414101
)


assert (
    get_hybrid_inner_cv_seed(
        10,
        5,
    )
    == 304005
)


assert (
    get_hybrid_rf_model_seed(
        10,
        5,
    )
    == 405005
)


assert (
    get_hybrid_rf_search_seed(
        10,
        5,
    )
    == 415005
)


# ============================================================
# 6. LOCAL RESULTS ROOT
#
# This is deliberately LOCAL.
#
# Colab:
#   saves to Google Drive
#
# VS Code:
#   saves here on this PC
# ============================================================

LOCAL_REPEATED_RESULTS_ROOT = (
    PROJECT_ROOT
    / "results"
    / "repeated_nested_cv_local"
)


REPEATED_RESNET50_RF_DIR = (
    LOCAL_REPEATED_RESULTS_ROOT
    / "resnet50_rf"
)


REPEATED_RESNET50_RF_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


# ============================================================
# 7. SAFETY CHECK
#
# Ensure this is clearly a local Windows path and not a
# Google Drive / Colab path.
# ============================================================

results_path_text = str(
    REPEATED_RESNET50_RF_DIR
)


assert "/content/drive" not in results_path_text


assert "MyDrive" not in results_path_text


assert REPEATED_RESNET50_RF_DIR.exists()


# ============================================================
# 8. DISPLAY
# ============================================================

print("=" * 80)

print(
    "RESNET50 + RF — LOCAL RF SEED / STORAGE SETUP"
)

print("=" * 80)


print(
    "\nR1/F1 inner-CV seed:",
    get_hybrid_inner_cv_seed(
        1,
        1,
    ),
)


print(
    "R1/F1 RF model seed:",
    get_hybrid_rf_model_seed(
        1,
        1,
    ),
)


print(
    "R1/F1 RF search seed:",
    get_hybrid_rf_search_seed(
        1,
        1,
    ),
)


print(
    "\nR10/F5 inner-CV seed:",
    get_hybrid_inner_cv_seed(
        10,
        5,
    ),
)


print(
    "R10/F5 RF model seed:",
    get_hybrid_rf_model_seed(
        10,
        5,
    ),
)


print(
    "R10/F5 RF search seed:",
    get_hybrid_rf_search_seed(
        10,
        5,
    ),
)


print(
    "\nLocal RF results root:"
)

print(
    REPEATED_RESNET50_RF_DIR
)


print(
    "\nLocal results directory exists:",
    REPEATED_RESNET50_RF_DIR.exists(),
)


print(
    "\nColab Google Drive results: NOT USED"
)


print(
    "Testing partition: NOT ACCESSED"
)


print(
    "\nRESNET50 + RF — LOCAL PC STEP 5: PASSED"
)

================================================================================
RESNET50 + RF — LOCAL RF SEED / STORAGE SETUP
================================================================================

R1/F1 inner-CV seed: 303101
R1/F1 RF model seed: 404101
R1/F1 RF search seed: 414101

R10/F5 inner-CV seed: 304005
R10/F5 RF model seed: 405005
R10/F5 RF search seed: 415005

Local RF results root:
C:\Users\kwsta\OneDrive\Desktop\Desetation project\brain-tumour-mri-classification\results\repeated_nested_cv_local\resnet50_rf

Local results directory exists: True

Colab Google Drive results: NOT USED
Testing partition: NOT ACCESSED

RESNET50 + RF — LOCAL PC STEP 5: PASSED

In [6]:
# ============================================================
# RESNET50 + RF — LOCAL PC STEP 6
# CHECKPOINTED RF SEARCH CONFIGURATION
#
# PURPOSE:
#   Prepare the exact RF search/checkpoint structure used by
#   the Colab ResNet50 + RF experiment.
#
# SEARCH:
#   1,920 possible RF configurations
#   100 deterministically sampled initial candidates
#
#   Stage 1: 100 candidates × 25 trees
#   Stage 2:  34 candidates × 75 trees
#   Stage 3:  12 candidates × 225 trees
#   Stage 4:   4 candidates × 675 trees
#
# INNER CV:
#   3-fold shuffled StratifiedKFold
#   scoring = macro-F1
#
# IMPORTANT:
#   - SAME methodology as Colab
#   - SAME seeds as Colab
#   - LOCAL checkpoints only
#   - Nothing is trained in this cell
#   - Testing is not accessed
# ============================================================

import json
import math
import os

from pathlib import Path

import numpy as np
import pandas as pd

from sklearn.ensemble import (
    RandomForestClassifier,
)

from sklearn.model_selection import (
    ParameterGrid,
    ParameterSampler,
    StratifiedKFold,
)


# ============================================================
# 1. EXACT RANDOM FOREST SEARCH SPACE
# ============================================================

RESNET50_RF_PARAMETER_DISTRIBUTIONS = {

    "criterion": [
        "gini",
        "entropy",
    ],

    "max_depth": [
        None,
        20,
        40,
        60,
        80,
    ],

    "min_samples_split": [
        2,
        5,
        10,
        20,
    ],

    "min_samples_leaf": [
        1,
        2,
        4,
        8,
    ],

    "max_features": [
        "sqrt",
        "log2",
        0.02,
        0.05,
        0.10,
        0.20,
    ],

    "bootstrap": [
        True,
        False,
    ],
}


# ============================================================
# 2. VERIFY COMPLETE SEARCH SPACE
# ============================================================

total_rf_parameter_combinations = len(
    list(
        ParameterGrid(
            RESNET50_RF_PARAMETER_DISTRIBUTIONS
        )
    )
)


assert (
    total_rf_parameter_combinations
    == 1920
)


# ============================================================
# 3. SUCCESSIVE-HALVING CONSTANTS
# ============================================================

RESNET50_RF_INITIAL_CANDIDATES = 100

RESNET50_RF_HALVING_FACTOR = 3


RESNET50_RF_STAGE_RESOURCES = [
    25,
    75,
    225,
    675,
]


RESNET50_RF_EXPECTED_STAGE_CANDIDATES = [
    100,
    34,
    12,
    4,
]


assert (
    RESNET50_RF_STAGE_RESOURCES
    == [
        25,
        75,
        225,
        675,
    ]
)


assert (
    RESNET50_RF_EXPECTED_STAGE_CANDIDATES
    == [
        100,
        34,
        12,
        4,
    ]
)


# ============================================================
# 4. ATOMIC DATAFRAME SAVE
#
# Prevents partially-written checkpoint CSV files if Python
# or Windows stops during the save operation.
# ============================================================

def resnet50_rf_save_dataframe_atomic(
    dataframe,
    destination_path,
):

    destination_path = Path(
        destination_path
    )


    destination_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )


    temporary_path = (
        destination_path.parent
        / (
            destination_path.name
            + ".tmp"
        )
    )


    with open(
        temporary_path,
        "w",
        encoding="utf-8",
        newline="",
    ) as file:

        dataframe.to_csv(
            file,
            index=False,
        )


        file.flush()

        os.fsync(
            file.fileno()
        )


    os.replace(
        temporary_path,
        destination_path,
    )


    assert destination_path.exists()


# ============================================================
# 5. JSON SERIALISATION HELPER
# ============================================================

def resnet50_rf_json_default(
    value,
):

    if isinstance(
        value,
        np.integer,
    ):

        return int(
            value
        )


    if isinstance(
        value,
        np.floating,
    ):

        return float(
            value
        )


    if isinstance(
        value,
        np.bool_,
    ):

        return bool(
            value
        )


    if isinstance(
        value,
        np.ndarray,
    ):

        return value.tolist()


    if isinstance(
        value,
        Path,
    ):

        return str(
            value
        )


    raise TypeError(
        f"Object of type {type(value).__name__} "
        "is not JSON serializable."
    )


# ============================================================
# 6. ATOMIC JSON SAVE
# ============================================================

def resnet50_rf_save_json_atomic(
    dictionary,
    destination_path,
):

    destination_path = Path(
        destination_path
    )


    destination_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )


    temporary_path = (
        destination_path.parent
        / (
            destination_path.name
            + ".tmp"
        )
    )


    with open(
        temporary_path,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            dictionary,
            file,
            indent=4,
            ensure_ascii=False,
            default=
                resnet50_rf_json_default,
        )


        file.flush()

        os.fsync(
            file.fileno()
        )


    os.replace(
        temporary_path,
        destination_path,
    )


    assert destination_path.exists()


# ============================================================
# 7. LOCAL FOLD / CHECKPOINT PATHS
# ============================================================

RESNET50_RF_RESULTS_ROOT = (
    REPEATED_RESNET50_RF_DIR
)


def get_checkpointed_resnet50_rf_fold_paths(
    repeat_number,
    fold_number,
):

    fold_directory = (
        RESNET50_RF_RESULTS_ROOT
        / f"repeat_{repeat_number:02d}"
        / f"fold_{fold_number:02d}"
    )


    search_progress_directory = (
        fold_directory
        / "search_progress"
    )


    return {

        "directory":
            fold_directory,

        "search_progress_directory":
            search_progress_directory,

        "candidate_manifest":
            (
                search_progress_directory
                / "candidate_manifest.csv"
            ),

        "inner_fit_progress":
            (
                search_progress_directory
                / "inner_fit_progress.csv"
            ),

        "search_complete":
            (
                search_progress_directory
                / "search_complete.json"
            ),

        "search_results":
            (
                fold_directory
                / "inner_search_results.csv"
            ),

        "selected_parameters":
            (
                fold_directory
                / "selected_parameters.json"
            ),

        "outer_predictions":
            (
                fold_directory
                / "outer_predictions.csv"
            ),

        "outer_metrics":
            (
                fold_directory
                / "outer_metrics.json"
            ),

        "completion_marker":
            (
                fold_directory
                / "COMPLETED.json"
            ),
    }


# ============================================================
# 8. COMPLETED-FOLD CHECK
# ============================================================

def is_checkpointed_resnet50_rf_fold_complete(
    repeat_number,
    fold_number,
):

    paths = (
        get_checkpointed_resnet50_rf_fold_paths(
            repeat_number,
            fold_number,
        )
    )


    required_paths = [

        paths[
            "search_results"
        ],

        paths[
            "selected_parameters"
        ],

        paths[
            "outer_predictions"
        ],

        paths[
            "outer_metrics"
        ],

        paths[
            "completion_marker"
        ],
    ]


    if not all(
        path.exists()
        for path
        in required_paths
    ):

        return False


    try:

        with open(
            paths[
                "completion_marker"
            ],
            "r",
            encoding="utf-8",
        ) as file:

            completion = json.load(
                file
            )


        if (
            completion.get(
                "status"
            )
            != "completed"
        ):

            return False


        if (
            completion.get(
                "model"
            )
            != "ResNet50_fixed_features_RF"
        ):

            return False


        if (
            int(
                completion[
                    "repeat"
                ]
            )
            != repeat_number
        ):

            return False


        if (
            int(
                completion[
                    "fold"
                ]
            )
            != fold_number
        ):

            return False


        with open(
            paths[
                "outer_metrics"
            ],
            "r",
            encoding="utf-8",
        ) as file:

            metrics = json.load(
                file
            )


        if (
            metrics.get(
                "model"
            )
            != "ResNet50_fixed_features_RF"
        ):

            return False


        if (
            int(
                metrics[
                    "outer_training_samples"
                ]
            )
            != 4480
        ):

            return False


        if (
            int(
                metrics[
                    "outer_validation_samples"
                ]
            )
            != 1120
        ):

            return False


        if not np.isfinite(
            float(
                metrics[
                    "macro_f1"
                ]
            )
        ):

            return False


        predictions_df = pd.read_csv(
            paths[
                "outer_predictions"
            ]
        )


        if len(
            predictions_df
        ) != 1120:

            return False


        if (
            predictions_df[
                "relative_path"
            ]
            .nunique()
            != 1120
        ):

            return False


        return True


    except Exception:

        return False


# ============================================================
# 9. INNER-CV CONSTRUCTOR
# ============================================================

def make_checkpointed_resnet50_rf_inner_cv(
    repeat_number,
    fold_number,
):

    return StratifiedKFold(

        n_splits=3,

        shuffle=True,

        random_state=
            get_hybrid_inner_cv_seed(
                repeat_number,
                fold_number,
            ),
    )


# ============================================================
# 10. PARAMETER RECONSTRUCTION HELPERS
#
# Candidate manifests are stored as CSV, so values must be
# reconstructed safely after a restart.
# ============================================================

def resnet50_rf_optional_integer(
    value,
):

    if pd.isna(
        value
    ):

        return None


    return int(
        value
    )


def resnet50_rf_normalise_max_features(
    value,
):

    if isinstance(
        value,
        str,
    ):

        cleaned_value = (
            value.strip()
        )


        if cleaned_value in (
            "sqrt",
            "log2",
        ):

            return cleaned_value


        return float(
            cleaned_value
        )


    return float(
        value
    )


def resnet50_rf_candidate_parameters_from_row(
    row,
):

    bootstrap_value = (
        row[
            "bootstrap"
        ]
    )


    if isinstance(
        bootstrap_value,
        str,
    ):

        bootstrap_value = (
            bootstrap_value
            .strip()
            .lower()
            == "true"
        )


    else:

        bootstrap_value = bool(
            bootstrap_value
        )


    return {

        "criterion":
            str(
                row[
                    "criterion"
                ]
            ),

        "max_depth":
            resnet50_rf_optional_integer(
                row[
                    "max_depth"
                ]
            ),

        "min_samples_split":
            int(
                row[
                    "min_samples_split"
                ]
            ),

        "min_samples_leaf":
            int(
                row[
                    "min_samples_leaf"
                ]
            ),

        "max_features":
            resnet50_rf_normalise_max_features(
                row[
                    "max_features"
                ]
            ),

        "bootstrap":
            bootstrap_value,
    }


# ============================================================
# 11. VERIFY DETERMINISTIC R1/F1 CANDIDATE SAMPLING
#
# No RF model is fitted here.
# ============================================================

test_candidates = list(
    ParameterSampler(

        RESNET50_RF_PARAMETER_DISTRIBUTIONS,

        n_iter=
            RESNET50_RF_INITIAL_CANDIDATES,

        random_state=
            get_hybrid_rf_search_seed(
                1,
                1,
            ),
    )
)


assert len(
    test_candidates
) == 100


# ============================================================
# 12. AUDIT LOCAL RESULT STATE
#
# Since this PC run is starting independently, this should
# normally report 0 / 50 completed unless old local results
# already exist.
# ============================================================

completed_local_rf_folds = []

partial_local_rf_folds = []


for repeat_number in range(
    1,
    11,
):

    for fold_number in range(
        1,
        6,
    ):

        paths = (
            get_checkpointed_resnet50_rf_fold_paths(
                repeat_number,
                fold_number,
            )
        )


        if (
            is_checkpointed_resnet50_rf_fold_complete(
                repeat_number,
                fold_number,
            )
        ):

            completed_local_rf_folds.append(
                (
                    repeat_number,
                    fold_number,
                )
            )


        elif (
            paths[
                "inner_fit_progress"
            ]
            .exists()
        ):

            progress_df = pd.read_csv(
                paths[
                    "inner_fit_progress"
                ]
            )


            partial_local_rf_folds.append(
                (
                    repeat_number,
                    fold_number,
                    len(
                        progress_df
                    ),
                )
            )


# ============================================================
# 13. DISPLAY
# ============================================================

print("=" * 80)

print(
    "RESNET50 + RF — LOCAL CHECKPOINT SEARCH SETUP"
)

print("=" * 80)


print(
    "\nLocal results root:"
)

print(
    RESNET50_RF_RESULTS_ROOT
)


print(
    "\nRF parameter combinations:",
    total_rf_parameter_combinations,
)


print(
    "Initial sampled candidates:",
    RESNET50_RF_INITIAL_CANDIDATES,
)


print(
    "Candidate progression:",
    "100 -> 34 -> 12 -> 4 -> winner",
)


print(
    "Tree resources:",
    RESNET50_RF_STAGE_RESOURCES,
)


print(
    "\nR1/F1 inner-CV seed:",
    get_hybrid_inner_cv_seed(
        1,
        1,
    ),
)


print(
    "R1/F1 model seed:",
    get_hybrid_rf_model_seed(
        1,
        1,
    ),
)


print(
    "R1/F1 search seed:",
    get_hybrid_rf_search_seed(
        1,
        1,
    ),
)


print(
    "\nCompleted LOCAL outer folds:",
    len(
        completed_local_rf_folds
    ),
    "/ 50",
)


print(
    "Partial LOCAL checkpointed folds:",
    len(
        partial_local_rf_folds
    ),
)


if completed_local_rf_folds:

    print(
        "\nCompleted folds:"
    )

    print(
        completed_local_rf_folds
    )


if partial_local_rf_folds:

    print(
        "\nPartial checkpoint folds:"
    )

    print(
        partial_local_rf_folds
    )


print(
    "\nColab/Google Drive output directory: NOT USED"
)


print(
    "Testing partition: NOT ACCESSED"
)


print(
    "\nRESNET50 + RF — LOCAL PC STEP 6: PASSED"
)


del test_candidates

================================================================================
RESNET50 + RF — LOCAL CHECKPOINT SEARCH SETUP
================================================================================

Local results root:
C:\Users\kwsta\OneDrive\Desktop\Desetation project\brain-tumour-mri-classification\results\repeated_nested_cv_local\resnet50_rf

RF parameter combinations: 1920
Initial sampled candidates: 100
Candidate progression: 100 -> 34 -> 12 -> 4 -> winner
Tree resources: [25, 75, 225, 675]

R1/F1 inner-CV seed: 303101
R1/F1 model seed: 404101
R1/F1 search seed: 414101

Completed LOCAL outer folds: 35 / 50
Partial LOCAL checkpointed folds: 1

Completed folds:
[(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5)]

Partial checkpoint folds:
[(8, 1, 157)]

Colab/Google Drive output directory: NOT USED
Testing partition: NOT ACCESSED

RESNET50 + RF — LOCAL PC STEP 6: PASSED

In [7]:
# ============================================================
# RESNET50 + RF — LOCAL PC STEP 7
# CHECKPOINTED 10 × 5 REPEATED NESTED-CV MASTER RUNNER
#
# TOTAL:
#   10 repeats × 5 outer folds = 50 outer evaluations
#
# INNER SEARCH PER OUTER FOLD:
#
#   Stage 1:
#       100 candidates × 3 inner folds × 25 trees
#
#   Stage 2:
#        34 candidates × 3 inner folds × 75 trees
#
#   Stage 3:
#        12 candidates × 3 inner folds × 225 trees
#
#   Stage 4:
#         4 candidates × 3 inner folds × 675 trees
#
# RESUME:
#   Every candidate × inner-fold fit is checkpointed.
#
#   If interrupted:
#       rerun THIS SAME CELL
#
#   Already-completed inner fits -> SKIPPED
#   Already-completed outer folds -> SKIPPED
#
# IMPORTANT:
#   - Uses local ResNet50 5,600 × 2,048 features.
#   - Uses shared repeated 10 × 5 assignments.
#   - Uses same seeds / RF search as Colab.
#   - Saves only to the LOCAL PC.
#   - Testing is NEVER accessed.
# ============================================================

import gc
import json
import math
import time

import numpy as np
import pandas as pd

from sklearn.ensemble import (
    RandomForestClassifier,
)

from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)

from sklearn.model_selection import (
    ParameterSampler,
)


# ============================================================
# 1. FINAL PRE-RUN VALIDATION
# ============================================================

assert training_features.shape == (
    5600,
    2048,
)

assert FEATURE_DIMENSION == 2048

assert len(
    repeated_folds_df
) == 56000

assert (
    RESNET50_RF_INITIAL_CANDIDATES
    == 100
)

assert (
    RESNET50_RF_STAGE_RESOURCES
    == [
        25,
        75,
        225,
        675,
    ]
)

assert (
    RESNET50_RF_EXPECTED_STAGE_CANDIDATES
    == [
        100,
        34,
        12,
        4,
    ]
)


# ============================================================
# 2. CREATE / LOAD DETERMINISTIC CANDIDATE MANIFEST
# ============================================================

def get_or_create_local_resnet50_rf_candidate_manifest(
    repeat_number,
    fold_number,
    candidate_manifest_path,
):

    if candidate_manifest_path.exists():

        candidate_manifest_df = pd.read_csv(
            candidate_manifest_path
        )


        print(
            "Loaded existing candidate manifest."
        )


    else:

        sampled_candidates = list(
            ParameterSampler(

                RESNET50_RF_PARAMETER_DISTRIBUTIONS,

                n_iter=
                    RESNET50_RF_INITIAL_CANDIDATES,

                random_state=
                    get_hybrid_rf_search_seed(
                        repeat_number,
                        fold_number,
                    ),
            )
        )


        assert len(
            sampled_candidates
        ) == 100


        candidate_rows = []


        for (
            candidate_id,
            parameters,
        ) in enumerate(
            sampled_candidates,
            start=1,
        ):

            candidate_rows.append(
                {
                    "candidate_id":
                        int(
                            candidate_id
                        ),

                    "criterion":
                        parameters[
                            "criterion"
                        ],

                    "max_depth":
                        parameters[
                            "max_depth"
                        ],

                    "min_samples_split":
                        parameters[
                            "min_samples_split"
                        ],

                    "min_samples_leaf":
                        parameters[
                            "min_samples_leaf"
                        ],

                    "max_features":
                        parameters[
                            "max_features"
                        ],

                    "bootstrap":
                        parameters[
                            "bootstrap"
                        ],
                }
            )


        candidate_manifest_df = pd.DataFrame(
            candidate_rows
        )


        assert len(
            candidate_manifest_df
        ) == 100


        assert (
            candidate_manifest_df[
                "candidate_id"
            ]
            .nunique()
            == 100
        )


        resnet50_rf_save_dataframe_atomic(
            candidate_manifest_df,
            candidate_manifest_path,
        )


        print(
            "Created and saved new candidate manifest."
        )


    candidate_manifest_df[
        "candidate_id"
    ] = (
        candidate_manifest_df[
            "candidate_id"
        ]
        .astype(int)
    )


    assert (
        candidate_manifest_df[
            "candidate_id"
        ]
        .tolist()
        == list(
            range(
                1,
                101,
            )
        )
    )


    return candidate_manifest_df


# ============================================================
# 3. LOAD INDIVIDUAL-FIT CHECKPOINT PROGRESS
# ============================================================

def load_local_resnet50_rf_inner_progress(
    progress_path,
):

    progress_columns = [

        "repeat",
        "outer_fold",

        "stage",
        "n_estimators",

        "candidate_id",
        "inner_fold",

        "macro_f1",
        "fit_seconds",
    ]


    if progress_path.exists():

        progress_df = pd.read_csv(
            progress_path
        )


        print(
            "Loaded checkpoint:",
            len(
                progress_df
            ),
            "completed inner fits."
        )


    else:

        progress_df = pd.DataFrame(
            columns=
                progress_columns
        )


        print(
            "No previous inner-fit checkpoint."
        )


    if len(
        progress_df
    ) > 0:

        assert set(
            progress_columns
        ).issubset(
            progress_df.columns
        )


        integer_columns = [

            "repeat",
            "outer_fold",

            "stage",
            "n_estimators",

            "candidate_id",
            "inner_fold",
        ]


        for column_name in (
            integer_columns
        ):

            progress_df[
                column_name
            ] = (
                pd.to_numeric(
                    progress_df[
                        column_name
                    ]
                )
                .astype(int)
            )


        progress_df[
            "macro_f1"
        ] = pd.to_numeric(
            progress_df[
                "macro_f1"
            ]
        )


        progress_df[
            "fit_seconds"
        ] = pd.to_numeric(
            progress_df[
                "fit_seconds"
            ]
        )


        assert not (
            progress_df
            .duplicated(
                subset=[
                    "stage",
                    "candidate_id",
                    "inner_fold",
                ]
            )
            .any()
        ), (
            "Duplicate inner-fit checkpoint "
            "records detected."
        )


    return progress_df


# ============================================================
# 4. SAVE ONE COMPLETED INNER FIT IMMEDIATELY
# ============================================================

def checkpoint_local_resnet50_rf_inner_fit(
    progress_df,
    new_record,
    progress_path,
):

    updated_progress_df = pd.concat(
        [
            progress_df,

            pd.DataFrame(
                [
                    new_record
                ]
            ),
        ],
        ignore_index=True,
    )


    assert not (
        updated_progress_df
        .duplicated(
            subset=[
                "stage",
                "candidate_id",
                "inner_fold",
            ]
        )
        .any()
    )


    resnet50_rf_save_dataframe_atomic(
        updated_progress_df,
        progress_path,
    )


    return updated_progress_df


# ============================================================
# 5. CHECK WHETHER ONE FIT IS ALREADY SAVED
# ============================================================

def local_resnet50_rf_inner_fit_exists(
    progress_df,
    stage_number,
    candidate_id,
    inner_fold_number,
):

    if len(
        progress_df
    ) == 0:

        return False


    return bool(
        (
            (
                progress_df[
                    "stage"
                ]
                == int(
                    stage_number
                )
            )
            &
            (
                progress_df[
                    "candidate_id"
                ]
                == int(
                    candidate_id
                )
            )
            &
            (
                progress_df[
                    "inner_fold"
                ]
                == int(
                    inner_fold_number
                )
            )
        )
        .any()
    )


# ============================================================
# 6. BUILD STAGE RESULTS FROM SAVED INDIVIDUAL FITS
# ============================================================

def build_local_resnet50_rf_stage_results(
    progress_df,
    candidate_manifest_df,
    active_candidate_ids,
    stage_number,
    number_of_trees,
):

    stage_progress_df = (
        progress_df[
            (
                progress_df[
                    "stage"
                ]
                == stage_number
            )
            &
            (
                progress_df[
                    "candidate_id"
                ]
                .astype(int)
                .isin(
                    active_candidate_ids
                )
            )
        ]
        .copy()
    )


    expected_fit_count = (
        len(
            active_candidate_ids
        )
        * 3
    )


    assert (
        len(
            stage_progress_df
        )
        == expected_fit_count
    ), (
        f"Stage {stage_number} incomplete: "
        f"expected {expected_fit_count} fits, "
        f"found {len(stage_progress_df)}."
    )


    fold_counts = (
        stage_progress_df
        .groupby(
            "candidate_id"
        )
        .size()
    )


    assert (
        fold_counts
        .eq(3)
        .all()
    )


    stage_results_df = (
        stage_progress_df
        .groupby(
            "candidate_id",
            as_index=False,
        )
        .agg(

            mean_test_score=(
                "macro_f1",
                "mean",
            ),

            std_test_score=(
                "macro_f1",
                "std",
            ),

            total_fit_seconds=(
                "fit_seconds",
                "sum",
            ),

            inner_folds_completed=(
                "inner_fold",
                "count",
            ),
        )
    )


    stage_results_df = (
        stage_results_df
        .merge(
            candidate_manifest_df,
            on="candidate_id",
            how="left",
            validate="one_to_one",
        )
    )


    # --------------------------------------------------------
    # Deterministic ranking:
    #
    # 1. highest macro-F1
    # 2. lowest candidate ID for ties
    # --------------------------------------------------------

    stage_results_df = (
        stage_results_df
        .sort_values(
            [
                "mean_test_score",
                "candidate_id",
            ],
            ascending=[
                False,
                True,
            ],
        )
        .reset_index(
            drop=True
        )
    )


    stage_results_df.insert(
        0,
        "rank_test_score",
        np.arange(
            1,
            len(
                stage_results_df
            )
            + 1,
        ),
    )


    stage_results_df.insert(
        0,
        "n_resources",
        int(
            number_of_trees
        ),
    )


    stage_results_df.insert(
        0,
        "iter",
        int(
            stage_number
            - 1
        ),
    )


    return stage_results_df


# ============================================================
# 7. RUN / RESUME ONE OUTER FOLD
# ============================================================

def run_local_checkpointed_resnet50_rf_outer_fold(
    repeat_number,
    fold_number,
):

    paths = (
        get_checkpointed_resnet50_rf_fold_paths(
            repeat_number,
            fold_number,
        )
    )


    fold_directory = (
        paths[
            "directory"
        ]
    )


    search_progress_directory = (
        paths[
            "search_progress_directory"
        ]
    )


    fold_directory.mkdir(
        parents=True,
        exist_ok=True,
    )


    search_progress_directory.mkdir(
        parents=True,
        exist_ok=True,
    )


    # ========================================================
    # 7A. SKIP COMPLETED FOLD
    # ========================================================

    if (
        is_checkpointed_resnet50_rf_fold_complete(
            repeat_number,
            fold_number,
        )
    ):

        print(
            "\n"
            f"R{repeat_number:02d}/"
            f"F{fold_number:02d} "
            "already COMPLETE -> SKIPPED"
        )


        return "skipped"


    # ========================================================
    # 7B. AUTHORITATIVE OUTER PARTITION
    # ========================================================

    partition = (
        make_hybrid_outer_partition(
            repeat_number=
                repeat_number,

            fold_number=
                fold_number,
        )
    )


    X_outer_train = (
        partition[
            "outer_training_features"
        ]
    )


    y_outer_train = np.asarray(
        partition[
            "outer_training_labels"
        ],
        dtype=int,
    )


    X_outer_validation = (
        partition[
            "outer_validation_features"
        ]
    )


    y_outer_validation = np.asarray(
        partition[
            "outer_validation_labels"
        ],
        dtype=int,
    )


    outer_validation_paths = np.asarray(
        partition[
            "outer_validation_paths"
        ],
        dtype=str,
    )


    assert X_outer_train.shape == (
        4480,
        2048,
    )


    assert X_outer_validation.shape == (
        1120,
        2048,
    )


    assert np.array_equal(
        np.bincount(
            y_outer_train,
            minlength=4,
        ),
        np.array(
            [
                1120,
                1120,
                1120,
                1120,
            ]
        ),
    )


    assert np.array_equal(
        np.bincount(
            y_outer_validation,
            minlength=4,
        ),
        np.array(
            [
                280,
                280,
                280,
                280,
            ]
        ),
    )


    print(
        "\n"
        + "=" * 88
    )


    print(
        "RESNET50 FIXED FEATURES + RANDOM FOREST"
    )


    print(
        f"REPEAT {repeat_number:02d} / "
        f"FOLD {fold_number:02d}"
    )


    print(
        "=" * 88
    )


    print(
        "Outer training:",
        X_outer_train.shape,
    )


    print(
        "Outer validation:",
        X_outer_validation.shape,
    )


    print(
        "Split seed:",
        partition[
            "split_seed"
        ],
    )


    print(
        "Inner-CV seed:",
        get_hybrid_inner_cv_seed(
            repeat_number,
            fold_number,
        ),
    )


    print(
        "RF model seed:",
        get_hybrid_rf_model_seed(
            repeat_number,
            fold_number,
        ),
    )


    print(
        "RF search seed:",
        get_hybrid_rf_search_seed(
            repeat_number,
            fold_number,
        ),
    )


    # ========================================================
    # 7C. INNER SEARCH
    # ========================================================

    candidate_manifest_path = (
        paths[
            "candidate_manifest"
        ]
    )


    progress_path = (
        paths[
            "inner_fit_progress"
        ]
    )


    search_complete_path = (
        paths[
            "search_complete"
        ]
    )


    # --------------------------------------------------------
    # Completed search already exists
    # --------------------------------------------------------

    if search_complete_path.exists():

        with open(
            search_complete_path,
            "r",
            encoding="utf-8",
        ) as file:

            search_summary = json.load(
                file
            )


        assert (
            search_summary[
                "status"
            ]
            == "completed"
        )


        assert (
            int(
                search_summary[
                    "repeat"
                ]
            )
            == repeat_number
        )


        assert (
            int(
                search_summary[
                    "outer_fold"
                ]
            )
            == fold_number
        )


        print(
            "\nInner search already COMPLETE "
            "-> loading saved winner."
        )


    # --------------------------------------------------------
    # New / partially completed search
    # --------------------------------------------------------

    else:

        candidate_manifest_df = (
            get_or_create_local_resnet50_rf_candidate_manifest(
                repeat_number,
                fold_number,
                candidate_manifest_path,
            )
        )


        progress_df = (
            load_local_resnet50_rf_inner_progress(
                progress_path
            )
        )


        if len(
            progress_df
        ) > 0:

            assert (
                progress_df[
                    "repeat"
                ]
                .eq(
                    repeat_number
                )
                .all()
            )


            assert (
                progress_df[
                    "outer_fold"
                ]
                .eq(
                    fold_number
                )
                .all()
            )


        # ====================================================
        # FIXED 3-FOLD INNER SPLITS
        # ====================================================

        inner_cv = (
            make_checkpointed_resnet50_rf_inner_cv(
                repeat_number,
                fold_number,
            )
        )


        inner_splits = list(
            inner_cv.split(
                X_outer_train,
                y_outer_train,
            )
        )


        assert len(
            inner_splits
        ) == 3


        active_candidate_ids = (
            candidate_manifest_df[
                "candidate_id"
            ]
            .astype(int)
            .tolist()
        )


        model_seed = (
            get_hybrid_rf_model_seed(
                repeat_number,
                fold_number,
            )
        )


        all_stage_results = []


        # ====================================================
        # FOUR SUCCESSIVE-HALVING STAGES
        # ====================================================

        for (
            stage_number,
            number_of_trees,
        ) in enumerate(
            RESNET50_RF_STAGE_RESOURCES,
            start=1,
        ):

            expected_candidates = (
                RESNET50_RF_EXPECTED_STAGE_CANDIDATES[
                    stage_number
                    - 1
                ]
            )


            assert (
                len(
                    active_candidate_ids
                )
                == expected_candidates
            )


            print(
                "\n"
                + "-" * 88
            )


            print(
                f"STAGE {stage_number}/4"
            )


            print(
                "-" * 88
            )


            print(
                "Trees:",
                number_of_trees,
            )


            print(
                "Candidates:",
                len(
                    active_candidate_ids
                ),
            )


            # =================================================
            # CANDIDATES
            # =================================================

            for (
                candidate_position,
                candidate_id,
            ) in enumerate(
                active_candidate_ids,
                start=1,
            ):

                candidate_row = (
                    candidate_manifest_df[
                        candidate_manifest_df[
                            "candidate_id"
                        ]
                        == int(
                            candidate_id
                        )
                    ]
                    .iloc[0]
                )


                candidate_parameters = (
                    resnet50_rf_candidate_parameters_from_row(
                        candidate_row
                    )
                )


                # =============================================
                # THREE INNER FOLDS
                # =============================================

                for (
                    inner_fold_number,
                    (
                        inner_training_indices,
                        inner_validation_indices,
                    ),
                ) in enumerate(
                    inner_splits,
                    start=1,
                ):

                    # -----------------------------------------
                    # RESUME CHECK
                    # -----------------------------------------

                    if (
                        local_resnet50_rf_inner_fit_exists(

                            progress_df,

                            stage_number,
                            candidate_id,
                            inner_fold_number,
                        )
                    ):

                        print(
                            f"Stage {stage_number} | "
                            f"Candidate "
                            f"{candidate_position}/"
                            f"{len(active_candidate_ids)} | "
                            f"ID {candidate_id:03d} | "
                            f"Inner {inner_fold_number}/3 "
                            "-> SKIPPED"
                        )


                        continue


                    # =========================================
                    # INDIVIDUAL RF FIT
                    #
                    # n_jobs=-1:
                    #   use available CPU cores on this PC
                    # =========================================

                    model = (
                        RandomForestClassifier(

                            **candidate_parameters,

                            n_estimators=
                                int(
                                    number_of_trees
                                ),

                            random_state=
                                model_seed,

                            n_jobs=-1,
                        )
                    )


                    fit_start = (
                        time.perf_counter()
                    )


                    model.fit(

                        X_outer_train[
                            inner_training_indices
                        ],

                        y_outer_train[
                            inner_training_indices
                        ],
                    )


                    inner_predictions = (
                        model.predict(

                            X_outer_train[
                                inner_validation_indices
                            ]
                        )
                    )


                    fit_seconds = (
                        time.perf_counter()
                        - fit_start
                    )


                    inner_macro_f1 = float(
                        f1_score(

                            y_outer_train[
                                inner_validation_indices
                            ],

                            inner_predictions,

                            average="macro",
                        )
                    )


                    assert np.isfinite(
                        inner_macro_f1
                    )


                    # =========================================
                    # CHECKPOINT IMMEDIATELY
                    # =========================================

                    progress_df = (
                        checkpoint_local_resnet50_rf_inner_fit(

                            progress_df,

                            {
                                "repeat":
                                    int(
                                        repeat_number
                                    ),

                                "outer_fold":
                                    int(
                                        fold_number
                                    ),

                                "stage":
                                    int(
                                        stage_number
                                    ),

                                "n_estimators":
                                    int(
                                        number_of_trees
                                    ),

                                "candidate_id":
                                    int(
                                        candidate_id
                                    ),

                                "inner_fold":
                                    int(
                                        inner_fold_number
                                    ),

                                "macro_f1":
                                    float(
                                        inner_macro_f1
                                    ),

                                "fit_seconds":
                                    float(
                                        fit_seconds
                                    ),
                            },

                            progress_path,
                        )
                    )


                    print(
                        f"Stage {stage_number} | "
                        f"Candidate "
                        f"{candidate_position}/"
                        f"{len(active_candidate_ids)} | "
                        f"ID {candidate_id:03d} | "
                        f"Inner {inner_fold_number}/3 | "
                        f"F1={inner_macro_f1:.6f} | "
                        f"{fit_seconds:.2f}s | "
                        "CHECKPOINT SAVED"
                    )


                    del model
                    del inner_predictions

                    gc.collect()


            # =================================================
            # STAGE COMPLETE
            # =================================================

            stage_results_df = (
                build_local_resnet50_rf_stage_results(

                    progress_df,
                    candidate_manifest_df,
                    active_candidate_ids,

                    stage_number,
                    number_of_trees,
                )
            )


            stage_results_path = (
                search_progress_directory
                / (
                    f"stage_{stage_number:02d}"
                    "_results.csv"
                )
            )


            resnet50_rf_save_dataframe_atomic(
                stage_results_df,
                stage_results_path,
            )


            all_stage_results.append(
                stage_results_df.copy()
            )


            # -------------------------------------------------
            # Successive-halving survivor count
            # -------------------------------------------------

            if stage_number < 4:

                number_to_keep = (
                    math.ceil(
                        len(
                            active_candidate_ids
                        )
                        /
                        RESNET50_RF_HALVING_FACTOR
                    )
                )


            else:

                number_to_keep = 1


            selected_candidate_ids = (
                stage_results_df[
                    "candidate_id"
                ]
                .head(
                    number_to_keep
                )
                .astype(int)
                .tolist()
            )


            selected_candidates_df = (
                stage_results_df[
                    stage_results_df[
                        "candidate_id"
                    ]
                    .isin(
                        selected_candidate_ids
                    )
                ]
                .copy()
            )


            selected_candidates_path = (
                search_progress_directory
                / (
                    f"stage_{stage_number:02d}"
                    "_selected_candidates.csv"
                )
            )


            resnet50_rf_save_dataframe_atomic(
                selected_candidates_df,
                selected_candidates_path,
            )


            print(
                "\nStage complete."
            )


            print(
                "Best mean inner macro-F1:",
                round(
                    float(
                        stage_results_df[
                            "mean_test_score"
                        ]
                        .iloc[0]
                    ),
                    6,
                ),
            )


            print(
                "Candidates advancing:",
                number_to_keep,
            )


            print(
                "IDs:",
                selected_candidate_ids,
            )


            active_candidate_ids = (
                selected_candidate_ids
            )


        # ====================================================
        # INNER SEARCH WINNER
        # ====================================================

        assert len(
            all_stage_results
        ) == 4


        final_stage_results_df = (
            all_stage_results[
                -1
            ]
        )


        assert len(
            final_stage_results_df
        ) == 4


        winner_row = (
            final_stage_results_df
            .iloc[0]
        )


        winning_candidate_id = int(
            winner_row[
                "candidate_id"
            ]
        )


        winning_candidate_row = (
            candidate_manifest_df[
                candidate_manifest_df[
                    "candidate_id"
                ]
                == winning_candidate_id
            ]
            .iloc[0]
        )


        winning_parameters = (
            resnet50_rf_candidate_parameters_from_row(
                winning_candidate_row
            )
        )


        best_inner_macro_f1 = float(
            winner_row[
                "mean_test_score"
            ]
        )


        selected_n_estimators = 675


        # ====================================================
        # SAVE COMPLETE 150-CANDIDATE-STAGE RESULT TABLE
        # ====================================================

        complete_search_results_df = (
            pd.concat(
                all_stage_results,
                ignore_index=True,
            )
        )


        assert len(
            complete_search_results_df
        ) == 150


        resnet50_rf_save_dataframe_atomic(

            complete_search_results_df,

            paths[
                "search_results"
            ],
        )


        # ====================================================
        # SEARCH COMPLETE CHECKPOINT
        # ====================================================

        search_summary = {

            "status":
                "completed",

            "model":
                "ResNet50_fixed_features_RF",

            "repeat":
                int(
                    repeat_number
                ),

            "outer_fold":
                int(
                    fold_number
                ),

            "winning_candidate_id":
                int(
                    winning_candidate_id
                ),

            "winning_parameters":
                winning_parameters,

            "selected_n_estimators":
                675,

            "best_inner_macro_f1":
                float(
                    best_inner_macro_f1
                ),

            "inner_cv_seed":
                int(
                    get_hybrid_inner_cv_seed(
                        repeat_number,
                        fold_number,
                    )
                ),

            "model_seed":
                int(
                    get_hybrid_rf_model_seed(
                        repeat_number,
                        fold_number,
                    )
                ),

            "search_seed":
                int(
                    get_hybrid_rf_search_seed(
                        repeat_number,
                        fold_number,
                    )
                ),

            "required_inner_fits":
                450,
        }


        resnet50_rf_save_json_atomic(
            search_summary,
            search_complete_path,
        )


        print(
            "\n"
            + "=" * 88
        )


        print(
            "INNER SEARCH COMPLETE"
        )


        print(
            "=" * 88
        )


        print(
            "Winning candidate:",
            winning_candidate_id,
        )


        print(
            "Winning parameters:",
            winning_parameters,
        )


        print(
            "Best inner macro-F1:",
            round(
                best_inner_macro_f1,
                6,
            ),
        )


    # ========================================================
    # 7D. LOAD SAVED WINNER
    # ========================================================

    winning_candidate_id = int(
        search_summary[
            "winning_candidate_id"
        ]
    )


    winning_parameters = (
        search_summary[
            "winning_parameters"
        ]
    )


    selected_n_estimators = int(
        search_summary[
            "selected_n_estimators"
        ]
    )


    best_inner_macro_f1 = float(
        search_summary[
            "best_inner_macro_f1"
        ]
    )


    assert (
        selected_n_estimators
        == 675
    )


    # ========================================================
    # 7E. FINAL REFIT
    #
    # Winner trained on all 4,480 outer-training images.
    # ========================================================

    print(
        "\nRefitting winner on all "
        "4,480 outer-training samples..."
    )


    final_refit_start = (
        time.perf_counter()
    )


    final_model = (
        RandomForestClassifier(

            **winning_parameters,

            n_estimators=675,

            random_state=
                get_hybrid_rf_model_seed(
                    repeat_number,
                    fold_number,
                ),

            n_jobs=-1,
        )
    )


    final_model.fit(
        X_outer_train,
        y_outer_train,
    )


    final_refit_seconds = (
        time.perf_counter()
        - final_refit_start
    )


    # ========================================================
    # 7F. OUTER VALIDATION — EXACTLY ONCE
    # ========================================================

    prediction_start = (
        time.perf_counter()
    )


    outer_predictions = (
        final_model.predict(
            X_outer_validation
        )
    )


    prediction_seconds = (
        time.perf_counter()
        - prediction_start
    )


    outer_predictions = np.asarray(
        outer_predictions,
        dtype=int,
    )


    assert len(
        outer_predictions
    ) == 1120


    # ========================================================
    # 7G. OUTER METRICS
    # ========================================================

    outer_accuracy = float(
        accuracy_score(
            y_outer_validation,
            outer_predictions,
        )
    )


    outer_balanced_accuracy = float(
        balanced_accuracy_score(
            y_outer_validation,
            outer_predictions,
        )
    )


    outer_macro_precision = float(
        precision_score(
            y_outer_validation,
            outer_predictions,
            average="macro",
            zero_division=0,
        )
    )


    outer_macro_recall = float(
        recall_score(
            y_outer_validation,
            outer_predictions,
            average="macro",
            zero_division=0,
        )
    )


    outer_macro_f1 = float(
        f1_score(
            y_outer_validation,
            outer_predictions,
            average="macro",
        )
    )


    outer_confusion_matrix = (
        confusion_matrix(
            y_outer_validation,
            outer_predictions,
            labels=[
                0,
                1,
                2,
                3,
            ],
        )
    )


    outer_classification_report = (
        classification_report(
            y_outer_validation,
            outer_predictions,
            labels=[
                0,
                1,
                2,
                3,
            ],
            target_names=
                CLASS_NAMES,
            output_dict=True,
            zero_division=0,
        )
    )


    # ========================================================
    # 7H. OUTER PREDICTIONS TABLE
    # ========================================================

    predictions_df = pd.DataFrame(
        {
            "relative_path":
                outer_validation_paths,

            "true_label":
                y_outer_validation,

            "predicted_label":
                outer_predictions,
        }
    )


    predictions_df[
        "true_class"
    ] = (
        predictions_df[
            "true_label"
        ]
        .map(
            INDEX_TO_CLASS
        )
    )


    predictions_df[
        "predicted_class"
    ] = (
        predictions_df[
            "predicted_label"
        ]
        .map(
            INDEX_TO_CLASS
        )
    )


    assert len(
        predictions_df
    ) == 1120


    assert (
        predictions_df[
            "relative_path"
        ]
        .nunique()
        == 1120
    )


    # ========================================================
    # 7I. ACCUMULATED INNER FIT TIME
    # ========================================================

    saved_progress_df = pd.read_csv(
        progress_path
    )


    assert len(
        saved_progress_df
    ) == 450


    cumulative_inner_fit_seconds = float(
        saved_progress_df[
            "fit_seconds"
        ]
        .sum()
    )


    # ========================================================
    # 7J. SELECTED PARAMETERS
    # ========================================================

    selected_parameters = {

        "model":
            "ResNet50_fixed_features_RF",

        "feature_dimension":
            2048,

        "repeat":
            int(
                repeat_number
            ),

        "fold":
            int(
                fold_number
            ),

        "outer_split_seed":
            int(
                partition[
                    "split_seed"
                ]
            ),

        "inner_cv_seed":
            int(
                get_hybrid_inner_cv_seed(
                    repeat_number,
                    fold_number,
                )
            ),

        "rf_model_seed":
            int(
                get_hybrid_rf_model_seed(
                    repeat_number,
                    fold_number,
                )
            ),

        "rf_search_seed":
            int(
                get_hybrid_rf_search_seed(
                    repeat_number,
                    fold_number,
                )
            ),

        "inner_cv_folds":
            3,

        "selection_metric":
            "f1_macro",

        "search_method":
            "manually_checkpointed_successive_halving",

        "initial_candidates":
            100,

        "halving_factor":
            3,

        "resource":
            "n_estimators",

        "tree_resources":
            [
                25,
                75,
                225,
                675,
            ],

        "candidate_counts_by_iteration":
            {
                "0": 100,
                "1": 34,
                "2": 12,
                "3": 4,
            },

        "winning_candidate_id":
            int(
                winning_candidate_id
            ),

        "selected_n_estimators":
            675,

        "best_inner_macro_f1":
            float(
                best_inner_macro_f1
            ),

        "best_parameters":
            winning_parameters,
    }


    # ========================================================
    # 7K. OUTER METRICS
    # ========================================================

    outer_metrics = {

        "model":
            "ResNet50_fixed_features_RF",

        "feature_dimension":
            2048,

        "repeat":
            int(
                repeat_number
            ),

        "fold":
            int(
                fold_number
            ),

        "outer_split_seed":
            int(
                partition[
                    "split_seed"
                ]
            ),

        "inner_cv_seed":
            int(
                get_hybrid_inner_cv_seed(
                    repeat_number,
                    fold_number,
                )
            ),

        "rf_model_seed":
            int(
                get_hybrid_rf_model_seed(
                    repeat_number,
                    fold_number,
                )
            ),

        "rf_search_seed":
            int(
                get_hybrid_rf_search_seed(
                    repeat_number,
                    fold_number,
                )
            ),

        "outer_training_samples":
            4480,

        "outer_validation_samples":
            1120,

        "winning_candidate_id":
            int(
                winning_candidate_id
            ),

        "selected_n_estimators":
            675,

        "best_inner_macro_f1":
            float(
                best_inner_macro_f1
            ),

        "accuracy":
            float(
                outer_accuracy
            ),

        "balanced_accuracy":
            float(
                outer_balanced_accuracy
            ),

        "macro_precision":
            float(
                outer_macro_precision
            ),

        "macro_recall":
            float(
                outer_macro_recall
            ),

        "macro_f1":
            float(
                outer_macro_f1
            ),

        "confusion_matrix":
            outer_confusion_matrix.tolist(),

        "classification_report":
            outer_classification_report,

        "cumulative_inner_fit_seconds":
            float(
                cumulative_inner_fit_seconds
            ),

        "final_refit_seconds":
            float(
                final_refit_seconds
            ),

        "prediction_seconds":
            float(
                prediction_seconds
            ),
    }


    # ========================================================
    # 7L. SAVE FINAL OUTPUT FILES
    # ========================================================

    assert (
        paths[
            "search_results"
        ]
        .exists()
    )


    resnet50_rf_save_json_atomic(
        selected_parameters,
        paths[
            "selected_parameters"
        ],
    )


    resnet50_rf_save_dataframe_atomic(
        predictions_df,
        paths[
            "outer_predictions"
        ],
    )


    resnet50_rf_save_json_atomic(
        outer_metrics,
        paths[
            "outer_metrics"
        ],
    )


    # ========================================================
    # 7M. VERIFY SAVED OUTPUTS
    # ========================================================

    saved_search_results = pd.read_csv(
        paths[
            "search_results"
        ]
    )


    saved_predictions = pd.read_csv(
        paths[
            "outer_predictions"
        ]
    )


    assert len(
        saved_search_results
    ) == 150


    assert (
        (
            saved_search_results[
                "iter"
            ]
            .astype(int)
            == 0
        )
        .sum()
        == 100
    )


    assert (
        (
            saved_search_results[
                "iter"
            ]
            .astype(int)
            == 1
        )
        .sum()
        == 34
    )


    assert (
        (
            saved_search_results[
                "iter"
            ]
            .astype(int)
            == 2
        )
        .sum()
        == 12
    )


    assert (
        (
            saved_search_results[
                "iter"
            ]
            .astype(int)
            == 3
        )
        .sum()
        == 4
    )


    assert len(
        saved_predictions
    ) == 1120


    # ========================================================
    # 7N. COMPLETED.JSON MUST BE WRITTEN LAST
    # ========================================================

    completion_information = {

        "status":
            "completed",

        "model":
            "ResNet50_fixed_features_RF",

        "repeat":
            int(
                repeat_number
            ),

        "fold":
            int(
                fold_number
            ),

        "outer_split_seed":
            int(
                partition[
                    "split_seed"
                ]
            ),

        "inner_cv_seed":
            int(
                get_hybrid_inner_cv_seed(
                    repeat_number,
                    fold_number,
                )
            ),

        "rf_model_seed":
            int(
                get_hybrid_rf_model_seed(
                    repeat_number,
                    fold_number,
                )
            ),

        "rf_search_seed":
            int(
                get_hybrid_rf_search_seed(
                    repeat_number,
                    fold_number,
                )
            ),

        "inner_search_completed":
            True,

        "outer_evaluation_completed":
            True,

        "required_outputs_verified":
            True,
    }


    resnet50_rf_save_json_atomic(
        completion_information,
        paths[
            "completion_marker"
        ],
    )


    # ========================================================
    # 7O. FINAL FOLD VALIDATION
    # ========================================================

    assert (
        is_checkpointed_resnet50_rf_fold_complete(
            repeat_number,
            fold_number,
        )
    )


    print(
        "\n"
        + "=" * 88
    )


    print(
        f"R{repeat_number:02d}/"
        f"F{fold_number:02d} COMPLETE"
    )


    print(
        "=" * 88
    )


    print(
        "Winner:",
        winning_candidate_id,
    )


    print(
        "Best inner macro-F1:",
        round(
            best_inner_macro_f1,
            6,
        ),
    )


    print(
        "Outer accuracy:",
        round(
            outer_accuracy,
            6,
        ),
    )


    print(
        "Outer balanced accuracy:",
        round(
            outer_balanced_accuracy,
            6,
        ),
    )


    print(
        "Outer macro-F1:",
        round(
            outer_macro_f1,
            6,
        ),
    )


    print(
        "Accumulated inner fitting:",
        round(
            cumulative_inner_fit_seconds
            / 60,
            2,
        ),
        "minutes",
    )


    print(
        "Final refit:",
        round(
            final_refit_seconds,
            2,
        ),
        "seconds",
    )


    print(
        "COMPLETED.json written LAST."
    )


    del final_model
    del outer_predictions

    del X_outer_train
    del y_outer_train

    del X_outer_validation
    del y_outer_validation

    del partition

    gc.collect()


    return "completed"


# ============================================================
# 8. COUNT FULLY COMPLETED LOCAL OUTER FOLDS
# ============================================================

def count_completed_local_resnet50_rf_folds():

    completed = []


    for repeat_number in range(
        1,
        11,
    ):

        for fold_number in range(
            1,
            6,
        ):

            if (
                is_checkpointed_resnet50_rf_fold_complete(
                    repeat_number,
                    fold_number,
                )
            ):

                completed.append(
                    (
                        repeat_number,
                        fold_number,
                    )
                )


    return completed


# ============================================================
# 9. RUN ALL 10 REPEATS × 5 OUTER FOLDS
# ============================================================

master_start_time = (
    time.perf_counter()
)


newly_completed_folds = 0

skipped_folds = 0


for repeat_number in range(
    1,
    11,
):

    print(
        "\n"
        + "#" * 88
    )


    print(
        f"STARTING REPEAT "
        f"{repeat_number}/10"
    )


    print(
        "#" * 88
    )


    for fold_number in range(
        1,
        6,
    ):

        fold_status = (
            run_local_checkpointed_resnet50_rf_outer_fold(
                repeat_number,
                fold_number,
            )
        )


        if (
            fold_status
            == "completed"
        ):

            newly_completed_folds += 1


        elif (
            fold_status
            == "skipped"
        ):

            skipped_folds += 1


        current_completed = (
            count_completed_local_resnet50_rf_folds()
        )


        print(
            "\nLOCAL RESNET50 + RF PROGRESS:",
            len(
                current_completed
            ),
            "/ 50 outer folds complete"
        )


# ============================================================
# 10. FINAL SESSION STATUS
# ============================================================

completed_local_folds = (
    count_completed_local_resnet50_rf_folds()
)


session_seconds = (
    time.perf_counter()
    - master_start_time
)


print(
    "\n"
    + "=" * 88
)


print(
    "LOCAL RESNET50 + RF SESSION FINISHED"
)


print(
    "=" * 88
)


print(
    "Completed outer folds:",
    len(
        completed_local_folds
    ),
    "/ 50",
)


print(
    "New folds completed this session:",
    newly_completed_folds,
)


print(
    "Previously completed folds skipped:",
    skipped_folds,
)


print(
    "Session runtime:",
    round(
        session_seconds
        / 60,
        2,
    ),
    "minutes",
)


print(
    "\nLocal results:"
)


print(
    RESNET50_RF_RESULTS_ROOT
)


if len(
    completed_local_folds
) == 50:

    print(
        "\nALL 50 LOCAL RESNET50 + RF "
        "OUTER FOLDS ARE COMPLETE."
    )


else:

    print(
        "\nExperiment is not complete yet."
    )


    print(
        "If this process is interrupted, rerun "
        "THIS SAME CELL."
    )


    print(
        "Saved candidate × inner-fold fits "
        "will be skipped automatically."
    )


print(
    "\nTesting partition was NEVER accessed."
)


print(
    "\nRESNET50 + RF — LOCAL PC MASTER RUNNER: PASSED"
)

########################################################################################
STARTING REPEAT 1/10
########################################################################################

R01/F01 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R01/F02 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R01/F03 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R01/F04 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R01/F05 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

########################################################################################
STARTING REPEAT 2/10
########################################################################################

R02/F01 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R02/F02 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R02/F03 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R02/F04 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R02/F05 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

########################################################################################
STARTING REPEAT 3/10
########################################################################################

R03/F01 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R03/F02 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R03/F03 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R03/F04 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R03/F05 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

########################################################################################
STARTING REPEAT 4/10
########################################################################################

R04/F01 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R04/F02 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R04/F03 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R04/F04 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R04/F05 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

########################################################################################
STARTING REPEAT 5/10
########################################################################################

R05/F01 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R05/F02 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R05/F03 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R05/F04 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R05/F05 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

########################################################################################
STARTING REPEAT 6/10
########################################################################################

R06/F01 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R06/F02 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R06/F03 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R06/F04 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R06/F05 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

########################################################################################
STARTING REPEAT 7/10
########################################################################################

R07/F01 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R07/F02 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R07/F03 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R07/F04 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

R07/F05 already COMPLETE -> SKIPPED

LOCAL RESNET50 + RF PROGRESS: 35 / 50 outer folds complete

########################################################################################
STARTING REPEAT 8/10
########################################################################################

========================================================================================
RESNET50 FIXED FEATURES + RANDOM FOREST
REPEAT 08 / FOLD 01
========================================================================================
Outer training: (4480, 2048)
Outer validation: (1120, 2048)
Split seed: 202608
Inner-CV seed: 303801
RF model seed: 404801
RF search seed: 414801
Loaded existing candidate manifest.
Loaded checkpoint: 157 completed inner fits.

----------------------------------------------------------------------------------------
STAGE 1/4
----------------------------------------------------------------------------------------
Trees: 25
Candidates: 100
Stage 1 | Candidate 1/100 | ID 001 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 1/100 | ID 001 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 1/100 | ID 001 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 2/100 | ID 002 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 2/100 | ID 002 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 2/100 | ID 002 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 3/100 | ID 003 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 3/100 | ID 003 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 3/100 | ID 003 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 4/100 | ID 004 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 4/100 | ID 004 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 4/100 | ID 004 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 5/100 | ID 005 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 5/100 | ID 005 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 5/100 | ID 005 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 6/100 | ID 006 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 6/100 | ID 006 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 6/100 | ID 006 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 7/100 | ID 007 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 7/100 | ID 007 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 7/100 | ID 007 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 8/100 | ID 008 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 8/100 | ID 008 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 8/100 | ID 008 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 9/100 | ID 009 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 9/100 | ID 009 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 9/100 | ID 009 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 10/100 | ID 010 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 10/100 | ID 010 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 10/100 | ID 010 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 11/100 | ID 011 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 11/100 | ID 011 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 11/100 | ID 011 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 12/100 | ID 012 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 12/100 | ID 012 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 12/100 | ID 012 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 13/100 | ID 013 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 13/100 | ID 013 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 13/100 | ID 013 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 14/100 | ID 014 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 14/100 | ID 014 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 14/100 | ID 014 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 15/100 | ID 015 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 15/100 | ID 015 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 15/100 | ID 015 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 16/100 | ID 016 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 16/100 | ID 016 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 16/100 | ID 016 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 17/100 | ID 017 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 17/100 | ID 017 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 17/100 | ID 017 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 18/100 | ID 018 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 18/100 | ID 018 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 18/100 | ID 018 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 19/100 | ID 019 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 19/100 | ID 019 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 19/100 | ID 019 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 20/100 | ID 020 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 20/100 | ID 020 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 20/100 | ID 020 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 21/100 | ID 021 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 21/100 | ID 021 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 21/100 | ID 021 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 22/100 | ID 022 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 22/100 | ID 022 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 22/100 | ID 022 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 23/100 | ID 023 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 23/100 | ID 023 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 23/100 | ID 023 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 24/100 | ID 024 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 24/100 | ID 024 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 24/100 | ID 024 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 25/100 | ID 025 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 25/100 | ID 025 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 25/100 | ID 025 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 26/100 | ID 026 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 26/100 | ID 026 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 26/100 | ID 026 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 27/100 | ID 027 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 27/100 | ID 027 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 27/100 | ID 027 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 28/100 | ID 028 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 28/100 | ID 028 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 28/100 | ID 028 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 29/100 | ID 029 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 29/100 | ID 029 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 29/100 | ID 029 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 30/100 | ID 030 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 30/100 | ID 030 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 30/100 | ID 030 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 31/100 | ID 031 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 31/100 | ID 031 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 31/100 | ID 031 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 32/100 | ID 032 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 32/100 | ID 032 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 32/100 | ID 032 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 33/100 | ID 033 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 33/100 | ID 033 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 33/100 | ID 033 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 34/100 | ID 034 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 34/100 | ID 034 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 34/100 | ID 034 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 35/100 | ID 035 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 35/100 | ID 035 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 35/100 | ID 035 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 36/100 | ID 036 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 36/100 | ID 036 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 36/100 | ID 036 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 37/100 | ID 037 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 37/100 | ID 037 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 37/100 | ID 037 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 38/100 | ID 038 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 38/100 | ID 038 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 38/100 | ID 038 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 39/100 | ID 039 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 39/100 | ID 039 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 39/100 | ID 039 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 40/100 | ID 040 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 40/100 | ID 040 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 40/100 | ID 040 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 41/100 | ID 041 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 41/100 | ID 041 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 41/100 | ID 041 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 42/100 | ID 042 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 42/100 | ID 042 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 42/100 | ID 042 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 43/100 | ID 043 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 43/100 | ID 043 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 43/100 | ID 043 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 44/100 | ID 044 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 44/100 | ID 044 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 44/100 | ID 044 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 45/100 | ID 045 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 45/100 | ID 045 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 45/100 | ID 045 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 46/100 | ID 046 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 46/100 | ID 046 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 46/100 | ID 046 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 47/100 | ID 047 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 47/100 | ID 047 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 47/100 | ID 047 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 48/100 | ID 048 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 48/100 | ID 048 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 48/100 | ID 048 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 49/100 | ID 049 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 49/100 | ID 049 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 49/100 | ID 049 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 50/100 | ID 050 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 50/100 | ID 050 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 50/100 | ID 050 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 51/100 | ID 051 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 51/100 | ID 051 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 51/100 | ID 051 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 52/100 | ID 052 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 52/100 | ID 052 | Inner 2/3 -> SKIPPED
Stage 1 | Candidate 52/100 | ID 052 | Inner 3/3 -> SKIPPED
Stage 1 | Candidate 53/100 | ID 053 | Inner 1/3 -> SKIPPED
Stage 1 | Candidate 53/100 | ID 053 | Inner 2/3 | F1=0.861353 | 5.71s | CHECKPOINT SAVED
Stage 1 | Candidate 53/100 | ID 053 | Inner 3/3 | F1=0.883684 | 5.19s | CHECKPOINT SAVED
Stage 1 | Candidate 54/100 | ID 054 | Inner 1/3 | F1=0.875438 | 1.01s | CHECKPOINT SAVED
Stage 1 | Candidate 54/100 | ID 054 | Inner 2/3 | F1=0.869498 | 1.15s | CHECKPOINT SAVED
Stage 1 | Candidate 54/100 | ID 054 | Inner 3/3 | F1=0.895686 | 1.04s | CHECKPOINT SAVED
Stage 1 | Candidate 55/100 | ID 055 | Inner 1/3 | F1=0.867695 | 1.57s | CHECKPOINT SAVED
Stage 1 | Candidate 55/100 | ID 055 | Inner 2/3 | F1=0.872391 | 1.60s | CHECKPOINT SAVED
Stage 1 | Candidate 55/100 | ID 055 | Inner 3/3 | F1=0.874191 | 1.50s | CHECKPOINT SAVED
Stage 1 | Candidate 56/100 | ID 056 | Inner 1/3 | F1=0.897867 | 6.60s | CHECKPOINT SAVED
Stage 1 | Candidate 56/100 | ID 056 | Inner 2/3 | F1=0.873157 | 6.40s | CHECKPOINT SAVED
Stage 1 | Candidate 56/100 | ID 056 | Inner 3/3 | F1=0.887385 | 6.80s | CHECKPOINT SAVED
Stage 1 | Candidate 57/100 | ID 057 | Inner 1/3 | F1=0.861899 | 1.45s | CHECKPOINT SAVED
Stage 1 | Candidate 57/100 | ID 057 | Inner 2/3 | F1=0.862931 | 1.43s | CHECKPOINT SAVED
Stage 1 | Candidate 57/100 | ID 057 | Inner 3/3 | F1=0.874893 | 1.36s | CHECKPOINT SAVED
Stage 1 | Candidate 58/100 | ID 058 | Inner 1/3 | F1=0.870671 | 2.70s | CHECKPOINT SAVED
Stage 1 | Candidate 58/100 | ID 058 | Inner 2/3 | F1=0.865381 | 2.82s | CHECKPOINT SAVED
Stage 1 | Candidate 58/100 | ID 058 | Inner 3/3 | F1=0.886431 | 2.57s | CHECKPOINT SAVED
Stage 1 | Candidate 59/100 | ID 059 | Inner 1/3 | F1=0.873272 | 3.57s | CHECKPOINT SAVED
Stage 1 | Candidate 59/100 | ID 059 | Inner 2/3 | F1=0.857255 | 3.45s | CHECKPOINT SAVED
Stage 1 | Candidate 59/100 | ID 059 | Inner 3/3 | F1=0.883949 | 3.73s | CHECKPOINT SAVED
Stage 1 | Candidate 60/100 | ID 060 | Inner 1/3 | F1=0.889695 | 6.13s | CHECKPOINT SAVED
Stage 1 | Candidate 60/100 | ID 060 | Inner 2/3 | F1=0.871875 | 6.28s | CHECKPOINT SAVED
Stage 1 | Candidate 60/100 | ID 060 | Inner 3/3 | F1=0.880859 | 6.38s | CHECKPOINT SAVED
Stage 1 | Candidate 61/100 | ID 061 | Inner 1/3 | F1=0.861956 | 0.82s | CHECKPOINT SAVED
Stage 1 | Candidate 61/100 | ID 061 | Inner 2/3 | F1=0.852086 | 0.68s | CHECKPOINT SAVED
Stage 1 | Candidate 61/100 | ID 061 | Inner 3/3 | F1=0.878895 | 0.79s | CHECKPOINT SAVED
Stage 1 | Candidate 62/100 | ID 062 | Inner 1/3 | F1=0.880418 | 1.09s | CHECKPOINT SAVED
Stage 1 | Candidate 62/100 | ID 062 | Inner 2/3 | F1=0.869963 | 1.30s | CHECKPOINT SAVED
Stage 1 | Candidate 62/100 | ID 062 | Inner 3/3 | F1=0.887002 | 1.11s | CHECKPOINT SAVED
Stage 1 | Candidate 63/100 | ID 063 | Inner 1/3 | F1=0.885553 | 0.83s | CHECKPOINT SAVED
Stage 1 | Candidate 63/100 | ID 063 | Inner 2/3 | F1=0.864044 | 0.82s | CHECKPOINT SAVED
Stage 1 | Candidate 63/100 | ID 063 | Inner 3/3 | F1=0.874247 | 0.95s | CHECKPOINT SAVED
Stage 1 | Candidate 64/100 | ID 064 | Inner 1/3 | F1=0.867081 | 5.48s | CHECKPOINT SAVED
Stage 1 | Candidate 64/100 | ID 064 | Inner 2/3 | F1=0.857908 | 5.93s | CHECKPOINT SAVED
Stage 1 | Candidate 64/100 | ID 064 | Inner 3/3 | F1=0.872061 | 5.62s | CHECKPOINT SAVED
Stage 1 | Candidate 65/100 | ID 065 | Inner 1/3 | F1=0.875861 | 0.84s | CHECKPOINT SAVED
Stage 1 | Candidate 65/100 | ID 065 | Inner 2/3 | F1=0.869955 | 0.88s | CHECKPOINT SAVED
Stage 1 | Candidate 65/100 | ID 065 | Inner 3/3 | F1=0.885630 | 0.92s | CHECKPOINT SAVED
Stage 1 | Candidate 66/100 | ID 066 | Inner 1/3 | F1=0.847303 | 0.35s | CHECKPOINT SAVED
Stage 1 | Candidate 66/100 | ID 066 | Inner 2/3 | F1=0.841903 | 0.35s | CHECKPOINT SAVED
Stage 1 | Candidate 66/100 | ID 066 | Inner 3/3 | F1=0.865605 | 0.40s | CHECKPOINT SAVED
Stage 1 | Candidate 67/100 | ID 067 | Inner 1/3 | F1=0.872128 | 1.21s | CHECKPOINT SAVED
Stage 1 | Candidate 67/100 | ID 067 | Inner 2/3 | F1=0.858300 | 1.24s | CHECKPOINT SAVED
Stage 1 | Candidate 67/100 | ID 067 | Inner 3/3 | F1=0.884919 | 1.22s | CHECKPOINT SAVED
Stage 1 | Candidate 68/100 | ID 068 | Inner 1/3 | F1=0.871554 | 0.80s | CHECKPOINT SAVED
Stage 1 | Candidate 68/100 | ID 068 | Inner 2/3 | F1=0.863492 | 0.79s | CHECKPOINT SAVED
Stage 1 | Candidate 68/100 | ID 068 | Inner 3/3 | F1=0.872317 | 0.84s | CHECKPOINT SAVED
Stage 1 | Candidate 69/100 | ID 069 | Inner 1/3 | F1=0.851367 | 0.51s | CHECKPOINT SAVED
Stage 1 | Candidate 69/100 | ID 069 | Inner 2/3 | F1=0.851277 | 0.40s | CHECKPOINT SAVED
Stage 1 | Candidate 69/100 | ID 069 | Inner 3/3 | F1=0.869838 | 0.47s | CHECKPOINT SAVED
Stage 1 | Candidate 70/100 | ID 070 | Inner 1/3 | F1=0.861956 | 0.78s | CHECKPOINT SAVED
Stage 1 | Candidate 70/100 | ID 070 | Inner 2/3 | F1=0.852086 | 0.78s | CHECKPOINT SAVED
Stage 1 | Candidate 70/100 | ID 070 | Inner 3/3 | F1=0.878895 | 0.71s | CHECKPOINT SAVED
Stage 1 | Candidate 71/100 | ID 071 | Inner 1/3 | F1=0.868117 | 3.43s | CHECKPOINT SAVED
Stage 1 | Candidate 71/100 | ID 071 | Inner 2/3 | F1=0.853057 | 3.24s | CHECKPOINT SAVED
Stage 1 | Candidate 71/100 | ID 071 | Inner 3/3 | F1=0.881635 | 3.34s | CHECKPOINT SAVED
Stage 1 | Candidate 72/100 | ID 072 | Inner 1/3 | F1=0.862731 | 0.70s | CHECKPOINT SAVED

KeyboardInterrupt:

In [ ]:
# ============================================================
# ResNet50 hybrid experiment - environment check
# ============================================================

import sys
import tensorflow as tf
import sklearn

print("Python version: ", sys.version)
print("TensorFlow version: ", tf.__version__)
print("Keras version: ", tf.keras.__version__)
print("Scikit-Learn version: ", sklearn.__version__)

gpu_devices = tf.config.list_physical_devices("GPU")

if gpu_devices:
    print("GPU is available")
else:
    print("No GPU is available")

!nvidia-smi --query-gpu=name --format=csv,noheader

Python version:  3.13.15 (main, Aug  6 2026, 11:06:23) [GCC 11.4.0]
TensorFlow version:  2.20.0
Keras version:  3.13.2
Scikit-Learn version:  1.6.1
No GPU is available
/bin/bash: line 1: nvidia-smi: command not found

In [1]:
# Accessing the google drive for the data

from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive

In [2]:
from google.colab import files

uploaded = files.upload()

Saving repeated_stratified_5fold_assignments.csv to repeated_stratified_5fold_assignments.csv

In [3]:
import shutil
import tarfile

from pathlib import Path


# ============================================================
# RESTORE THE PROJECT DATASET TO THE COLAB RUNTIME
# ============================================================

# Create the path to the project archive stored in Google Drive
DRIVE_ARCHIVE = Path("/content/drive/MyDrive/brain_tumour_colab/brain_tumour_colab_bundle.tar")


# Create the local path where the archive will temporarily be copied
LOCAL_ARCHIVE = Path("/content/brain_tumour_colab_bundle.tar")


# Create the path where the project will be restored
PROJECT_ROOT = Path("/content/brain-tumour-mri-classification")


print("=" * 70)
print("RESTORE PROJECT DATA")
print("=" * 70)
print("Drive archive:", DRIVE_ARCHIVE)
print("Drive archive exists:", DRIVE_ARCHIVE.exists())
print("Project root:", PROJECT_ROOT)


# Stop if the project archive cannot be found in Google Drive
if not DRIVE_ARCHIVE.exists():
    raise FileNotFoundError(f"Archive not found: {DRIVE_ARCHIVE}")


# Restore the project only if it is not already present in the runtime
if not PROJECT_ROOT.exists():

    print("\nCopying archive to Colab runtime...")
    shutil.copy2(DRIVE_ARCHIVE, LOCAL_ARCHIVE)


    # Create the project directory
    PROJECT_ROOT.mkdir(parents=True, exist_ok=True)


    print("Extracting archive...")

    with tarfile.open(LOCAL_ARCHIVE, "r") as archive:
        archive.extractall(PROJECT_ROOT, filter="data")

else:
    print("\nProject directory already exists. Skipping archive extraction.")


# ============================================================
# VERIFY THE RESTORED PROJECT
# ============================================================

# Create the path to the fixed five-fold cross-validation file
FOLDS_FILE = (PROJECT_ROOT / "splits" / "five_fold_cross_validation.csv")


# Create the path to the cropped Training and Testing dataset
DATA_DIR = (PROJECT_ROOT / "processed_data_cropped")


# Count every PNG image in the cropped dataset
png_image_count = len(list(DATA_DIR.rglob("*.png")))

print("\n--- Verification ---")
print("Project root exists:", PROJECT_ROOT.exists())
print("Fold file exists:", FOLDS_FILE.exists())
print("Dataset folder exists:", DATA_DIR.exists())
print("PNG images found:", png_image_count)


# Stop if the project was not restored correctly
if not FOLDS_FILE.exists():
    raise FileNotFoundError(f"Five-fold cross-validation file not found: {FOLDS_FILE}")


if not DATA_DIR.exists():
    raise FileNotFoundError(f"Cropped dataset folder not found: {DATA_DIR}")


if png_image_count != 7198:
    raise RuntimeError("Expected 7,198 PNG images, "f"but found {png_image_count}.")

print("\nProject restored successfully.")

======================================================================
RESTORE PROJECT DATA
======================================================================
Drive archive: /content/drive/MyDrive/brain_tumour_colab/brain_tumour_colab_bundle.tar
Drive archive exists: True
Project root: /content/brain-tumour-mri-classification

Copying archive to Colab runtime...
Extracting archive...

--- Verification ---
Project root exists: True
Fold file exists: True
Dataset folder exists: True
PNG images found: 7198

Project restored successfully.

In [4]:
# ============================================================
# VALIDATE THE REPEATED 10 x 5 CROSS-VALIDATION ASSIGNMENTS
# ============================================================

from pathlib import Path
import shutil
import pandas as pd


UPLOADED_SPLIT_FILE = Path(
    "/content/repeated_stratified_5fold_assignments.csv"
)

REPEATED_SPLITS_DIR = (
    PROJECT_ROOT
    / "repeated_cv"
    / "splits"
)

REPEATED_SPLITS_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

REPEATED_FOLDS_FILE = (
    REPEATED_SPLITS_DIR
    / "repeated_stratified_5fold_assignments.csv"
)


# Copy the uploaded file into the restored project structure
shutil.copy2(
    UPLOADED_SPLIT_FILE,
    REPEATED_FOLDS_FILE,
)


# Load the assignments
repeated_folds_df = pd.read_csv(
    REPEATED_FOLDS_FILE
)


# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

assert len(repeated_folds_df) == 56000

assert repeated_folds_df["repeat"].nunique() == 10

assert set(
    repeated_folds_df["repeat"]
) == set(range(1, 11))

assert set(
    repeated_folds_df["fold"]
) == {1, 2, 3, 4, 5}

assert (
    repeated_folds_df
    .groupby(
        ["repeat", "fold"]
    )
    .size()
    .eq(1120)
    .all()
)

assert (
    repeated_folds_df
    .groupby(
        ["repeat", "fold", "class"]
    )
    .size()
    .eq(280)
    .all()
)

assert (
    repeated_folds_df[
        "relative_path"
    ]
    .str.startswith("Training/")
    .all()
)


print(
    "Repeated split file:",
    REPEATED_FOLDS_FILE,
)

print(
    "Rows:",
    len(repeated_folds_df),
)

print(
    "Repeats:",
    repeated_folds_df[
        "repeat"
    ].nunique(),
)

print(
    "Folds per repeat:",
    repeated_folds_df[
        "fold"
    ].nunique(),
)

print(
    "\nSplit seeds:"
)

print(
    repeated_folds_df[
        ["repeat", "split_seed"]
    ]
    .drop_duplicates()
    .sort_values("repeat")
    .to_string(index=False)
)

print(
    "\nRepeated 10 x 5 split validation PASSED."
)

Repeated split file: /content/brain-tumour-mri-classification/repeated_cv/splits/repeated_stratified_5fold_assignments.csv
Rows: 56000
Repeats: 10
Folds per repeat: 5

Split seeds:
 repeat  split_seed
      1      202601
      2      202602
      3      202603
      4      202604
      5      202605
      6      202606
      7      202607
      8      202608
      9      202609
     10      202610

Repeated 10 x 5 split validation PASSED.

In [5]:
# ============================================================
# Step 5. REPEATED NESTED-CV RESNET50 FIXED-FEATURE
# HYBRID EXPERIMENT SETUP
#
# IMPORTANT:
#   - Uses the EXISTING ResNet50 feature cache created during
#     the original Hybrid experiment.
#   - ResNet50 features are NOT extracted again.
#   - Old cached five-fold assignments will NOT be used.
#   - The shared repeated 10 × 5 assignments loaded earlier
#     will control all new outer folds.
# ============================================================

import gc
import json
import os
import random
import time
from pathlib import Path

import numpy as np
import pandas as pd
import tensorflow as tf


# ------------------------------------------------------------
# Dataset
# ------------------------------------------------------------

DATA_DIR = (
    PROJECT_ROOT
    / "processed_data_cropped"
)

assert DATA_DIR.exists(), (
    "Dataset directory was not found:\n"
    f"{DATA_DIR}"
)


# ------------------------------------------------------------
# Persistent Google Drive storage
# ------------------------------------------------------------

DRIVE_ROOT = Path(
    "/content/drive/MyDrive/brain_tumour_colab"
)


assert DRIVE_ROOT.exists(), (
    "Google Drive experiment directory was not found:\n"
    f"{DRIVE_ROOT}"
)


# ------------------------------------------------------------
# EXISTING ResNet50 fixed-feature cache
#
# This file was produced by the original Hybrid experiment.
# It contains the already-extracted fixed ImageNet ResNet50
# features for all 5,600 Training images.
#
# DO NOT create another feature matrix for the repeated run.
# ------------------------------------------------------------

RESNET50_FEATURE_CACHE_PATH = (
    DRIVE_ROOT
    / "results"
    / "resnet50_fixed_features"
    / "training_resnet50_features.npz"
)


assert RESNET50_FEATURE_CACHE_PATH.exists(), (
    "Existing ResNet50 feature cache was not found:\n"
    f"{RESNET50_FEATURE_CACHE_PATH}\n\n"
    "Do not extract new features until this has been checked."
)


# ------------------------------------------------------------
# Persistent repeated-CV result directories
# ------------------------------------------------------------

REPEATED_RESNET50_SVM_DIR = (
    DRIVE_ROOT
    / "results"
    / "repeated_nested_cv"
    / "resnet50_svm"
)

REPEATED_RESNET50_SVM_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


REPEATED_RESNET50_RF_DIR = (
    DRIVE_ROOT
    / "results"
    / "repeated_nested_cv"
    / "resnet50_rf"
)

REPEATED_RESNET50_RF_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


# ------------------------------------------------------------
# Image / feature / class configuration
# ------------------------------------------------------------

IMAGE_HEIGHT = 224
IMAGE_WIDTH = 224
IMAGE_CHANNELS = 3

NUMBER_OF_CLASSES = 4

FEATURE_DIMENSION = 2048


CLASS_NAMES = [
    "glioma",
    "meningioma",
    "notumor",
    "pituitary",
]


CLASS_TO_INDEX = {
    class_name: index
    for index, class_name
    in enumerate(CLASS_NAMES)
}


INDEX_TO_CLASS = {
    index: class_name
    for class_name, index
    in CLASS_TO_INDEX.items()
}


# ------------------------------------------------------------
# Repeated nested-CV configuration
# ------------------------------------------------------------

NUMBER_OF_REPEATS = 10

NUMBER_OF_OUTER_FOLDS = 5

NUMBER_OF_INNER_FOLDS = 3


# ------------------------------------------------------------
# Deterministic inner-CV seed
# ------------------------------------------------------------

BASE_INNER_CV_SEED = 303000


def get_hybrid_inner_cv_seed(
    repeat_number,
    fold_number,
):
    return (
        BASE_INNER_CV_SEED
        + repeat_number * 100
        + fold_number
    )


# ------------------------------------------------------------
# Random Forest model/search seeds
# ------------------------------------------------------------

BASE_RF_MODEL_SEED = 404000

BASE_RF_SEARCH_SEED = 414000


def get_hybrid_rf_model_seed(
    repeat_number,
    fold_number,
):
    return (
        BASE_RF_MODEL_SEED
        + repeat_number * 100
        + fold_number
    )


def get_hybrid_rf_search_seed(
    repeat_number,
    fold_number,
):
    return (
        BASE_RF_SEARCH_SEED
        + repeat_number * 100
        + fold_number
    )


# ------------------------------------------------------------
# Reproducibility
# ------------------------------------------------------------

RANDOM_SEED = 42

os.environ[
    "PYTHONHASHSEED"
] = str(
    RANDOM_SEED
)

random.seed(
    RANDOM_SEED
)

np.random.seed(
    RANDOM_SEED
)

tf.keras.utils.set_random_seed(
    RANDOM_SEED
)


try:

    tf.config.experimental.enable_op_determinism()

    determinism_status = "enabled"

except Exception as error:

    determinism_status = (
        f"requested but unavailable: {error}"
    )


tf.keras.backend.set_floatx(
    "float32"
)


# ------------------------------------------------------------
# Safety checks
# ------------------------------------------------------------

assert len(
    repeated_folds_df
) == 56000


assert (
    repeated_folds_df[
        "repeat"
    ].nunique()
    == NUMBER_OF_REPEATS
)


assert (
    repeated_folds_df[
        "fold"
    ].nunique()
    == NUMBER_OF_OUTER_FOLDS
)


# ------------------------------------------------------------
# Display configuration
# ------------------------------------------------------------

print("=" * 70)

print(
    "REPEATED NESTED-CV RESNET50 FIXED-FEATURE SETUP"
)

print("=" * 70)


print(
    "Dataset:",
    DATA_DIR,
)


print(
    "\nExisting ResNet50 feature cache:",
    RESNET50_FEATURE_CACHE_PATH,
)


print(
    "Feature cache exists:",
    RESNET50_FEATURE_CACHE_PATH.exists(),
)


print(
    "\nResNet50 + SVM results:",
    REPEATED_RESNET50_SVM_DIR,
)


print(
    "ResNet50 + RF results:",
    REPEATED_RESNET50_RF_DIR,
)


print(
    "\nRepeats:",
    NUMBER_OF_REPEATS,
)


print(
    "Outer folds per repeat:",
    NUMBER_OF_OUTER_FOLDS,
)


print(
    "Total outer evaluations per classifier:",
    (
        NUMBER_OF_REPEATS
        * NUMBER_OF_OUTER_FOLDS
    ),
)


print(
    "Inner CV folds:",
    NUMBER_OF_INNER_FOLDS,
)


print(
    "\nExpected feature dimension:",
    FEATURE_DIMENSION,
)


print(
    "Feature extraction required:",
    False,
)


print(
    "\nRepeat 1 / Fold 1 inner-CV seed:",
    get_hybrid_inner_cv_seed(
        1,
        1,
    ),
)


print(
    "Repeat 1 / Fold 1 RF model seed:",
    get_hybrid_rf_model_seed(
        1,
        1,
    ),
)


print(
    "Repeat 1 / Fold 1 RF search seed:",
    get_hybrid_rf_search_seed(
        1,
        1,
    ),
)


print(
    "\nIMPORTANT:"
)

print(
    "The previously extracted ResNet50 feature cache "
    "will be reused."
)

print(
    "No ResNet50 feature extraction will be performed."
)

print(
    "Old cached five-fold assignments will be ignored."
)

print(
    "The shared repeated 10 × 5 assignments will be used."
)

print(
    "The Testing partition is not used."
)


print(
    "\nHybrid Step 5 repeated-CV setup PASSED."
)

======================================================================
REPEATED NESTED-CV RESNET50 FIXED-FEATURE SETUP
======================================================================
Dataset: /content/brain-tumour-mri-classification/processed_data_cropped

Existing ResNet50 feature cache: /content/drive/MyDrive/brain_tumour_colab/results/resnet50_fixed_features/training_resnet50_features.npz
Feature cache exists: True

ResNet50 + SVM results: /content/drive/MyDrive/brain_tumour_colab/results/repeated_nested_cv/resnet50_svm
ResNet50 + RF results: /content/drive/MyDrive/brain_tumour_colab/results/repeated_nested_cv/resnet50_rf

Repeats: 10
Outer folds per repeat: 5
Total outer evaluations per classifier: 50
Inner CV folds: 3

Expected feature dimension: 2048
Feature extraction required: False

Repeat 1 / Fold 1 inner-CV seed: 303101
Repeat 1 / Fold 1 RF model seed: 404101
Repeat 1 / Fold 1 RF search seed: 414101

IMPORTANT:
The previously extracted ResNet50 feature cache will be reused.
No ResNet50 feature extraction will be performed.
Old cached five-fold assignments will be ignored.
The shared repeated 10 × 5 assignments will be used.
The Testing partition is not used.

Hybrid Step 5 repeated-CV setup PASSED.

In [6]:
# ============================================================
# Step 6. LOAD AND VALIDATE THE EXISTING
# RESNET50 FIXED-FEATURE CACHE
#
# IMPORTANT:
#   - Features are loaded from the original Hybrid experiment.
#   - Features are NOT extracted again.
#   - The old cached five-fold assignments are ignored.
#   - Feature rows are aligned to a canonical 5,600-image
#     Training manifest derived from the shared repeated splits.
# ============================================================


# ------------------------------------------------------------
# 1. Load the existing feature archive
# ------------------------------------------------------------

feature_archive = np.load(
    RESNET50_FEATURE_CACHE_PATH,
    allow_pickle=True,
)


print(
    "Feature archive contents:",
    feature_archive.files,
)


# ------------------------------------------------------------
# 2. Required archive contents
# ------------------------------------------------------------

required_cache_arrays = {
    "features",
    "class_indices",
    "relative_paths",
}


missing_cache_arrays = (
    required_cache_arrays
    - set(
        feature_archive.files
    )
)


assert not missing_cache_arrays, (
    "Existing ResNet50 feature cache is missing "
    f"required arrays: {sorted(missing_cache_arrays)}"
)


# ------------------------------------------------------------
# 3. Load the cached arrays
#
# NOTE:
#   fold_assignments may also exist in the archive because
#   it was created during the original five-fold experiment.
#
#   Those old fold assignments are deliberately NOT loaded
#   for use in the repeated experiment.
# ------------------------------------------------------------

cached_resnet50_features = (
    feature_archive[
        "features"
    ]
)

cached_resnet50_class_indices = (
    feature_archive[
        "class_indices"
    ]
    .astype(
        np.int32
    )
)

cached_resnet50_relative_paths = (
    feature_archive[
        "relative_paths"
    ]
    .astype(str)
)


# ------------------------------------------------------------
# 4. Basic feature-cache validation
# ------------------------------------------------------------

assert cached_resnet50_features.shape == (
    5600,
    FEATURE_DIMENSION,
), (
    "Unexpected ResNet50 feature matrix shape: "
    f"{cached_resnet50_features.shape}"
)


assert cached_resnet50_features.dtype == np.float32, (
    "Expected float32 ResNet50 features, but found "
    f"{cached_resnet50_features.dtype}"
)


assert len(
    cached_resnet50_class_indices
) == 5600


assert len(
    cached_resnet50_relative_paths
) == 5600


assert (
    len(
        np.unique(
            cached_resnet50_relative_paths
        )
    )
    == 5600
), (
    "Duplicate image paths were found "
    "in the cached ResNet50 features."
)


assert np.isfinite(
    cached_resnet50_features
).all(), (
    "Non-finite values were found "
    "in the cached ResNet50 feature matrix."
)


assert set(
    np.unique(
        cached_resnet50_class_indices
    )
) == {
    0,
    1,
    2,
    3,
}, (
    "Unexpected class indices were found "
    "in the feature cache."
)


# ------------------------------------------------------------
# 5. Create the canonical Training manifest
#
# Every repeat contains the same 5,600 Training images.
# We use Repeat 1 only to obtain one canonical copy.
#
# Fold membership is NOT taken from Repeat 1 here.
# The 'fold' column is deliberately excluded.
# ------------------------------------------------------------

canonical_training_df = (
    repeated_folds_df[
        repeated_folds_df[
            "repeat"
        ]
        == 1
    ][
        [
            "relative_path",
            "class",
            "label",
        ]
    ]
    .copy()
    .sort_values(
        "relative_path"
    )
    .reset_index(
        drop=True
    )
)


assert len(
    canonical_training_df
) == 5600


assert (
    canonical_training_df[
        "relative_path"
    ]
    .nunique()
    == 5600
)


# ------------------------------------------------------------
# 6. Verify the cache contains exactly the same
#    5,600 Training images as the repeated experiment
# ------------------------------------------------------------

cached_path_set = set(
    cached_resnet50_relative_paths.tolist()
)


repeated_training_path_set = set(
    canonical_training_df[
        "relative_path"
    ]
    .astype(str)
    .tolist()
)


assert (
    cached_path_set
    == repeated_training_path_set
), (
    "The existing ResNet50 feature cache and the "
    "shared repeated-CV Training manifest do not "
    "contain exactly the same 5,600 images."
)


# ------------------------------------------------------------
# 7. Align cached feature rows to the canonical
#    Training manifest order
# ------------------------------------------------------------

path_to_cached_index = {
    path: index
    for index, path
    in enumerate(
        cached_resnet50_relative_paths
    )
}


ordered_cache_indices = np.array(
    [
        path_to_cached_index[
            path
        ]
        for path
        in canonical_training_df[
            "relative_path"
        ].astype(str)
    ],
    dtype=np.int64,
)


training_features = (
    cached_resnet50_features[
        ordered_cache_indices
    ]
)


training_class_indices = (
    cached_resnet50_class_indices[
        ordered_cache_indices
    ]
)


training_relative_paths = (
    cached_resnet50_relative_paths[
        ordered_cache_indices
    ]
)


# ------------------------------------------------------------
# 8. Validate labels after path-based alignment
# ------------------------------------------------------------

expected_class_indices = (
    canonical_training_df[
        "label"
    ]
    .to_numpy(
        dtype=np.int32
    )
)


assert np.array_equal(
    training_class_indices,
    expected_class_indices,
), (
    "Cached ResNet50 class indices do not match "
    "the repeated-CV Training manifest after "
    "path-based alignment."
)


assert np.array_equal(
    training_relative_paths,
    canonical_training_df[
        "relative_path"
    ]
    .astype(str)
    .to_numpy(),
), (
    "Cached ResNet50 feature rows are not aligned "
    "with the canonical Training manifest."
)


# ------------------------------------------------------------
# 9. Final feature-matrix validation
# ------------------------------------------------------------

assert training_features.shape == (
    5600,
    2048,
)


assert training_features.dtype == np.float32


assert len(
    training_class_indices
) == 5600


assert len(
    training_relative_paths
) == 5600


assert np.isfinite(
    training_features
).all()


# ------------------------------------------------------------
# 10. Class-distribution validation
# ------------------------------------------------------------

class_counts = (
    pd.Series(
        training_class_indices
    )
    .value_counts()
    .sort_index()
)


assert (
    class_counts
    == 1400
).all(), (
    "Expected exactly 1,400 Training images "
    "from each class."
)


# ------------------------------------------------------------
# 11. Display
# ------------------------------------------------------------

print("=" * 70)

print(
    "EXISTING RESNET50 FEATURE CACHE VALIDATION"
)

print("=" * 70)


print(
    "Loaded from:",
    RESNET50_FEATURE_CACHE_PATH,
)


print(
    "\nFeature matrix:",
    training_features.shape,
)


print(
    "Feature dtype:",
    training_features.dtype,
)


print(
    "Class indices:",
    training_class_indices.shape,
)


print(
    "Unique Training paths:",
    len(
        np.unique(
            training_relative_paths
        )
    ),
)


print(
    "All features finite:",
    np.isfinite(
        training_features
    ).all(),
)


print(
    "\nClass counts:"
)

for class_index, count in (
    class_counts.items()
):

    print(
        f"{INDEX_TO_CLASS[class_index]:12s}:",
        count,
    )


print(
    "\nIMPORTANT:"
)

print(
    "Existing ResNet50 features were LOADED."
)

print(
    "No ResNet50 feature extraction was performed."
)

print(
    "Old cached five-fold assignments were NOT used."
)

print(
    "Feature rows were aligned using image paths."
)

print(
    "Shared repeated 10 × 5 assignments remain authoritative."
)

print(
    "Testing images were not used."
)


print(
    "\nHybrid Step 6 feature-cache validation PASSED."
)

Feature archive contents: ['features', 'class_indices', 'fold_assignments', 'relative_paths']
======================================================================
EXISTING RESNET50 FEATURE CACHE VALIDATION
======================================================================
Loaded from: /content/drive/MyDrive/brain_tumour_colab/results/resnet50_fixed_features/training_resnet50_features.npz

Feature matrix: (5600, 2048)
Feature dtype: float32
Class indices: (5600,)
Unique Training paths: 5600
All features finite: True

Class counts:
glioma      : 1400
meningioma  : 1400
notumor     : 1400
pituitary   : 1400

IMPORTANT:
Existing ResNet50 features were LOADED.
No ResNet50 feature extraction was performed.
Old cached five-fold assignments were NOT used.
Feature rows were aligned using image paths.
Shared repeated 10 × 5 assignments remain authoritative.
Testing images were not used.

Hybrid Step 6 feature-cache validation PASSED.

In [7]:
# ============================================================
# Step 7. BUILD AND VALIDATE THE REPEATED OUTER PARTITIONS
# FOR RESNET50 FIXED FEATURES
#
# IMPORTANT:
#   - Uses the shared repeated 10 × 5 assignment file.
#   - Uses the already-loaded 5,600 × 2,048 feature matrix.
#   - Does NOT use the old cached five-fold assignments.
#   - Does NOT use the Testing partition.
# ============================================================


# ------------------------------------------------------------
# 1. Map every Training image path to its canonical
#    feature-matrix row
# ------------------------------------------------------------

path_to_feature_index = {
    path: index
    for index, path
    in enumerate(
        training_relative_paths
    )
}


assert len(
    path_to_feature_index
) == 5600


# ------------------------------------------------------------
# 2. Create repeated hybrid assignment table
# ------------------------------------------------------------

hybrid_repeated_assignments = (
    repeated_folds_df
    .copy()
)


hybrid_repeated_assignments[
    "feature_index"
] = (
    hybrid_repeated_assignments[
        "relative_path"
    ]
    .astype(str)
    .map(
        path_to_feature_index
    )
)


# ------------------------------------------------------------
# 3. Validate feature-row mapping
# ------------------------------------------------------------

assert (
    hybrid_repeated_assignments[
        "feature_index"
    ]
    .notna()
    .all()
), (
    "At least one repeated-CV image could not "
    "be matched to the cached ResNet50 features."
)


hybrid_repeated_assignments[
    "feature_index"
] = (
    hybrid_repeated_assignments[
        "feature_index"
    ]
    .astype(
        np.int64
    )
)


assert len(
    hybrid_repeated_assignments
) == 56000


# ------------------------------------------------------------
# 4. Define outer-partition function
# ------------------------------------------------------------

def make_hybrid_outer_partition(
    repeat_number,
    fold_number,
):
    """
    Return one repeated outer-training /
    outer-validation partition using the fixed
    ResNet50 feature matrix.

    Hyperparameter tuning will later be performed
    only on the returned outer-training partition.
    """

    assert (
        1
        <= repeat_number
        <= NUMBER_OF_REPEATS
    )

    assert (
        1
        <= fold_number
        <= NUMBER_OF_OUTER_FOLDS
    )


    # --------------------------------------------------------
    # Select one repeat
    # --------------------------------------------------------

    repeat_df = (
        hybrid_repeated_assignments[
            hybrid_repeated_assignments[
                "repeat"
            ]
            == repeat_number
        ]
        .copy()
    )


    assert len(
        repeat_df
    ) == 5600


    # --------------------------------------------------------
    # Identify outer training / validation rows
    # --------------------------------------------------------

    outer_training_df = (
        repeat_df[
            repeat_df[
                "fold"
            ]
            != fold_number
        ]
        .copy()
    )


    outer_validation_df = (
        repeat_df[
            repeat_df[
                "fold"
            ]
            == fold_number
        ]
        .copy()
    )


    # --------------------------------------------------------
    # Obtain feature-matrix indices
    # --------------------------------------------------------

    outer_training_indices = (
        outer_training_df[
            "feature_index"
        ]
        .to_numpy(
            dtype=np.int64
        )
    )


    outer_validation_indices = (
        outer_validation_df[
            "feature_index"
        ]
        .to_numpy(
            dtype=np.int64
        )
    )


    # --------------------------------------------------------
    # Obtain features
    # --------------------------------------------------------

    outer_training_features = (
        training_features[
            outer_training_indices
        ]
    )


    outer_validation_features = (
        training_features[
            outer_validation_indices
        ]
    )


    # --------------------------------------------------------
    # Obtain labels
    # --------------------------------------------------------

    outer_training_labels = (
        training_class_indices[
            outer_training_indices
        ]
    )


    outer_validation_labels = (
        training_class_indices[
            outer_validation_indices
        ]
    )


    # --------------------------------------------------------
    # Obtain paths
    # --------------------------------------------------------

    outer_training_paths = (
        training_relative_paths[
            outer_training_indices
        ]
    )


    outer_validation_paths = (
        training_relative_paths[
            outer_validation_indices
        ]
    )


    # --------------------------------------------------------
    # Validate sizes
    # --------------------------------------------------------

    assert outer_training_features.shape == (
        4480,
        FEATURE_DIMENSION,
    )


    assert outer_validation_features.shape == (
        1120,
        FEATURE_DIMENSION,
    )


    assert len(
        outer_training_labels
    ) == 4480


    assert len(
        outer_validation_labels
    ) == 1120


    # --------------------------------------------------------
    # Validate no overlap
    # --------------------------------------------------------

    assert set(
        outer_training_paths
    ).isdisjoint(
        set(
            outer_validation_paths
        )
    ), (
        "Outer Training and validation paths overlap."
    )


    assert (
        len(
            set(
                outer_training_paths
            )
        )
        == 4480
    )


    assert (
        len(
            set(
                outer_validation_paths
            )
        )
        == 1120
    )


    # --------------------------------------------------------
    # Validate class balance
    # --------------------------------------------------------

    outer_training_class_counts = (
        pd.Series(
            outer_training_labels
        )
        .value_counts()
        .sort_index()
    )


    outer_validation_class_counts = (
        pd.Series(
            outer_validation_labels
        )
        .value_counts()
        .sort_index()
    )


    assert (
        outer_training_class_counts
        == 1120
    ).all(), (
        "Each class must contain exactly "
        "1,120 outer-training images."
    )


    assert (
        outer_validation_class_counts
        == 280
    ).all(), (
        "Each class must contain exactly "
        "280 outer-validation images."
    )


    # --------------------------------------------------------
    # Return partition
    # --------------------------------------------------------

    return {
        "repeat": repeat_number,
        "fold": fold_number,

        "split_seed": int(
            outer_validation_df[
                "split_seed"
            ].iloc[0]
        ),

        "outer_training_features":
            outer_training_features,

        "outer_training_labels":
            outer_training_labels,

        "outer_training_paths":
            outer_training_paths,

        "outer_validation_features":
            outer_validation_features,

        "outer_validation_labels":
            outer_validation_labels,

        "outer_validation_paths":
            outer_validation_paths,
    }


# ------------------------------------------------------------
# 5. Test Repeat 1 / Fold 1
# ------------------------------------------------------------

hybrid_partition_test = (
    make_hybrid_outer_partition(
        repeat_number=1,
        fold_number=1,
    )
)


# ------------------------------------------------------------
# 6. Display validation
# ------------------------------------------------------------

print("=" * 70)

print(
    "RESNET50 FIXED-FEATURE REPEATED OUTER PARTITION"
)

print("=" * 70)


print(
    "Repeat:",
    hybrid_partition_test[
        "repeat"
    ],
)


print(
    "Fold:",
    hybrid_partition_test[
        "fold"
    ],
)


print(
    "Split seed:",
    hybrid_partition_test[
        "split_seed"
    ],
)


print(
    "\nOuter Training features:",
    hybrid_partition_test[
        "outer_training_features"
    ].shape,
)


print(
    "Outer validation features:",
    hybrid_partition_test[
        "outer_validation_features"
    ].shape,
)


print(
    "\nOuter Training class counts:"
)

print(
    pd.Series(
        hybrid_partition_test[
            "outer_training_labels"
        ]
    )
    .value_counts()
    .sort_index()
)


print(
    "\nOuter validation class counts:"
)

print(
    pd.Series(
        hybrid_partition_test[
            "outer_validation_labels"
        ]
    )
    .value_counts()
    .sort_index()
)


print(
    "\nIMPORTANT:"
)

print(
    "Old cached five-fold assignments were NOT used."
)

print(
    "Shared repeated 10 × 5 assignments were used."
)

print(
    "Testing images were not used."
)


print(
    "\nHybrid Step 7 repeated outer-partition "
    "validation PASSED."
)

======================================================================
RESNET50 FIXED-FEATURE REPEATED OUTER PARTITION
======================================================================
Repeat: 1
Fold: 1
Split seed: 202601

Outer Training features: (4480, 2048)
Outer validation features: (1120, 2048)

Outer Training class counts:
0    1120
1    1120
2    1120
3    1120
Name: count, dtype: int64

Outer validation class counts:
0    280
1    280
2    280
3    280
Name: count, dtype: int64

IMPORTANT:
Old cached five-fold assignments were NOT used.
Shared repeated 10 × 5 assignments were used.
Testing images were not used.

Hybrid Step 7 repeated outer-partition validation PASSED.

In [8]:
# ============================================================
# Step 8. DEFINE THE REPEATED NESTED-CV
# RESNET50 FIXED-FEATURE + SVM SEARCH
#
# IMPORTANT:
#   - StandardScaler remains INSIDE the sklearn pipeline.
#   - Hyperparameter selection uses only the 4,480
#     outer-training feature vectors.
#   - Every outer fold receives its own deterministic
#     shuffled 3-fold inner CV.
#   - Outer-validation data is not used for selection.
# ============================================================

from sklearn.model_selection import (
    GridSearchCV,
    StratifiedKFold,
)

from sklearn.pipeline import Pipeline

from sklearn.preprocessing import (
    StandardScaler,
)

from sklearn.svm import SVC


# ------------------------------------------------------------
# 1. SVM hyperparameter grid
#
# Same search used in the original Hybrid experiment:
#
#   C     = 5 values
#   gamma = 5 values
#
# Total = 25 candidate configurations
# ------------------------------------------------------------

SVM_PARAMETER_GRID = {
    "classifier__C": [
        0.01,
        0.1,
        1,
        10,
        100,
    ],

    "classifier__gamma": [
        "scale",
        1e-5,
        1e-4,
        1e-3,
        1e-2,
    ],
}


# ------------------------------------------------------------
# 2. Base SVM pipeline
#
# StandardScaler MUST stay inside the pipeline so that,
# during inner CV, it is fitted only on each inner-training
# subset and never on its corresponding inner-validation set.
# ------------------------------------------------------------

def build_hybrid_svm_pipeline():

    return Pipeline(
        steps=[
            (
                "scaler",
                StandardScaler(),
            ),

            (
                "classifier",
                SVC(
                    kernel="rbf",
                ),
            ),
        ]
    )


# ------------------------------------------------------------
# 3. Build one fold-specific inner search
#
# A fresh StratifiedKFold object is created for every
# repeat / outer-fold combination using the documented
# deterministic seed schedule.
# ------------------------------------------------------------

def build_hybrid_svm_search(
    repeat_number,
    fold_number,
):

    inner_cv_seed = (
        get_hybrid_inner_cv_seed(
            repeat_number,
            fold_number,
        )
    )


    inner_cross_validation = (
        StratifiedKFold(
            n_splits=NUMBER_OF_INNER_FOLDS,
            shuffle=True,
            random_state=inner_cv_seed,
        )
    )


    svm_search = GridSearchCV(
        estimator=build_hybrid_svm_pipeline(),

        param_grid=SVM_PARAMETER_GRID,

        scoring="f1_macro",

        cv=inner_cross_validation,

        n_jobs=-1,

        refit=True,

        return_train_score=False,
    )


    return svm_search


# ------------------------------------------------------------
# 4. Validate the complete search definition
# ------------------------------------------------------------

number_of_svm_configurations = (
    len(
        SVM_PARAMETER_GRID[
            "classifier__C"
        ]
    )
    *
    len(
        SVM_PARAMETER_GRID[
            "classifier__gamma"
        ]
    )
)


assert (
    number_of_svm_configurations
    == 25
)


test_svm_search = (
    build_hybrid_svm_search(
        repeat_number=1,
        fold_number=1,
    )
)


assert (
    test_svm_search.scoring
    == "f1_macro"
)


assert (
    test_svm_search.cv.n_splits
    == 3
)


assert (
    test_svm_search.cv.random_state
    == 303101
)


assert (
    test_svm_search.refit
    is True
)


# ------------------------------------------------------------
# 5. Display
# ------------------------------------------------------------

print("=" * 70)

print(
    "RESNET50 FIXED-FEATURE + SVM SEARCH"
)

print("=" * 70)


print(
    "SVM kernel:",
    "RBF",
)


print(
    "Feature standardisation:",
    "StandardScaler inside Pipeline",
)


print(
    "C values:",
    SVM_PARAMETER_GRID[
        "classifier__C"
    ],
)


print(
    "Gamma values:",
    SVM_PARAMETER_GRID[
        "classifier__gamma"
    ],
)


print(
    "Candidate configurations:",
    number_of_svm_configurations,
)


print(
    "Inner CV folds:",
    NUMBER_OF_INNER_FOLDS,
)


print(
    "Selection metric:",
    test_svm_search.scoring,
)


print(
    "\nRepeat 1 / Fold 1 inner-CV seed:",
    test_svm_search.cv.random_state,
)


print(
    "\nIMPORTANT:"
)

print(
    "A fresh SVM search will be created "
    "for every outer fold."
)

print(
    "Only outer-training features will be used "
    "for hyperparameter selection."
)

print(
    "Outer-validation features remain untouched "
    "until final fold evaluation."
)

print(
    "Testing images are not used."
)


print(
    "\nHybrid Step 8 SVM search definition PASSED."
)

======================================================================
RESNET50 FIXED-FEATURE + SVM SEARCH
======================================================================
SVM kernel: RBF
Feature standardisation: StandardScaler inside Pipeline
C values: [0.01, 0.1, 1, 10, 100]
Gamma values: ['scale', 1e-05, 0.0001, 0.001, 0.01]
Candidate configurations: 25
Inner CV folds: 3
Selection metric: f1_macro

Repeat 1 / Fold 1 inner-CV seed: 303101

IMPORTANT:
A fresh SVM search will be created for every outer fold.
Only outer-training features will be used for hyperparameter selection.
Outer-validation features remain untouched until final fold evaluation.
Testing images are not used.

Hybrid Step 8 SVM search definition PASSED.

In [9]:
# ============================================================
# Step 9. RESNET50 FIXED-FEATURE + SVM
# PERSISTENCE AND RESUME UTILITIES
#
# IMPORTANT:
#   - Every completed outer fold will be saved to Google Drive.
#   - Completed folds can be detected after a disconnect.
#   - Existing completed folds will later be skipped.
#   - Files are written atomically to reduce the risk of
#     partially written results.
# ============================================================

import json
import os
from pathlib import Path

import numpy as np
import pandas as pd


# ------------------------------------------------------------
# 1. Convert NumPy objects to ordinary Python objects
#    before writing JSON
# ------------------------------------------------------------

def make_json_serializable(value):

    if isinstance(
        value,
        np.integer,
    ):
        return int(
            value
        )

    if isinstance(
        value,
        np.floating,
    ):
        return float(
            value
        )

    if isinstance(
        value,
        np.ndarray,
    ):
        return value.tolist()

    if isinstance(
        value,
        Path,
    ):
        return str(
            value
        )

    raise TypeError(
        "Object of type "
        f"{type(value).__name__} "
        "is not JSON serializable."
    )


# ------------------------------------------------------------
# 2. Atomic JSON writer
# ------------------------------------------------------------

def save_json_atomic(
    data,
    output_path,
):

    output_path = Path(
        output_path
    )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )


    temporary_path = (
        output_path.with_suffix(
            output_path.suffix
            + ".tmp"
        )
    )


    with open(
        temporary_path,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            data,
            file,
            indent=2,
            default=make_json_serializable,
        )


    os.replace(
        temporary_path,
        output_path,
    )


# ------------------------------------------------------------
# 3. Atomic CSV writer
# ------------------------------------------------------------

def save_dataframe_atomic(
    dataframe,
    output_path,
):

    output_path = Path(
        output_path
    )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )


    temporary_path = (
        output_path.with_suffix(
            output_path.suffix
            + ".tmp"
        )
    )


    dataframe.to_csv(
        temporary_path,
        index=False,
    )


    os.replace(
        temporary_path,
        output_path,
    )


# ------------------------------------------------------------
# 4. Create the directory for one repeat / fold
# ------------------------------------------------------------

def get_resnet50_svm_fold_directory(
    repeat_number,
    fold_number,
):

    fold_directory = (
        REPEATED_RESNET50_SVM_DIR
        / f"repeat_{repeat_number:02d}"
        / f"fold_{fold_number:02d}"
    )


    return fold_directory


# ------------------------------------------------------------
# 5. Define the files required for a completed fold
# ------------------------------------------------------------

def get_resnet50_svm_fold_paths(
    repeat_number,
    fold_number,
):

    fold_directory = (
        get_resnet50_svm_fold_directory(
            repeat_number,
            fold_number,
        )
    )


    return {

        "directory":
            fold_directory,

        "search_results":
            (
                fold_directory
                / "inner_search_results.csv"
            ),

        "selected_parameters":
            (
                fold_directory
                / "selected_parameters.json"
            ),

        "outer_predictions":
            (
                fold_directory
                / "outer_predictions.csv"
            ),

        "outer_metrics":
            (
                fold_directory
                / "outer_metrics.json"
            ),

        "completion_marker":
            (
                fold_directory
                / "COMPLETED.json"
            ),
    }


# ------------------------------------------------------------
# 6. Determine whether one fold is already complete
#
# The completion marker is written LAST.
# Therefore its existence indicates that all required
# results were successfully saved.
# ------------------------------------------------------------

def is_resnet50_svm_fold_complete(
    repeat_number,
    fold_number,
):

    fold_paths = (
        get_resnet50_svm_fold_paths(
            repeat_number,
            fold_number,
        )
    )


    required_files = [

        fold_paths[
            "search_results"
        ],

        fold_paths[
            "selected_parameters"
        ],

        fold_paths[
            "outer_predictions"
        ],

        fold_paths[
            "outer_metrics"
        ],

        fold_paths[
            "completion_marker"
        ],
    ]


    return all(
        file_path.exists()
        for file_path
        in required_files
    )


# ------------------------------------------------------------
# 7. Validate directory structure using Repeat 1 / Fold 1
#
# This does NOT train anything.
# ------------------------------------------------------------

test_svm_fold_paths = (
    get_resnet50_svm_fold_paths(
        repeat_number=1,
        fold_number=1,
    )
)


assert (
    test_svm_fold_paths[
        "directory"
    ]
    ==
    (
        REPEATED_RESNET50_SVM_DIR
        / "repeat_01"
        / "fold_01"
    )
)


# ------------------------------------------------------------
# 8. Display
# ------------------------------------------------------------

print("=" * 70)

print(
    "RESNET50 FIXED-FEATURE + SVM "
    "PERSISTENCE / RESUME SETUP"
)

print("=" * 70)


print(
    "Results root:",
    REPEATED_RESNET50_SVM_DIR,
)


print(
    "\nExample fold directory:"
)

print(
    test_svm_fold_paths[
        "directory"
    ]
)


print(
    "\nFiles saved for every completed fold:"
)

print(
    " - inner_search_results.csv"
)

print(
    " - selected_parameters.json"
)

print(
    " - outer_predictions.csv"
)

print(
    " - outer_metrics.json"
)

print(
    " - COMPLETED.json"
)


print(
    "\nRepeat 1 / Fold 1 currently complete:",
    is_resnet50_svm_fold_complete(
        1,
        1,
    ),
)


print(
    "\nIMPORTANT:"
)

print(
    "The completion marker will be written only "
    "after all fold outputs are saved."
)

print(
    "After a Colab disconnect, completed folds "
    "can therefore be skipped safely."
)


print(
    "\nHybrid Step 9 SVM persistence / resume "
    "setup PASSED."
)

======================================================================
RESNET50 FIXED-FEATURE + SVM PERSISTENCE / RESUME SETUP
======================================================================
Results root: /content/drive/MyDrive/brain_tumour_colab/results/repeated_nested_cv/resnet50_svm

Example fold directory:
/content/drive/MyDrive/brain_tumour_colab/results/repeated_nested_cv/resnet50_svm/repeat_01/fold_01

Files saved for every completed fold:
 - inner_search_results.csv
 - selected_parameters.json
 - outer_predictions.csv
 - outer_metrics.json
 - COMPLETED.json

Repeat 1 / Fold 1 currently complete: True

IMPORTANT:
The completion marker will be written only after all fold outputs are saved.
After a Colab disconnect, completed folds can therefore be skipped safely.

Hybrid Step 9 SVM persistence / resume setup PASSED.

In [ ]:
# ============================================================
# Step 11. RUN ALL 10 × 5 REPEATED NESTED-CV
# RESNET50 FIXED-FEATURE + SVM FOLDS
#
# Total:
#   10 repeats × 5 outer folds = 50 outer evaluations
#
# Resume behaviour:
#   - completed + valid fold -> SKIP
#   - incomplete / corrupt fold -> DELETE and RERUN
#   - save immediately after every completed fold
#
# IMPORTANT:
#   - ResNet50 features are NOT extracted again.
#   - The existing 5,600 × 2,048 feature cache is reused.
#   - Hyperparameter selection occurs only inside the
#     4,480-sample outer-training partition.
#   - The 1,120 outer-validation samples are evaluated once.
#   - Testing data is never used.
# ============================================================

import gc
import json
import shutil
import time

from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)


# ------------------------------------------------------------
# 1. Validate an already-completed fold
#
# A fold is skipped only if:
#   - every required file exists
#   - completion marker says completed
#   - repeat/fold identifiers are correct
#   - 25 SVM search configurations were saved
#   - 1,120 outer predictions were saved
# ------------------------------------------------------------

def validate_completed_resnet50_svm_fold(
    repeat_number,
    fold_number,
):

    fold_paths = (
        get_resnet50_svm_fold_paths(
            repeat_number,
            fold_number,
        )
    )


    required_paths = [
        fold_paths["search_results"],
        fold_paths["selected_parameters"],
        fold_paths["outer_predictions"],
        fold_paths["outer_metrics"],
        fold_paths["completion_marker"],
    ]


    if not all(
        path.exists()
        for path in required_paths
    ):
        return False


    try:

        # ----------------------------------------------------
        # Read completion marker
        # ----------------------------------------------------

        with open(
            fold_paths[
                "completion_marker"
            ],
            "r",
            encoding="utf-8",
        ) as file:

            completion = (
                json.load(
                    file
                )
            )


        if (
            completion.get(
                "status"
            )
            != "completed"
        ):
            return False


        if (
            int(
                completion.get(
                    "repeat"
                )
            )
            != repeat_number
        ):
            return False


        if (
            int(
                completion.get(
                    "fold"
                )
            )
            != fold_number
        ):
            return False


        # ----------------------------------------------------
        # Read metrics
        # ----------------------------------------------------

        with open(
            fold_paths[
                "outer_metrics"
            ],
            "r",
            encoding="utf-8",
        ) as file:

            metrics = (
                json.load(
                    file
                )
            )


        if (
            int(
                metrics[
                    "repeat"
                ]
            )
            != repeat_number
        ):
            return False


        if (
            int(
                metrics[
                    "fold"
                ]
            )
            != fold_number
        ):
            return False


        if (
            int(
                metrics[
                    "outer_training_samples"
                ]
            )
            != 4480
        ):
            return False


        if (
            int(
                metrics[
                    "outer_validation_samples"
                ]
            )
            != 1120
        ):
            return False


        # ----------------------------------------------------
        # Read saved predictions
        # ----------------------------------------------------

        saved_predictions = (
            pd.read_csv(
                fold_paths[
                    "outer_predictions"
                ]
            )
        )


        if (
            len(
                saved_predictions
            )
            != 1120
        ):
            return False


        # ----------------------------------------------------
        # Read saved search results
        # ----------------------------------------------------

        saved_search_results = (
            pd.read_csv(
                fold_paths[
                    "search_results"
                ]
            )
        )


        if (
            len(
                saved_search_results
            )
            != 25
        ):
            return False


        # ----------------------------------------------------
        # Read selected parameters
        # ----------------------------------------------------

        with open(
            fold_paths[
                "selected_parameters"
            ],
            "r",
            encoding="utf-8",
        ) as file:

            selected_parameters = (
                json.load(
                    file
                )
            )


        if (
            int(
                selected_parameters[
                    "repeat"
                ]
            )
            != repeat_number
        ):
            return False


        if (
            int(
                selected_parameters[
                    "fold"
                ]
            )
            != fold_number
        ):
            return False


        return True


    except Exception:

        return False


# ------------------------------------------------------------
# 2. Counters
# ------------------------------------------------------------

completed_folds = 0

skipped_folds = 0

rerun_folds = 0


full_run_start_time = (
    time.perf_counter()
)


# ------------------------------------------------------------
# 3. Run all 10 repeats × 5 outer folds
# ------------------------------------------------------------

for repeat_number in range(
    1,
    NUMBER_OF_REPEATS + 1,
):

    print(
        "\n"
        + "=" * 72
    )

    print(
        f"REPEAT {repeat_number} / "
        f"{NUMBER_OF_REPEATS}"
    )

    print(
        "=" * 72
    )


    for fold_number in range(
        1,
        NUMBER_OF_OUTER_FOLDS + 1,
    ):

        print(
            "\n"
            + "-" * 72
        )

        print(
            f"Repeat {repeat_number} / "
            f"Fold {fold_number}"
        )

        print(
            "-" * 72
        )


        # ----------------------------------------------------
        # Persistent fold paths
        # ----------------------------------------------------

        fold_paths = (
            get_resnet50_svm_fold_paths(
                repeat_number,
                fold_number,
            )
        )


        fold_directory = (
            fold_paths[
                "directory"
            ]
        )


        # ----------------------------------------------------
        # Skip already-completed valid folds
        # ----------------------------------------------------

        if (
            validate_completed_resnet50_svm_fold(
                repeat_number,
                fold_number,
            )
        ):

            print(
                "Status: already completed "
                "and validated."
            )

            print(
                "Action: SKIPPING."
            )


            skipped_folds += 1

            continue


        # ----------------------------------------------------
        # Delete an incomplete/corrupt previous attempt
        # ----------------------------------------------------

        if fold_directory.exists():

            print(
                "Existing fold directory is incomplete "
                "or invalid."
            )

            print(
                "Deleting incomplete fold before rerun..."
            )


            shutil.rmtree(
                fold_directory
            )


            rerun_folds += 1


        fold_directory.mkdir(
            parents=True,
            exist_ok=True,
        )


        # ----------------------------------------------------
        # Obtain the correct shared outer partition
        # ----------------------------------------------------

        partition = (
            make_hybrid_outer_partition(
                repeat_number=
                    repeat_number,

                fold_number=
                    fold_number,
            )
        )


        X_outer_train = (
            partition[
                "outer_training_features"
            ]
        )


        y_outer_train = (
            partition[
                "outer_training_labels"
            ]
        )


        X_outer_validation = (
            partition[
                "outer_validation_features"
            ]
        )


        y_outer_validation = (
            partition[
                "outer_validation_labels"
            ]
        )


        outer_validation_paths = (
            partition[
                "outer_validation_paths"
            ]
        )


        assert X_outer_train.shape == (
            4480,
            FEATURE_DIMENSION,
        )


        assert X_outer_validation.shape == (
            1120,
            FEATURE_DIMENSION,
        )


        # ----------------------------------------------------
        # Fold-specific deterministic inner-CV seed
        # ----------------------------------------------------

        inner_cv_seed = (
            get_hybrid_inner_cv_seed(
                repeat_number,
                fold_number,
            )
        )


        # ----------------------------------------------------
        # Fresh SVM hyperparameter search
        # ----------------------------------------------------

        svm_search = (
            build_hybrid_svm_search(
                repeat_number,
                fold_number,
            )
        )


        print(
            "Split seed:",
            partition[
                "split_seed"
            ],
        )


        print(
            "Inner-CV seed:",
            inner_cv_seed,
        )


        print(
            "Outer Training:",
            X_outer_train.shape,
        )


        print(
            "Outer validation:",
            X_outer_validation.shape,
        )


        print(
            "SVM candidates:",
            25,
        )


        print(
            "\nStarting inner 3-fold "
            "hyperparameter search..."
        )


        fold_start_time = (
            time.perf_counter()
        )


        # ----------------------------------------------------
        # NESTED MODEL SELECTION
        #
        # Only outer-training data enters GridSearchCV.
        #
        # GridSearchCV(refit=True) automatically refits
        # the winning StandardScaler + SVM pipeline using
        # all 4,480 outer-training samples.
        # ----------------------------------------------------

        svm_search.fit(
            X_outer_train,
            y_outer_train,
        )


        search_elapsed_seconds = (
            time.perf_counter()
            - fold_start_time
        )


        # ----------------------------------------------------
        # Validate completed inner search
        # ----------------------------------------------------

        assert hasattr(
            svm_search,
            "best_estimator_",
        )


        assert hasattr(
            svm_search,
            "best_params_",
        )


        assert (
            len(
                svm_search.cv_results_[
                    "params"
                ]
            )
            == 25
        )


        best_inner_macro_f1 = float(
            svm_search.best_score_
        )


        # ----------------------------------------------------
        # OUTER EVALUATION
        #
        # Outer-validation data is used only here.
        # ----------------------------------------------------

        outer_predictions = (
            svm_search.predict(
                X_outer_validation
            )
        )


        assert (
            len(
                outer_predictions
            )
            == 1120
        )


        # ----------------------------------------------------
        # Metrics
        # ----------------------------------------------------

        outer_accuracy = float(
            accuracy_score(
                y_outer_validation,
                outer_predictions,
            )
        )


        outer_balanced_accuracy = float(
            balanced_accuracy_score(
                y_outer_validation,
                outer_predictions,
            )
        )


        outer_macro_f1 = float(
            f1_score(
                y_outer_validation,
                outer_predictions,
                average="macro",
            )
        )


        outer_macro_precision = float(
            precision_score(
                y_outer_validation,
                outer_predictions,
                average="macro",
                zero_division=0,
            )
        )


        outer_macro_recall = float(
            recall_score(
                y_outer_validation,
                outer_predictions,
                average="macro",
                zero_division=0,
            )
        )


        outer_confusion_matrix = (
            confusion_matrix(
                y_outer_validation,
                outer_predictions,
                labels=[
                    0,
                    1,
                    2,
                    3,
                ],
            )
        )


        outer_classification_report = (
            classification_report(
                y_outer_validation,
                outer_predictions,
                labels=[
                    0,
                    1,
                    2,
                    3,
                ],
                target_names=
                    CLASS_NAMES,
                output_dict=True,
                zero_division=0,
            )
        )


        # ----------------------------------------------------
        # Save complete inner-search results
        # ----------------------------------------------------

        search_results_df = (
            pd.DataFrame(
                svm_search.cv_results_
            )
        )


        assert (
            len(
                search_results_df
            )
            == 25
        )


        # ----------------------------------------------------
        # Outer-validation prediction table
        # ----------------------------------------------------

        predictions_df = pd.DataFrame(
            {
                "relative_path":
                    outer_validation_paths,

                "true_label":
                    y_outer_validation,

                "predicted_label":
                    outer_predictions,
            }
        )


        predictions_df[
            "true_class"
        ] = (
            predictions_df[
                "true_label"
            ]
            .map(
                INDEX_TO_CLASS
            )
        )


        predictions_df[
            "predicted_class"
        ] = (
            predictions_df[
                "predicted_label"
            ]
            .map(
                INDEX_TO_CLASS
            )
        )


        assert (
            len(
                predictions_df
            )
            == 1120
        )


        # ----------------------------------------------------
        # Selected hyperparameter record
        # ----------------------------------------------------

        selected_parameters = {

            "model":
                "ResNet50_fixed_features_SVM",

            "repeat":
                int(
                    repeat_number
                ),

            "fold":
                int(
                    fold_number
                ),

            "outer_split_seed":
                int(
                    partition[
                        "split_seed"
                    ]
                ),

            "inner_cv_seed":
                int(
                    inner_cv_seed
                ),

            "inner_cv_folds":
                int(
                    NUMBER_OF_INNER_FOLDS
                ),

            "selection_metric":
                "f1_macro",

            "number_of_candidates":
                25,

            "best_inner_macro_f1":
                float(
                    best_inner_macro_f1
                ),

            "best_parameters":
                svm_search.best_params_,
        }


        # ----------------------------------------------------
        # Outer-fold metric record
        # ----------------------------------------------------

        outer_metrics = {

            "model":
                "ResNet50_fixed_features_SVM",

            "repeat":
                int(
                    repeat_number
                ),

            "fold":
                int(
                    fold_number
                ),

            "outer_split_seed":
                int(
                    partition[
                        "split_seed"
                    ]
                ),

            "inner_cv_seed":
                int(
                    inner_cv_seed
                ),

            "outer_training_samples":
                4480,

            "outer_validation_samples":
                1120,

            "best_inner_macro_f1":
                float(
                    best_inner_macro_f1
                ),

            "accuracy":
                float(
                    outer_accuracy
                ),

            "balanced_accuracy":
                float(
                    outer_balanced_accuracy
                ),

            "macro_f1":
                float(
                    outer_macro_f1
                ),

            "macro_precision":
                float(
                    outer_macro_precision
                ),

            "macro_recall":
                float(
                    outer_macro_recall
                ),

            "confusion_matrix":
                outer_confusion_matrix.tolist(),

            "classification_report":
                outer_classification_report,

            "elapsed_seconds":
                float(
                    search_elapsed_seconds
                ),
        }


        # ----------------------------------------------------
        # Save substantive files FIRST
        # ----------------------------------------------------

        save_dataframe_atomic(
            search_results_df,
            fold_paths[
                "search_results"
            ],
        )


        save_json_atomic(
            selected_parameters,
            fold_paths[
                "selected_parameters"
            ],
        )


        save_dataframe_atomic(
            predictions_df,
            fold_paths[
                "outer_predictions"
            ],
        )


        save_json_atomic(
            outer_metrics,
            fold_paths[
                "outer_metrics"
            ],
        )


        # ----------------------------------------------------
        # Read saved outputs back before declaring completion
        # ----------------------------------------------------

        saved_search_results = (
            pd.read_csv(
                fold_paths[
                    "search_results"
                ]
            )
        )


        saved_predictions = (
            pd.read_csv(
                fold_paths[
                    "outer_predictions"
                ]
            )
        )


        with open(
            fold_paths[
                "outer_metrics"
            ],
            "r",
            encoding="utf-8",
        ) as file:

            saved_metrics = (
                json.load(
                    file
                )
            )


        assert (
            len(
                saved_search_results
            )
            == 25
        )


        assert (
            len(
                saved_predictions
            )
            == 1120
        )


        assert (
            int(
                saved_metrics[
                    "repeat"
                ]
            )
            == repeat_number
        )


        assert (
            int(
                saved_metrics[
                    "fold"
                ]
            )
            == fold_number
        )


        # ----------------------------------------------------
        # Completion marker MUST be written LAST
        # ----------------------------------------------------

        completion_information = {

            "status":
                "completed",

            "model":
                "ResNet50_fixed_features_SVM",

            "repeat":
                int(
                    repeat_number
                ),

            "fold":
                int(
                    fold_number
                ),

            "required_outputs_verified":
                True,
        }


        save_json_atomic(
            completion_information,
            fold_paths[
                "completion_marker"
            ],
        )


        # ----------------------------------------------------
        # Final saved-fold validation
        # ----------------------------------------------------

        assert (
            validate_completed_resnet50_svm_fold(
                repeat_number,
                fold_number,
            )
        ), (
            "Saved fold failed final "
            "completion validation."
        )


        completed_folds += 1


        # ----------------------------------------------------
        # Fold status
        # ----------------------------------------------------

        print(
            "\nBest parameters:",
            svm_search.best_params_,
        )


        print(
            "Best inner macro F1:",
            round(
                best_inner_macro_f1,
                6,
            ),
        )


        print(
            "Outer accuracy:",
            round(
                outer_accuracy,
                6,
            ),
        )


        print(
            "Outer balanced accuracy:",
            round(
                outer_balanced_accuracy,
                6,
            ),
        )


        print(
            "Outer macro F1:",
            round(
                outer_macro_f1,
                6,
            ),
        )


        print(
            "Elapsed seconds:",
            round(
                search_elapsed_seconds,
                2,
            ),
        )


        print(
            "Status: SAVED AND VERIFIED."
        )


        # ----------------------------------------------------
        # Release fold-specific objects
        # ----------------------------------------------------

        del svm_search
        del partition

        del X_outer_train
        del y_outer_train

        del X_outer_validation
        del y_outer_validation

        del outer_predictions

        gc.collect()


    # --------------------------------------------------------
    # Repeat completion status
    # --------------------------------------------------------

    completed_in_repeat = sum(

        validate_completed_resnet50_svm_fold(
            repeat_number,
            fold_number,
        )

        for fold_number
        in range(
            1,
            NUMBER_OF_OUTER_FOLDS + 1,
        )
    )


    print(
        "\n"
        f"Repeat {repeat_number} status: "
        f"{completed_in_repeat}/5 folds complete."
    )


# ------------------------------------------------------------
# 4. Final experiment validation
# ------------------------------------------------------------

total_valid_completed_folds = sum(

    validate_completed_resnet50_svm_fold(
        repeat_number,
        fold_number,
    )

    for repeat_number
    in range(
        1,
        NUMBER_OF_REPEATS + 1,
    )

    for fold_number
    in range(
        1,
        NUMBER_OF_OUTER_FOLDS + 1,
    )
)


full_run_elapsed_seconds = (
    time.perf_counter()
    - full_run_start_time
)


# ------------------------------------------------------------
# 5. Final status
# ------------------------------------------------------------

print(
    "\n"
    + "=" * 72
)

print(
    "RESNET50 FIXED-FEATURE + SVM "
    "REPEATED NESTED-CV RUN FINISHED"
)

print(
    "=" * 72
)


print(
    "Valid completed folds:",
    total_valid_completed_folds,
    "/ 50",
)


print(
    "New folds completed this run:",
    completed_folds,
)


print(
    "Previously completed folds skipped:",
    skipped_folds,
)


print(
    "Incomplete/corrupt folds rerun:",
    rerun_folds,
)


print(
    "Total runtime this session (seconds):",
    round(
        full_run_elapsed_seconds,
        2,
    ),
)


print(
    "\nResults root:"
)

print(
    REPEATED_RESNET50_SVM_DIR
)


if (
    total_valid_completed_folds
    == 50
):

    print(
        "\nALL 50 RESNET50 + SVM "
        "OUTER FOLDS COMPLETED AND VERIFIED."
    )

else:

    print(
        "\nExperiment is not yet complete."
    )

    print(
        "Rerun this same cell after reconnecting."
    )

    print(
        "Valid completed folds will be skipped."
    )


print(
    "\nTesting partition was not used."
)

========================================================================
REPEAT 1 / 10
========================================================================

------------------------------------------------------------------------
Repeat 1 / Fold 1
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 1 / Fold 2
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 1 / Fold 3
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 1 / Fold 4
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 1 / Fold 5
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

Repeat 1 status: 5/5 folds complete.

========================================================================
REPEAT 2 / 10
========================================================================

------------------------------------------------------------------------
Repeat 2 / Fold 1
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 2 / Fold 2
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 2 / Fold 3
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 2 / Fold 4
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 2 / Fold 5
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

Repeat 2 status: 5/5 folds complete.

========================================================================
REPEAT 3 / 10
========================================================================

------------------------------------------------------------------------
Repeat 3 / Fold 1
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 3 / Fold 2
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 3 / Fold 3
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 3 / Fold 4
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 3 / Fold 5
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

Repeat 3 status: 5/5 folds complete.

========================================================================
REPEAT 4 / 10
========================================================================

------------------------------------------------------------------------
Repeat 4 / Fold 1
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 4 / Fold 2
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 4 / Fold 3
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 4 / Fold 4
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 4 / Fold 5
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

Repeat 4 status: 5/5 folds complete.

========================================================================
REPEAT 5 / 10
========================================================================

------------------------------------------------------------------------
Repeat 5 / Fold 1
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 5 / Fold 2
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 5 / Fold 3
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 5 / Fold 4
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 5 / Fold 5
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

Repeat 5 status: 5/5 folds complete.

========================================================================
REPEAT 6 / 10
========================================================================

------------------------------------------------------------------------
Repeat 6 / Fold 1
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 6 / Fold 2
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 6 / Fold 3
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 6 / Fold 4
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 6 / Fold 5
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

Repeat 6 status: 5/5 folds complete.

========================================================================
REPEAT 7 / 10
========================================================================

------------------------------------------------------------------------
Repeat 7 / Fold 1
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 7 / Fold 2
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 7 / Fold 3
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 7 / Fold 4
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 7 / Fold 5
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

Repeat 7 status: 5/5 folds complete.

========================================================================
REPEAT 8 / 10
========================================================================

------------------------------------------------------------------------
Repeat 8 / Fold 1
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 8 / Fold 2
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 8 / Fold 3
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 8 / Fold 4
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 8 / Fold 5
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

Repeat 8 status: 5/5 folds complete.

========================================================================
REPEAT 9 / 10
========================================================================

------------------------------------------------------------------------
Repeat 9 / Fold 1
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 9 / Fold 2
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 9 / Fold 3
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 9 / Fold 4
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 9 / Fold 5
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

Repeat 9 status: 5/5 folds complete.

========================================================================
REPEAT 10 / 10
========================================================================

------------------------------------------------------------------------
Repeat 10 / Fold 1
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 10 / Fold 2
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 10 / Fold 3
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 10 / Fold 4
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

------------------------------------------------------------------------
Repeat 10 / Fold 5
------------------------------------------------------------------------
Status: already completed and validated.
Action: SKIPPING.

Repeat 10 status: 5/5 folds complete.

========================================================================
RESNET50 FIXED-FEATURE + SVM REPEATED NESTED-CV RUN FINISHED
========================================================================
Valid completed folds: 50 / 50
New folds completed this run: 0
Previously completed folds skipped: 50
Incomplete/corrupt folds rerun: 0
Total runtime this session (seconds): 71.65

Results root:
/content/drive/MyDrive/brain_tumour_colab/results/repeated_nested_cv/resnet50_svm

ALL 50 RESNET50 + SVM OUTER FOLDS COMPLETED AND VERIFIED.

Testing partition was not used.

In [ ]:
# ============================================================
# ACCESS AND AGGREGATE RESNET50 FIXED-FEATURE + SVM RESULTS
#
# Reads the exact files produced by the repeated Hybrid 1
# SVM experiment.
#
# Expected structure:
#
# repeated_nested_cv/resnet50_svm/
#     repeat_01/
#         fold_01/
#             inner_search_results.csv
#             selected_parameters.json
#             outer_predictions.csv
#             outer_metrics.json
#             COMPLETED.json
#
# Produces:
#     all_fold_results.csv
#     repeat_level_summary.csv
# ============================================================

import json
from pathlib import Path

import numpy as np
import pandas as pd


# ------------------------------------------------------------
# 1. Results root
# ------------------------------------------------------------

RESULTS_ROOT = Path(
    "/content/drive/MyDrive/brain_tumour_colab/"
    "results/repeated_nested_cv/resnet50_svm"
)


assert RESULTS_ROOT.exists(), (
    "Results directory does not exist:\n"
    f"{RESULTS_ROOT}"
)


# ------------------------------------------------------------
# 2. Required files for every completed fold
# ------------------------------------------------------------

REQUIRED_FILES = [
    "inner_search_results.csv",
    "selected_parameters.json",
    "outer_predictions.csv",
    "outer_metrics.json",
    "COMPLETED.json",
]


# ------------------------------------------------------------
# 3. Scan all 50 fold directories
# ------------------------------------------------------------

fold_records = []

problem_folds = []


for repeat_number in range(1, 11):

    for fold_number in range(1, 6):

        fold_directory = (
            RESULTS_ROOT
            / f"repeat_{repeat_number:02d}"
            / f"fold_{fold_number:02d}"
        )


        # ----------------------------------------------------
        # Check folder
        # ----------------------------------------------------

        if not fold_directory.exists():

            problem_folds.append(
                {
                    "repeat": repeat_number,
                    "fold": fold_number,
                    "problem": "folder missing",
                    "path": str(fold_directory),
                }
            )

            continue


        # ----------------------------------------------------
        # Check required files
        # ----------------------------------------------------

        missing_files = [
            filename
            for filename
            in REQUIRED_FILES
            if not (
                fold_directory
                / filename
            ).exists()
        ]


        if missing_files:

            problem_folds.append(
                {
                    "repeat": repeat_number,
                    "fold": fold_number,
                    "problem":
                        "missing required files: "
                        + ", ".join(missing_files),
                    "path": str(fold_directory),
                }
            )

            continue


        # ----------------------------------------------------
        # Load completion marker
        # ----------------------------------------------------

        with open(
            fold_directory
            / "COMPLETED.json",
            "r",
            encoding="utf-8",
        ) as file:

            completion = json.load(
                file
            )


        if completion.get(
            "status"
        ) != "completed":

            problem_folds.append(
                {
                    "repeat": repeat_number,
                    "fold": fold_number,
                    "problem":
                        "completion marker does not "
                        "say completed",
                    "path": str(fold_directory),
                }
            )

            continue


        # ----------------------------------------------------
        # Load outer metrics
        # ----------------------------------------------------

        with open(
            fold_directory
            / "outer_metrics.json",
            "r",
            encoding="utf-8",
        ) as file:

            metrics = json.load(
                file
            )


        # ----------------------------------------------------
        # Load selected parameters
        # ----------------------------------------------------

        with open(
            fold_directory
            / "selected_parameters.json",
            "r",
            encoding="utf-8",
        ) as file:

            selected = json.load(
                file
            )


        best_parameters = (
            selected.get(
                "best_parameters",
                {},
            )
        )


        # ----------------------------------------------------
        # Build one fold-level record
        # ----------------------------------------------------

        fold_records.append(
            {
                "model":
                    metrics.get(
                        "model"
                    ),

                "repeat":
                    int(
                        metrics[
                            "repeat"
                        ]
                    ),

                "fold":
                    int(
                        metrics[
                            "fold"
                        ]
                    ),

                "outer_split_seed":
                    metrics.get(
                        "outer_split_seed"
                    ),

                "inner_cv_seed":
                    selected.get(
                        "inner_cv_seed"
                    ),

                "outer_training_samples":
                    metrics.get(
                        "outer_training_samples"
                    ),

                "outer_validation_samples":
                    metrics.get(
                        "outer_validation_samples"
                    ),

                "best_C":
                    best_parameters.get(
                        "classifier__C"
                    ),

                "best_gamma":
                    best_parameters.get(
                        "classifier__gamma"
                    ),

                "best_inner_macro_f1":
                    metrics.get(
                        "best_inner_macro_f1"
                    ),

                "accuracy":
                    metrics.get(
                        "accuracy"
                    ),

                "balanced_accuracy":
                    metrics.get(
                        "balanced_accuracy"
                    ),

                "macro_precision":
                    metrics.get(
                        "macro_precision"
                    ),

                "macro_recall":
                    metrics.get(
                        "macro_recall"
                    ),

                "macro_f1":
                    metrics.get(
                        "macro_f1"
                    ),

                "elapsed_seconds":
                    metrics.get(
                        "elapsed_seconds"
                    ),

                "fold_directory":
                    str(
                        fold_directory
                    ),
            }
        )


# ------------------------------------------------------------
# 4. Create fold-level table
# ------------------------------------------------------------

fold_results_df = pd.DataFrame(
    fold_records
)


if not fold_results_df.empty:

    fold_results_df = (
        fold_results_df
        .sort_values(
            [
                "repeat",
                "fold",
            ]
        )
        .reset_index(
            drop=True
        )
    )


# ------------------------------------------------------------
# 5. Display scan result
# ------------------------------------------------------------

print("=" * 72)

print(
    "RESNET50 + SVM SAVED RESULT CHECK"
)

print("=" * 72)


print(
    "Results root:",
    RESULTS_ROOT,
)


print(
    "\nValid fold results found:",
    len(
        fold_results_df
    ),
    "/ 50",
)


print(
    "Problem folds:",
    len(
        problem_folds
    ),
)


if problem_folds:

    problem_folds_df = (
        pd.DataFrame(
            problem_folds
        )
    )

    print(
        "\nPROBLEM FOLDS:"
    )

    display(
        problem_folds_df
    )

else:

    print(
        "\nAll 50 fold directories contain "
        "the required saved files."
    )


# ------------------------------------------------------------
# 6. Stop aggregation if fewer than 50 valid folds exist
# ------------------------------------------------------------

if len(
    fold_results_df
) != 50:

    raise RuntimeError(
        "\nOnly "
        f"{len(fold_results_df)} / 50 "
        "valid fold result sets were found.\n"
        "See the problem-fold table above."
    )


# ------------------------------------------------------------
# 7. Validate repeated structure
# ------------------------------------------------------------

assert (
    fold_results_df[
        "repeat"
    ].nunique()
    == 10
)


assert (
    fold_results_df
    .groupby(
        "repeat"
    )
    .size()
    .eq(5)
    .all()
)


# ------------------------------------------------------------
# 8. Build the 10 repeat-level observations
#
# These mean macro-F1 values are the values later used
# for paired Wilcoxon comparison.
# ------------------------------------------------------------

repeat_level_summary_df = (
    fold_results_df
    .groupby(
        "repeat",
        as_index=False,
    )
    .agg(
        mean_accuracy=(
            "accuracy",
            "mean",
        ),

        mean_balanced_accuracy=(
            "balanced_accuracy",
            "mean",
        ),

        mean_macro_precision=(
            "macro_precision",
            "mean",
        ),

        mean_macro_recall=(
            "macro_recall",
            "mean",
        ),

        mean_macro_f1=(
            "macro_f1",
            "mean",
        ),

        sd_macro_f1=(
            "macro_f1",
            "std",
        ),
    )
)


repeat_level_summary_df[
    "wilcoxon_value"
] = (
    repeat_level_summary_df[
        "mean_macro_f1"
    ]
)


# ------------------------------------------------------------
# 9. Save consolidated tables
# ------------------------------------------------------------

ALL_FOLD_RESULTS_PATH = (
    RESULTS_ROOT
    / "all_fold_results.csv"
)


REPEAT_LEVEL_SUMMARY_PATH = (
    RESULTS_ROOT
    / "repeat_level_summary.csv"
)


fold_results_df.to_csv(
    ALL_FOLD_RESULTS_PATH,
    index=False,
)


repeat_level_summary_df.to_csv(
    REPEAT_LEVEL_SUMMARY_PATH,
    index=False,
)


# ------------------------------------------------------------
# 10. Display results
# ------------------------------------------------------------

print(
    "\n"
    + "=" * 72
)

print(
    "50 OUTER-FOLD RESULTS"
)

print(
    "=" * 72
)


display(
    fold_results_df
)


print(
    "\n"
    + "=" * 72
)

print(
    "10 REPEAT-LEVEL RESULTS"
)

print(
    "=" * 72
)


display(
    repeat_level_summary_df
)


print(
    "\nOverall mean outer-fold macro F1:",
    round(
        fold_results_df[
            "macro_f1"
        ].mean(),
        6,
    ),
)


print(
    "Mean of 10 repeat-level macro F1 values:",
    round(
        repeat_level_summary_df[
            "mean_macro_f1"
        ].mean(),
        6,
    ),
)


print(
    "\nSaved fold-level table:"
)

print(
    ALL_FOLD_RESULTS_PATH
)


print(
    "\nSaved repeat-level table:"
)

print(
    REPEAT_LEVEL_SUMMARY_PATH
)


print(
    "\nRESNET50 + SVM RESULT ACCESS PASSED."
)

========================================================================
RESNET50 + SVM SAVED RESULT CHECK
========================================================================
Results root: /content/drive/MyDrive/brain_tumour_colab/results/repeated_nested_cv/resnet50_svm

Valid fold results found: 50 / 50
Problem folds: 0

All 50 fold directories contain the required saved files.

========================================================================
50 OUTER-FOLD RESULTS
========================================================================

,model,repeat,fold,outer_split_seed,inner_cv_seed,outer_training_samples,outer_validation_samples,best_C,best_gamma,best_inner_macro_f1,accuracy,balanced_accuracy,macro_precision,macro_recall,macro_f1,elapsed_seconds,fold_directory
0,ResNet50_fixed_features_SVM,1,1,202601,303101,4480,1120,10,scale,0.940540,0.963393,0.963393,0.964282,0.963393,0.963537,1530.667471,/content/drive/MyDrive/brain_tumour_colab/resu...
1,ResNet50_fixed_features_SVM,1,2,202601,303102,4480,1120,10,scale,0.946815,0.954464,0.954464,0.955543,0.954464,0.954558,1489.084888,/content/drive/MyDrive/brain_tumour_colab/resu...
2,ResNet50_fixed_features_SVM,1,3,202601,303103,4480,1120,100,0.0001,0.940175,0.955357,0.955357,0.955732,0.955357,0.955462,1476.240939,/content/drive/MyDrive/brain_tumour_colab/resu...
3,ResNet50_fixed_features_SVM,1,4,202601,303104,4480,1120,10,scale,0.941420,0.959821,0.959821,0.960617,0.959821,0.959857,1477.913745,/content/drive/MyDrive/brain_tumour_colab/resu...
4,ResNet50_fixed_features_SVM,1,5,202601,303105,4480,1120,10,scale,0.942161,0.947321,0.947321,0.950970,0.947321,0.947683,1481.021127,/content/drive/MyDrive/brain_tumour_colab/resu...
5,ResNet50_fixed_features_SVM,2,1,202602,303201,4480,1120,100,0.0001,0.940588,0.951786,0.951786,0.952278,0.951786,0.951854,1471.170585,/content/drive/MyDrive/brain_tumour_colab/resu...
6,ResNet50_fixed_features_SVM,2,2,202602,303202,4480,1120,10,scale,0.940595,0.950000,0.950000,0.952832,0.950000,0.950456,1484.603794,/content/drive/MyDrive/brain_tumour_colab/resu...
7,ResNet50_fixed_features_SVM,2,3,202602,303203,4480,1120,10,scale,0.938501,0.969643,0.969643,0.969960,0.969643,0.969713,1474.245519,/content/drive/MyDrive/brain_tumour_colab/resu...
8,ResNet50_fixed_features_SVM,2,4,202602,303204,4480,1120,10,scale,0.942178,0.963393,0.963393,0.963960,0.963393,0.963474,1507.633168,/content/drive/MyDrive/brain_tumour_colab/resu...
9,ResNet50_fixed_features_SVM,2,5,202602,303205,4480,1120,10,scale,0.942946,0.951786,0.951786,0.954178,0.951786,0.952059,1472.166893,/content/drive/MyDrive/brain_tumour_colab/resu...
10,ResNet50_fixed_features_SVM,3,1,202603,303301,4480,1120,10,scale,0.937604,0.964286,0.964286,0.964386,0.964286,0.964284,1508.080633,/content/drive/MyDrive/brain_tumour_colab/resu...
11,ResNet50_fixed_features_SVM,3,2,202603,303302,4480,1120,10,scale,0.939009,0.962500,0.962500,0.964113,0.962500,0.962667,1527.286037,/content/drive/MyDrive/brain_tumour_colab/resu...
12,ResNet50_fixed_features_SVM,3,3,202603,303303,4480,1120,10,scale,0.939630,0.958036,0.958036,0.959773,0.958036,0.958212,1675.488717,/content/drive/MyDrive/brain_tumour_colab/resu...
13,ResNet50_fixed_features_SVM,3,4,202603,303304,4480,1120,10,scale,0.943464,0.953571,0.953571,0.953285,0.953571,0.953288,1665.886697,/content/drive/MyDrive/brain_tumour_colab/resu...
14,ResNet50_fixed_features_SVM,3,5,202603,303305,4480,1120,10,scale,0.946887,0.954464,0.954464,0.956681,0.954464,0.954894,1642.139261,/content/drive/MyDrive/brain_tumour_colab/resu...
15,ResNet50_fixed_features_SVM,4,1,202604,303401,4480,1120,10,scale,0.942041,0.959821,0.959821,0.961823,0.959821,0.960123,1629.920127,/content/drive/MyDrive/brain_tumour_colab/resu...
16,ResNet50_fixed_features_SVM,4,2,202604,303402,4480,1120,10,scale,0.943187,0.966071,0.966071,0.967135,0.966071,0.966233,1687.200973,/content/drive/MyDrive/brain_tumour_colab/resu...
17,ResNet50_fixed_features_SVM,4,3,202604,303403,4480,1120,10,scale,0.941150,0.958036,0.958036,0.959265,0.958036,0.958143,1718.879996,/content/drive/MyDrive/brain_tumour_colab/resu...
18,ResNet50_fixed_features_SVM,4,4,202604,303404,4480,1120,100,0.0001,0.951011,0.939286,0.939286,0.940483,0.939286,0.939556,1667.877165,/content/drive/MyDrive/brain_tumour_colab/resu...
19,ResNet50_fixed_features_SVM,4,5,202604,303405,4480,1120,100,0.0001,0.940536,0.960714,0.960714,0.961410,0.960714,0.960872,1674.827520,/content/drive/MyDrive/brain_tumour_colab/resu...
20,ResNet50_fixed_features_SVM,5,1,202605,303501,4480,1120,10,scale,0.941752,0.958036,0.958036,0.959257,0.958036,0.958373,1655.389941,/content/drive/MyDrive/brain_tumour_colab/resu...
21,ResNet50_fixed_features_SVM,5,2,202605,303502,4480,1120,100,0.0001,0.936499,0.963393,0.963393,0.964351,0.963393,0.963575,1642.264028,/content/drive/MyDrive/brain_tumour_colab/resu...
22,ResNet50_fixed_features_SVM,5,3,202605,303503,4480,1120,100,0.0001,0.944532,0.953571,0.953571,0.954528,0.953571,0.953745,1633.037010,/content/drive/MyDrive/brain_tumour_colab/resu...
23,ResNet50_fixed_features_SVM,5,4,202605,303504,4480,1120,100,0.0001,0.942151,0.957143,0.957143,0.957309,0.957143,0.957216,1623.715049,/content/drive/MyDrive/brain_tumour_colab/resu...
24,ResNet50_fixed_features_SVM,5,5,202605,303505,4480,1120,10,scale,0.942804,0.954464,0.954464,0.955119,0.954464,0.954414,1627.272085,/content/drive/MyDrive/brain_tumour_colab/resu...
25,ResNet50_fixed_features_SVM,6,1,202606,303601,4480,1120,10,scale,0.937265,0.958929,0.958929,0.960001,0.958929,0.959149,1646.851340,/content/drive/MyDrive/brain_tumour_colab/resu...
26,ResNet50_fixed_features_SVM,6,2,202606,303602,4480,1120,10,scale,0.946180,0.949107,0.949107,0.950486,0.949107,0.949292,1631.720573,/content/drive/MyDrive/brain_tumour_colab/resu...
27,ResNet50_fixed_features_SVM,6,3,202606,303603,4480,1120,10,scale,0.938178,0.967857,0.967857,0.968003,0.967857,0.967844,1643.910088,/content/drive/MyDrive/brain_tumour_colab/resu...
28,ResNet50_fixed_features_SVM,6,4,202606,303604,4480,1120,10,scale,0.937862,0.953571,0.953571,0.954692,0.953571,0.953732,1666.706485,/content/drive/MyDrive/brain_tumour_colab/resu...
29,ResNet50_fixed_features_SVM,6,5,202606,303605,4480,1120,10,scale,0.943028,0.959821,0.959821,0.960616,0.959821,0.959945,1667.016618,/content/drive/MyDrive/brain_tumour_colab/resu...
30,ResNet50_fixed_features_SVM,7,1,202607,303701,4480,1120,100,0.0001,0.937614,0.961607,0.961607,0.961429,0.961607,0.961452,1649.525877,/content/drive/MyDrive/brain_tumour_colab/resu...
31,ResNet50_fixed_features_SVM,7,2,202607,303702,4480,1120,10,scale,0.948296,0.941071,0.941071,0.942126,0.941071,0.941282,1620.108784,/content/drive/MyDrive/brain_tumour_colab/resu...
32,ResNet50_fixed_features_SVM,7,3,202607,303703,4480,1120,10,scale,0.942068,0.947321,0.947321,0.949540,0.947321,0.947683,1576.161390,/content/drive/MyDrive/brain_tumour_colab/resu...
33,ResNet50_fixed_features_SVM,7,4,202607,303704,4480,1120,10,scale,0.940614,0.961607,0.961607,0.962950,0.961607,0.961753,1662.740216,/content/drive/MyDrive/brain_tumour_colab/resu...
34,ResNet50_fixed_features_SVM,7,5,202607,303705,4480,1120,10,scale,0.941638,0.958036,0.958036,0.960015,0.958036,0.958349,1606.614883,/content/drive/MyDrive/brain_tumour_colab/resu...
35,ResNet50_fixed_features_SVM,8,1,202608,303801,4480,1120,10,scale,0.937715,0.961607,0.961607,0.962557,0.961607,0.961688,1587.281833,/content/drive/MyDrive/brain_tumour_colab/resu...
36,ResNet50_fixed_features_SVM,8,2,202608,303802,4480,1120,10,scale,0.941243,0.960714,0.960714,0.961722,0.960714,0.960876,1607.535729,/content/drive/MyDrive/brain_tumour_colab/resu...
37,ResNet50_fixed_features_SVM,8,3,202608,303803,4480,1120,10,scale,0.948981,0.955357,0.955357,0.956079,0.955357,0.955493,1632.387150,/content/drive/MyDrive/brain_tumour_colab/resu...
38,ResNet50_fixed_features_SVM,8,4,202608,303804,4480,1120,10,scale,0.942202,0.956250,0.956250,0.957038,0.956250,0.956366,1626.063230,/content/drive/MyDrive/brain_tumour_colab/resu...
39,ResNet50_fixed_features_SVM,8,5,202608,303805,4480,1120,100,0.0001,0.940154,0.954464,0.954464,0.955837,0.954464,0.954669,1618.907523,/content/drive/MyDrive/brain_tumour_colab/resu...
40,ResNet50_fixed_features_SVM,9,1,202609,303901,4480,1120,100,0.0001,0.940187,0.963393,0.963393,0.963278,0.963393,0.963285,1620.957357,/content/drive/MyDrive/brain_tumour_colab/resu...
41,ResNet50_fixed_features_SVM,9,2,202609,303902,4480,1120,100,0.0001,0.945206,0.950000,0.950000,0.951286,0.950000,0.950322,1613.898908,/content/drive/MyDrive/brain_tumour_colab/resu...
42,ResNet50_fixed_features_SVM,9,3,202609,303903,4480,1120,10,scale,0.943374,0.950000,0.950000,0.950637,0.950000,0.950066,1585.921492,/content/drive/MyDrive/brain_tumour_colab/resu...
43,ResNet50_fixed_features_SVM,9,4,202609,303904,4480,1120,10,scale,0.941077,0.964286,0.964286,0.964811,0.964286,0.964386,1925.447795,/content/drive/MyDrive/brain_tumour_colab/resu...
44,ResNet50_fixed_features_SVM,9,5,202609,303905,4480,1120,10,scale,0.946477,0.949107,0.949107,0.950265,0.949107,0.949175,1922.439738,/content/drive/MyDrive/brain_tumour_colab/resu...
45,ResNet50_fixed_features_SVM,10,1,202610,304001,4480,1120,100,0.0001,0.942566,0.963393,0.963393,0.963643,0.963393,0.963466,1928.334564,/content/drive/MyDrive/brain_tumour_colab/resu...
46,ResNet50_fixed_features_SVM,10,2,202610,304002,4480,1120,10,scale,0.940076,0.952679,0.952679,0.953876,0.952679,0.952837,1675.440044,/content/drive/MyDrive/brain_tumour_colab/resu...
47,ResNet50_fixed_features_SVM,10,3,202610,304003,4480,1120,10,scale,0.938108,0.962500,0.962500,0.964989,0.962500,0.962797,1772.226828,/content/drive/MyDrive/brain_tumour_colab/resu...
48,ResNet50_fixed_features_SVM,10,4,202610,304004,4480,1120,10,scale,0.941917,0.953571,0.953571,0.954352,0.953571,0.953745,1826.043925,/content/drive/MyDrive/brain_tumour_colab/resu...
49,ResNet50_fixed_features_SVM,10,5,202610,304005,4480,1120,10,scale,0.942648,0.955357,0.955357,0.956572,0.955357,0.955455,1799.443416,/content/drive/MyDrive/brain_tumour_colab/resu...

========================================================================
10 REPEAT-LEVEL RESULTS
========================================================================

,repeat,mean_accuracy,mean_balanced_accuracy,mean_macro_precision,mean_macro_recall,mean_macro_f1,sd_macro_f1,wilcoxon_value
0,1,0.956071,0.956071,0.957429,0.956071,0.956219,0.005979,0.956219
1,2,0.957321,0.957321,0.958642,0.957321,0.957511,0.008602,0.957511
2,3,0.958571,0.958571,0.959647,0.958571,0.958669,0.004768,0.958669
3,4,0.956786,0.956786,0.958023,0.956786,0.956985,0.010193,0.956985
4,5,0.957321,0.957321,0.958113,0.957321,0.957465,0.003917,0.957465
5,6,0.957857,0.957857,0.958759,0.957857,0.957992,0.007001,0.957992
6,7,0.953929,0.953929,0.955212,0.953929,0.954104,0.009167,0.954104
7,8,0.957679,0.957679,0.958647,0.957679,0.957819,0.003231,0.957819
8,9,0.955357,0.955357,0.956055,0.955357,0.955447,0.007680,0.955447
9,10,0.957500,0.957500,0.958687,0.957500,0.957660,0.005088,0.957660

Overall mean outer-fold macro F1: 0.956987
Mean of 10 repeat-level macro F1 values: 0.956987

Saved fold-level table:
/content/drive/MyDrive/brain_tumour_colab/results/repeated_nested_cv/resnet50_svm/all_fold_results.csv

Saved repeat-level table:
/content/drive/MyDrive/brain_tumour_colab/results/repeated_nested_cv/resnet50_svm/repeat_level_summary.csv

RESNET50 + SVM RESULT ACCESS PASSED.

In [10]:
# ============================================================
# RESNET50 + RF — CHECKPOINTED STEP 1
# RESTART / RECOVERY CONFIGURATION
#
# CRITICAL RESUME BEHAVIOUR:
#
#   - candidate manifest will be saved once per outer fold
#   - EVERY completed inner-CV fit will be saved immediately
#   - completed stages will be saved
#   - completed inner searches will be saved
#   - completed outer folds will be skipped
#   - interrupted outer folds will RESUME inside the search
#
# IMPORTANT:
#   - Existing ResNet50 features are reused.
#   - Existing shared 10 × 5 assignments are reused.
#   - No feature extraction occurs.
#   - No fold assignments are regenerated.
#   - Existing completed RF folds are preserved.
#   - Nothing is deleted in this cell.
#   - Testing data is NEVER used.
# ============================================================

import json
import math
import os
from pathlib import Path

import numpy as np
import pandas as pd

from sklearn.ensemble import (
    RandomForestClassifier,
)

from sklearn.model_selection import (
    ParameterGrid,
    ParameterSampler,
    StratifiedKFold,
)


# ============================================================
# 1. REQUIRED HYBRID-1 STATE
#
# These variables/functions must already exist from:
#
#   Hybrid Step 5
#   Hybrid Step 6
#   Hybrid Step 7
# ============================================================

required_resnet50_rf_globals = [

    "REPEATED_RESNET50_RF_DIR",

    "training_features",

    "training_class_indices",

    "training_relative_paths",

    "repeated_folds_df",

    "make_hybrid_outer_partition",

    "get_hybrid_inner_cv_seed",

    "get_hybrid_rf_model_seed",

    "get_hybrid_rf_search_seed",

    "FEATURE_DIMENSION",

    "CLASS_NAMES",

    "INDEX_TO_CLASS",
]


missing_resnet50_rf_globals = [

    variable_name

    for variable_name
    in required_resnet50_rf_globals

    if variable_name
    not in globals()
]


assert not missing_resnet50_rf_globals, (
    "Required Hybrid setup is missing:\n"
    f"{missing_resnet50_rf_globals}\n\n"
    "Rerun the existing Hybrid Steps 5, 6 and 7 first."
)


# ============================================================
# 2. STRICT DATA VALIDATION
# ============================================================

assert FEATURE_DIMENSION == 2048


assert training_features.shape == (
    5600,
    2048,
)


assert training_features.dtype == np.float32


assert len(
    training_class_indices
) == 5600


assert len(
    training_relative_paths
) == 5600


assert (
    len(
        np.unique(
            training_relative_paths
        )
    )
    == 5600
)


assert np.isfinite(
    training_features
).all()


assert set(
    np.unique(
        training_class_indices
    )
) == {
    0,
    1,
    2,
    3,
}


assert len(
    repeated_folds_df
) == 56000


# ============================================================
# 3. RESULTS ROOT
#
# SAME directory used by the previous ResNet50 + RF runner.
#
# We do NOT create a competing experiment directory.
# ============================================================

RESNET50_RF_RESULTS_ROOT = (
    REPEATED_RESNET50_RF_DIR
)


RESNET50_RF_RESULTS_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)


# ============================================================
# 4. EXACT RF SEARCH SPACE
#
# This remains unchanged from the previous RF experiment.
# ============================================================

RESNET50_RF_PARAMETER_DISTRIBUTIONS = {

    "criterion": [
        "gini",
        "entropy",
    ],

    "max_depth": [
        None,
        20,
        40,
        60,
        80,
    ],

    "min_samples_split": [
        2,
        5,
        10,
        20,
    ],

    "min_samples_leaf": [
        1,
        2,
        4,
        8,
    ],

    "max_features": [
        "sqrt",
        "log2",
        0.02,
        0.05,
        0.10,
        0.20,
    ],

    "bootstrap": [
        True,
        False,
    ],
}


# ============================================================
# 5. MANUALLY CHECKPOINTED SUCCESSIVE-HALVING CONFIGURATION
#
# Same experimental search:
#
#   100 initial candidates
#
#   Stage 1:
#       100 candidates × 25 trees
#
#   Stage 2:
#       34 candidates × 75 trees
#
#   Stage 3:
#       12 candidates × 225 trees
#
#   Stage 4:
#       4 candidates × 675 trees
#
#   Winner:
#       best candidate after Stage 4
#
# Every candidate is evaluated with the same deterministic
# 3-fold inner CV for that outer fold.
# ============================================================

RESNET50_RF_INITIAL_CANDIDATES = 100

RESNET50_RF_HALVING_FACTOR = 3


RESNET50_RF_STAGE_RESOURCES = [
    25,
    75,
    225,
    675,
]


RESNET50_RF_EXPECTED_STAGE_CANDIDATES = [
    100,
    34,
    12,
    4,
]


# ------------------------------------------------------------
# Validate full discrete space
# ------------------------------------------------------------

resnet50_rf_total_possible_combinations = len(
    list(
        ParameterGrid(
            RESNET50_RF_PARAMETER_DISTRIBUTIONS
        )
    )
)


assert (
    resnet50_rf_total_possible_combinations
    == 1920
)


assert (
    RESNET50_RF_INITIAL_CANDIDATES
    == 100
)


assert (
    RESNET50_RF_HALVING_FACTOR
    == 3
)


assert (
    RESNET50_RF_STAGE_RESOURCES
    == [
        25,
        75,
        225,
        675,
    ]
)


assert (
    RESNET50_RF_EXPECTED_STAGE_CANDIDATES
    == [
        100,
        34,
        12,
        4,
    ]
)


# ============================================================
# 6. VERIFY DETERMINISTIC SEED SCHEDULES
#
# SAME seeds already defined in Hybrid Step 5.
# ============================================================

assert (
    get_hybrid_inner_cv_seed(
        1,
        1,
    )
    == 303101
)


assert (
    get_hybrid_rf_model_seed(
        1,
        1,
    )
    == 404101
)


assert (
    get_hybrid_rf_search_seed(
        1,
        1,
    )
    == 414101
)


# ============================================================
# 7. ATOMIC DATAFRAME SAVE
#
# The temporary file is written first.
# The destination filename is replaced only when writing
# succeeds.
# ============================================================

def resnet50_rf_save_dataframe_atomic(
    dataframe,
    destination_path,
):

    destination_path = Path(
        destination_path
    )


    destination_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )


    temporary_path = (
        destination_path.parent
        / (
            destination_path.name
            + ".tmp"
        )
    )


    with open(
        temporary_path,
        "w",
        encoding="utf-8",
        newline="",
    ) as file:

        dataframe.to_csv(
            file,
            index=False,
        )


        file.flush()

        os.fsync(
            file.fileno()
        )


    os.replace(
        temporary_path,
        destination_path,
    )


    assert destination_path.exists()


# ============================================================
# 8. JSON SERIALISATION
# ============================================================

def resnet50_rf_json_default(
    value,
):

    if isinstance(
        value,
        np.integer,
    ):

        return int(
            value
        )


    if isinstance(
        value,
        np.floating,
    ):

        return float(
            value
        )


    if isinstance(
        value,
        np.bool_,
    ):

        return bool(
            value
        )


    if isinstance(
        value,
        np.ndarray,
    ):

        return value.tolist()


    if isinstance(
        value,
        Path,
    ):

        return str(
            value
        )


    raise TypeError(
        "Object of type "
        f"{type(value).__name__} "
        "is not JSON serializable."
    )


# ============================================================
# 9. ATOMIC JSON SAVE
# ============================================================

def resnet50_rf_save_json_atomic(
    dictionary,
    destination_path,
):

    destination_path = Path(
        destination_path
    )


    destination_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )


    temporary_path = (
        destination_path.parent
        / (
            destination_path.name
            + ".tmp"
        )
    )


    with open(
        temporary_path,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            dictionary,
            file,
            indent=4,
            ensure_ascii=False,
            default=
                resnet50_rf_json_default,
        )


        file.flush()

        os.fsync(
            file.fileno()
        )


    os.replace(
        temporary_path,
        destination_path,
    )


    assert destination_path.exists()


# ============================================================
# 10. CHECKPOINTED RF FOLD PATHS
#
# Final outputs retain the same five filenames used by the
# previous Hybrid RF runner.
#
# New resumable search state lives INSIDE:
#
#       search_progress/
#
# This means existing completed folds remain compatible.
# ============================================================

def get_checkpointed_resnet50_rf_fold_paths(
    repeat_number,
    fold_number,
):

    fold_directory = (
        RESNET50_RF_RESULTS_ROOT
        / f"repeat_{repeat_number:02d}"
        / f"fold_{fold_number:02d}"
    )


    search_progress_directory = (
        fold_directory
        / "search_progress"
    )


    return {

        # ----------------------------------------------------
        # Directories
        # ----------------------------------------------------

        "directory":
            fold_directory,

        "search_progress_directory":
            search_progress_directory,


        # ----------------------------------------------------
        # Resumable inner-search state
        # ----------------------------------------------------

        "candidate_manifest":
            (
                search_progress_directory
                / "candidate_manifest.csv"
            ),

        "inner_fit_progress":
            (
                search_progress_directory
                / "inner_fit_progress.csv"
            ),

        "search_complete":
            (
                search_progress_directory
                / "search_complete.json"
            ),


        # ----------------------------------------------------
        # Final fold outputs
        #
        # SAME names as the previous Hybrid RF runner.
        # ----------------------------------------------------

        "search_results":
            (
                fold_directory
                / "inner_search_results.csv"
            ),

        "selected_parameters":
            (
                fold_directory
                / "selected_parameters.json"
            ),

        "outer_predictions":
            (
                fold_directory
                / "outer_predictions.csv"
            ),

        "outer_metrics":
            (
                fold_directory
                / "outer_metrics.json"
            ),

        "completion_marker":
            (
                fold_directory
                / "COMPLETED.json"
            ),
    }


# ============================================================
# 11. CHECK WHETHER AN OUTER FOLD IS ALREADY FULLY COMPLETE
#
# This deliberately accepts a previously completed fold from
# the old Hybrid RF runner.
#
# It does NOT require search_progress/ to exist for a fold
# which was already completed before this checkpointing change.
# ============================================================

def is_checkpointed_resnet50_rf_fold_complete(
    repeat_number,
    fold_number,
):

    paths = (
        get_checkpointed_resnet50_rf_fold_paths(
            repeat_number,
            fold_number,
        )
    )


    required_final_files = [

        paths[
            "search_results"
        ],

        paths[
            "selected_parameters"
        ],

        paths[
            "outer_predictions"
        ],

        paths[
            "outer_metrics"
        ],

        paths[
            "completion_marker"
        ],
    ]


    if not all(
        path.exists()
        for path
        in required_final_files
    ):

        return False


    try:

        with open(
            paths[
                "completion_marker"
            ],
            "r",
            encoding="utf-8",
        ) as file:

            completion = json.load(
                file
            )


        if (
            completion.get(
                "status"
            )
            != "completed"
        ):

            return False


        if (
            completion.get(
                "model"
            )
            != "ResNet50_fixed_features_RF"
        ):

            return False


        if (
            int(
                completion[
                    "repeat"
                ]
            )
            != repeat_number
        ):

            return False


        if (
            int(
                completion[
                    "fold"
                ]
            )
            != fold_number
        ):

            return False


        with open(
            paths[
                "outer_metrics"
            ],
            "r",
            encoding="utf-8",
        ) as file:

            metrics = json.load(
                file
            )


        if (
            int(
                metrics[
                    "repeat"
                ]
            )
            != repeat_number
        ):

            return False


        if (
            int(
                metrics[
                    "fold"
                ]
            )
            != fold_number
        ):

            return False


        if (
            int(
                metrics[
                    "outer_training_samples"
                ]
            )
            != 4480
        ):

            return False


        if (
            int(
                metrics[
                    "outer_validation_samples"
                ]
            )
            != 1120
        ):

            return False


        predictions_df = pd.read_csv(
            paths[
                "outer_predictions"
            ]
        )


        if (
            len(
                predictions_df
            )
            != 1120
        ):

            return False


        return True


    except Exception:

        return False


# ============================================================
# 12. INNER CV CONSTRUCTOR
#
# The same three deterministic inner folds will be reused for
# every candidate and every successive-halving stage within
# one outer fold.
# ============================================================

def make_checkpointed_resnet50_rf_inner_cv(
    repeat_number,
    fold_number,
):

    return StratifiedKFold(
        n_splits=3,
        shuffle=True,
        random_state=
            get_hybrid_inner_cv_seed(
                repeat_number,
                fold_number,
            ),
    )


# ============================================================
# 13. PARAMETER RECONSTRUCTION HELPERS
#
# CSV persistence can convert None / numbers / booleans into
# generic dataframe representations.
#
# These functions reconstruct the exact sklearn parameters
# when a candidate manifest is loaded after a disconnect.
# ============================================================

def resnet50_rf_optional_integer(
    value,
):

    if pd.isna(
        value
    ):

        return None


    return int(
        value
    )


def resnet50_rf_normalise_max_features(
    value,
):

    if isinstance(
        value,
        str,
    ):

        cleaned_value = (
            value.strip()
        )


        if cleaned_value in (
            "sqrt",
            "log2",
        ):

            return cleaned_value


        return float(
            cleaned_value
        )


    return float(
        value
    )


def resnet50_rf_candidate_parameters_from_row(
    row,
):

    bootstrap_value = (
        row[
            "bootstrap"
        ]
    )


    if isinstance(
        bootstrap_value,
        str,
    ):

        bootstrap_value = (
            bootstrap_value
            .strip()
            .lower()
            == "true"
        )

    else:

        bootstrap_value = bool(
            bootstrap_value
        )


    return {

        "criterion":
            str(
                row[
                    "criterion"
                ]
            ),

        "max_depth":
            resnet50_rf_optional_integer(
                row[
                    "max_depth"
                ]
            ),

        "min_samples_split":
            int(
                row[
                    "min_samples_split"
                ]
            ),

        "min_samples_leaf":
            int(
                row[
                    "min_samples_leaf"
                ]
            ),

        "max_features":
            resnet50_rf_normalise_max_features(
                row[
                    "max_features"
                ]
            ),

        "bootstrap":
            bootstrap_value,
    }


# ============================================================
# 14. AUDIT CURRENT RESNET50 + RF STATE
#
# NOTHING is deleted.
#
# We record:
#
#   - completely finished folds
#   - folds that already contain checkpoint progress
#   - incomplete directories from the old monolithic runner
# ============================================================

fully_completed_rf_folds = []

checkpointed_partial_rf_folds = []

other_incomplete_rf_directories = []


for repeat_number in range(
    1,
    11,
):

    for fold_number in range(
        1,
        6,
    ):

        paths = (
            get_checkpointed_resnet50_rf_fold_paths(
                repeat_number,
                fold_number,
            )
        )


        if (
            is_checkpointed_resnet50_rf_fold_complete(
                repeat_number,
                fold_number,
            )
        ):

            fully_completed_rf_folds.append(
                (
                    repeat_number,
                    fold_number,
                )
            )


            continue


        if (
            paths[
                "inner_fit_progress"
            ]
            .exists()
        ):

            try:

                progress_df = pd.read_csv(
                    paths[
                        "inner_fit_progress"
                    ]
                )


                completed_inner_fits = len(
                    progress_df
                )


            except Exception:

                completed_inner_fits = -1


            checkpointed_partial_rf_folds.append(
                (
                    repeat_number,
                    fold_number,
                    completed_inner_fits,
                )
            )


            continue


        if (
            paths[
                "directory"
            ]
            .exists()
        ):

            other_incomplete_rf_directories.append(
                (
                    repeat_number,
                    fold_number,
                )
            )


# ============================================================
# 15. DISPLAY
# ============================================================

print("=" * 80)

print(
    "RESNET50 + RF CHECKPOINTED RECOVERY SETUP"
)

print("=" * 80)


print(
    "Results root:",
    RESNET50_RF_RESULTS_ROOT,
)


print(
    "\nFeature matrix:",
    training_features.shape,
)


print(
    "Feature dtype:",
    training_features.dtype,
)


print(
    "Repeated assignments:",
    len(
        repeated_folds_df
    ),
)


print(
    "\nRF parameter combinations:",
    resnet50_rf_total_possible_combinations,
)


print(
    "Initial candidates:",
    RESNET50_RF_INITIAL_CANDIDATES,
)


print(
    "Candidate progression:",
    "100 -> 34 -> 12 -> 4 -> winner",
)


print(
    "Tree resources:",
    RESNET50_RF_STAGE_RESOURCES,
)


print(
    "\nR1/F1 inner-CV seed:",
    get_hybrid_inner_cv_seed(
        1,
        1,
    ),
)


print(
    "R1/F1 RF model seed:",
    get_hybrid_rf_model_seed(
        1,
        1,
    ),
)


print(
    "R1/F1 RF search seed:",
    get_hybrid_rf_search_seed(
        1,
        1,
    ),
)


print(
    "\nFully completed outer folds:",
    len(
        fully_completed_rf_folds
    ),
    "/ 50",
)


if fully_completed_rf_folds:

    print(
        fully_completed_rf_folds
    )


print(
    "\nFolds with NEW checkpoint progress:",
    len(
        checkpointed_partial_rf_folds
    ),
)


if checkpointed_partial_rf_folds:

    print(
        checkpointed_partial_rf_folds
    )


print(
    "\nOther incomplete fold directories:",
    len(
        other_incomplete_rf_directories
    ),
)


if other_incomplete_rf_directories:

    print(
        other_incomplete_rf_directories
    )


print(
    "\nIMPORTANT:"
)


print(
    "Nothing was deleted."
)


print(
    "No Random Forest model was fitted."
)


print(
    "No ResNet50 features were extracted."
)


print(
    "The existing repeated 10 × 5 assignments were reused."
)


print(
    "The Testing partition was not accessed."
)


print(
    "\nRESNET50 + RF CHECKPOINTED STEP 1: PASSED"
)

================================================================================
RESNET50 + RF CHECKPOINTED RECOVERY SETUP
================================================================================
Results root: /content/drive/MyDrive/brain_tumour_colab/results/repeated_nested_cv/resnet50_rf

Feature matrix: (5600, 2048)
Feature dtype: float32
Repeated assignments: 56000

RF parameter combinations: 1920
Initial candidates: 100
Candidate progression: 100 -> 34 -> 12 -> 4 -> winner
Tree resources: [25, 75, 225, 675]

R1/F1 inner-CV seed: 303101
R1/F1 RF model seed: 404101
R1/F1 RF search seed: 414101

Fully completed outer folds: 5 / 50
[(1, 1), (1, 2), (1, 3), (1, 4), (1, 5)]

Folds with NEW checkpoint progress: 1
[(2, 1, 438)]

Other incomplete fold directories: 0

IMPORTANT:
Nothing was deleted.
No Random Forest model was fitted.
No ResNet50 features were extracted.
The existing repeated 10 × 5 assignments were reused.
The Testing partition was not accessed.

RESNET50 + RF CHECKPOINTED STEP 1: PASSED

In [9]:
# ============================================================
# RESNET50 + RF — CHECKPOINTED STEP 2
# MASTER 10 × 5 REPEATED NESTED-CV RUNNER
#
# PURPOSE:
#   Run the complete ResNet50 fixed-feature + Random Forest
#   repeated nested-CV experiment with INNER-FIT CHECKPOINTING.
#
# TOTAL:
#   10 repeats × 5 outer folds = 50 outer evaluations
#
# CRITICAL RESUME BEHAVIOUR:
#
#   COMPLETED OUTER FOLD
#       -> SKIPPED
#
#   COMPLETED INNER SEARCH
#       -> LOADED
#       -> only final refit / outer evaluation is repeated
#
#   PARTIALLY COMPLETED INNER SEARCH
#       -> candidate manifest loaded
#       -> completed inner fits loaded
#       -> completed fits SKIPPED
#       -> resumes from first missing candidate × inner fold
#
# CHECKPOINT FREQUENCY:
#   EVERY individual candidate × inner-fold fit is saved
#   immediately to Google Drive.
#
# SEARCH METHODOLOGY:
#
#   Search space:
#       1,920 possible RF configurations
#
#   Initial candidates:
#       100
#
#   Inner CV:
#       shuffled stratified 3-fold
#
#   Selection:
#       macro-F1
#
#   Successive halving:
#
#       Stage 1:
#           100 candidates
#           25 trees
#
#       Stage 2:
#           34 candidates
#           75 trees
#
#       Stage 3:
#           12 candidates
#           225 trees
#
#       Stage 4:
#           4 candidates
#           675 trees
#
#       Final winner:
#           best Stage-4 candidate
#
# IMPORTANT:
#   - Existing ResNet50 2,048-D features are reused.
#   - Shared repeated outer assignments are reused.
#   - Outer validation is untouched during inner search.
#   - Testing is NEVER accessed.
# ============================================================

import gc
import json
import math
import time

from pathlib import Path

import numpy as np
import pandas as pd

from sklearn.ensemble import (
    RandomForestClassifier,
)

from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)

from sklearn.model_selection import (
    ParameterSampler,
)


# ============================================================
# 1. MASTER VALIDATION
# ============================================================

assert FEATURE_DIMENSION == 2048

assert training_features.shape == (
    5600,
    2048,
)

assert len(
    training_class_indices
) == 5600

assert len(
    training_relative_paths
) == 5600

assert len(
    repeated_folds_df
) == 56000


assert (
    RESNET50_RF_INITIAL_CANDIDATES
    == 100
)

assert (
    RESNET50_RF_HALVING_FACTOR
    == 3
)

assert (
    RESNET50_RF_STAGE_RESOURCES
    == [
        25,
        75,
        225,
        675,
    ]
)

assert (
    RESNET50_RF_EXPECTED_STAGE_CANDIDATES
    == [
        100,
        34,
        12,
        4,
    ]
)


# ============================================================
# 2. CREATE / LOAD DETERMINISTIC CANDIDATE MANIFEST
# ============================================================

def get_or_create_resnet50_rf_candidate_manifest(
    repeat_number,
    fold_number,
    candidate_manifest_path,
):

    # --------------------------------------------------------
    # Existing manifest
    # --------------------------------------------------------

    if candidate_manifest_path.exists():

        candidate_manifest_df = (
            pd.read_csv(
                candidate_manifest_path
            )
        )


        print(
            "Loaded existing candidate manifest."
        )


    # --------------------------------------------------------
    # New deterministic manifest
    # --------------------------------------------------------

    else:

        sampled_candidates = list(
            ParameterSampler(

                RESNET50_RF_PARAMETER_DISTRIBUTIONS,

                n_iter=
                    RESNET50_RF_INITIAL_CANDIDATES,

                random_state=
                    get_hybrid_rf_search_seed(
                        repeat_number,
                        fold_number,
                    ),
            )
        )


        assert (
            len(
                sampled_candidates
            )
            == 100
        )


        candidate_rows = []


        for (
            candidate_id,
            parameters,
        ) in enumerate(
            sampled_candidates,
            start=1,
        ):

            candidate_rows.append(
                {
                    "candidate_id":
                        int(
                            candidate_id
                        ),

                    "criterion":
                        parameters[
                            "criterion"
                        ],

                    "max_depth":
                        parameters[
                            "max_depth"
                        ],

                    "min_samples_split":
                        parameters[
                            "min_samples_split"
                        ],

                    "min_samples_leaf":
                        parameters[
                            "min_samples_leaf"
                        ],

                    "max_features":
                        parameters[
                            "max_features"
                        ],

                    "bootstrap":
                        parameters[
                            "bootstrap"
                        ],
                }
            )


        candidate_manifest_df = (
            pd.DataFrame(
                candidate_rows
            )
        )


        assert (
            len(
                candidate_manifest_df
            )
            == 100
        )


        assert (
            candidate_manifest_df[
                "candidate_id"
            ]
            .nunique()
            == 100
        )


        resnet50_rf_save_dataframe_atomic(
            candidate_manifest_df,
            candidate_manifest_path,
        )


        print(
            "Created and saved new candidate manifest."
        )


    # --------------------------------------------------------
    # Manifest validation after loading
    # --------------------------------------------------------

    assert (
        len(
            candidate_manifest_df
        )
        == 100
    )


    candidate_manifest_df[
        "candidate_id"
    ] = (
        candidate_manifest_df[
            "candidate_id"
        ]
        .astype(
            int
        )
    )


    assert (
        candidate_manifest_df[
            "candidate_id"
        ]
        .tolist()
        == list(
            range(
                1,
                101,
            )
        )
    )


    return candidate_manifest_df


# ============================================================
# 3. LOAD CHECKPOINTED INNER-FIT PROGRESS
# ============================================================

def load_resnet50_rf_inner_progress(
    progress_path,
):

    progress_columns = [

        "repeat",
        "outer_fold",

        "stage",
        "n_estimators",

        "candidate_id",
        "inner_fold",

        "macro_f1",
        "fit_seconds",
    ]


    if progress_path.exists():

        progress_df = pd.read_csv(
            progress_path
        )


        print(
            "Loaded existing checkpoint progress:",
            len(
                progress_df
            ),
            "completed inner fits",
        )


    else:

        progress_df = pd.DataFrame(
            columns=
                progress_columns
        )


        print(
            "No previous inner-fit checkpoint found."
        )


    # --------------------------------------------------------
    # Validate / normalise loaded progress
    # --------------------------------------------------------

    if len(
        progress_df
    ) > 0:

        required_columns = set(
            progress_columns
        )


        assert required_columns.issubset(
            progress_df.columns
        )


        integer_columns = [

            "repeat",
            "outer_fold",

            "stage",
            "n_estimators",

            "candidate_id",
            "inner_fold",
        ]


        for column_name in (
            integer_columns
        ):

            progress_df[
                column_name
            ] = (
                pd.to_numeric(
                    progress_df[
                        column_name
                    ]
                )
                .astype(
                    int
                )
            )


        progress_df[
            "macro_f1"
        ] = pd.to_numeric(
            progress_df[
                "macro_f1"
            ]
        )


        progress_df[
            "fit_seconds"
        ] = pd.to_numeric(
            progress_df[
                "fit_seconds"
            ]
        )


        assert not (
            progress_df
            .duplicated(
                subset=[
                    "stage",
                    "candidate_id",
                    "inner_fold",
                ]
            )
            .any()
        ), (
            "Duplicate inner-fit checkpoint records "
            "were found."
        )


    return progress_df


# ============================================================
# 4. SAVE ONE COMPLETED INNER FIT
#
# The complete progress dataframe is written atomically.
#
# If Colab disconnects AFTER this function finishes, this
# exact candidate × inner-fold fit will be skipped next time.
# ============================================================

def checkpoint_resnet50_rf_inner_fit(
    progress_df,
    new_record,
    progress_path,
):

    new_row_df = pd.DataFrame(
        [
            new_record
        ]
    )


    updated_progress_df = pd.concat(
        [
            progress_df,
            new_row_df,
        ],
        ignore_index=True,
    )


    # --------------------------------------------------------
    # Duplicate protection
    # --------------------------------------------------------

    assert not (
        updated_progress_df
        .duplicated(
            subset=[
                "stage",
                "candidate_id",
                "inner_fold",
            ]
        )
        .any()
    )


    # --------------------------------------------------------
    # ATOMIC GOOGLE DRIVE SAVE
    # --------------------------------------------------------

    resnet50_rf_save_dataframe_atomic(
        updated_progress_df,
        progress_path,
    )


    return updated_progress_df


# ============================================================
# 5. CHECK WHETHER ONE INNER FIT IS ALREADY SAVED
# ============================================================

def resnet50_rf_inner_fit_exists(
    progress_df,
    stage_number,
    candidate_id,
    inner_fold_number,
):

    if len(
        progress_df
    ) == 0:

        return False


    return bool(
        (
            (
                progress_df[
                    "stage"
                ]
                == int(
                    stage_number
                )
            )
            &
            (
                progress_df[
                    "candidate_id"
                ]
                == int(
                    candidate_id
                )
            )
            &
            (
                progress_df[
                    "inner_fold"
                ]
                == int(
                    inner_fold_number
                )
            )
        )
        .any()
    )


# ============================================================
# 6. BUILD ONE COMPLETE STAGE RESULT
# ============================================================

def build_resnet50_rf_stage_results(
    progress_df,
    candidate_manifest_df,
    active_candidate_ids,
    stage_number,
    number_of_trees,
):

    # --------------------------------------------------------
    # Extract only current stage / current candidates
    # --------------------------------------------------------

    stage_progress_df = (
        progress_df[
            (
                progress_df[
                    "stage"
                ]
                == stage_number
            )
            &
            (
                progress_df[
                    "candidate_id"
                ]
                .astype(
                    int
                )
                .isin(
                    active_candidate_ids
                )
            )
        ]
        .copy()
    )


    expected_stage_fits = (
        len(
            active_candidate_ids
        )
        * 3
    )


    assert (
        len(
            stage_progress_df
        )
        == expected_stage_fits
    ), (
        f"Stage {stage_number} is incomplete. "
        f"Expected {expected_stage_fits} saved inner fits, "
        f"found {len(stage_progress_df)}."
    )


    # --------------------------------------------------------
    # Every candidate must have exactly three inner folds
    # --------------------------------------------------------

    candidate_fold_counts = (
        stage_progress_df
        .groupby(
            "candidate_id"
        )
        .size()
    )


    assert (
        candidate_fold_counts
        .eq(
            3
        )
        .all()
    )


    # --------------------------------------------------------
    # Candidate-level stage scores
    # --------------------------------------------------------

    stage_results_df = (
        stage_progress_df
        .groupby(
            "candidate_id",
            as_index=False,
        )
        .agg(

            mean_test_score=(
                "macro_f1",
                "mean",
            ),

            std_test_score=(
                "macro_f1",
                "std",
            ),

            total_fit_seconds=(
                "fit_seconds",
                "sum",
            ),

            inner_folds_completed=(
                "inner_fold",
                "count",
            ),
        )
    )


    # --------------------------------------------------------
    # Add parameter definitions
    # --------------------------------------------------------

    stage_results_df = (
        stage_results_df
        .merge(
            candidate_manifest_df,
            on="candidate_id",
            how="left",
            validate="one_to_one",
        )
    )


    # --------------------------------------------------------
    # Deterministic ranking
    #
    # Primary:
    #       highest mean macro-F1
    #
    # Tie:
    #       lowest deterministic candidate ID
    # --------------------------------------------------------

    stage_results_df = (
        stage_results_df
        .sort_values(
            by=[
                "mean_test_score",
                "candidate_id",
            ],
            ascending=[
                False,
                True,
            ],
        )
        .reset_index(
            drop=True
        )
    )


    stage_results_df.insert(
        0,
        "rank_test_score",
        np.arange(
            1,
            len(
                stage_results_df
            )
            + 1,
        ),
    )


    stage_results_df.insert(
        0,
        "n_resources",
        int(
            number_of_trees
        ),
    )


    # sklearn's HalvingRandomSearchCV uses 0-based iterations.
    stage_results_df.insert(
        0,
        "iter",
        int(
            stage_number
            - 1
        ),
    )


    return stage_results_df


# ============================================================
# 7. RUN / RESUME ONE COMPLETE OUTER FOLD
# ============================================================

def run_checkpointed_resnet50_rf_outer_fold(
    repeat_number,
    fold_number,
):

    # --------------------------------------------------------
    # Paths
    # --------------------------------------------------------

    paths = (
        get_checkpointed_resnet50_rf_fold_paths(
            repeat_number,
            fold_number,
        )
    )


    fold_directory = (
        paths[
            "directory"
        ]
    )


    search_progress_directory = (
        paths[
            "search_progress_directory"
        ]
    )


    fold_directory.mkdir(
        parents=True,
        exist_ok=True,
    )


    search_progress_directory.mkdir(
        parents=True,
        exist_ok=True,
    )


    # ========================================================
    # 7A. SKIP FULLY COMPLETED OUTER FOLD
    # ========================================================

    if (
        is_checkpointed_resnet50_rf_fold_complete(
            repeat_number,
            fold_number,
        )
    ):

        print(
            "\n"
            f"Repeat {repeat_number:02d} / "
            f"Fold {fold_number:02d} "
            "already COMPLETE -> SKIPPED"
        )


        return "skipped"


    # ========================================================
    # 7B. OUTER PARTITION
    #
    # Shared master 10 × 5 assignment is authoritative.
    # ========================================================

    partition = (
        make_hybrid_outer_partition(
            repeat_number=
                repeat_number,

            fold_number=
                fold_number,
        )
    )


    X_outer_train = (
        partition[
            "outer_training_features"
        ]
    )


    y_outer_train = (
        np.asarray(
            partition[
                "outer_training_labels"
            ],
            dtype=int,
        )
    )


    X_outer_validation = (
        partition[
            "outer_validation_features"
        ]
    )


    y_outer_validation = (
        np.asarray(
            partition[
                "outer_validation_labels"
            ],
            dtype=int,
        )
    )


    outer_validation_paths = np.asarray(
        partition[
            "outer_validation_paths"
        ],
        dtype=str,
    )


    # --------------------------------------------------------
    # Strict structural validation
    # --------------------------------------------------------

    assert X_outer_train.shape == (
        4480,
        2048,
    )


    assert X_outer_validation.shape == (
        1120,
        2048,
    )


    assert len(
        y_outer_train
    ) == 4480


    assert len(
        y_outer_validation
    ) == 1120


    assert len(
        outer_validation_paths
    ) == 1120


    assert (
        len(
            np.unique(
                outer_validation_paths
            )
        )
        == 1120
    )


    training_class_counts = (
        np.bincount(
            y_outer_train,
            minlength=4,
        )
    )


    validation_class_counts = (
        np.bincount(
            y_outer_validation,
            minlength=4,
        )
    )


    assert np.array_equal(
        training_class_counts,
        np.array(
            [
                1120,
                1120,
                1120,
                1120,
            ]
        ),
    )


    assert np.array_equal(
        validation_class_counts,
        np.array(
            [
                280,
                280,
                280,
                280,
            ]
        ),
    )


    print(
        "\n"
        + "=" * 88
    )


    print(
        "RESNET50 FIXED FEATURES + RF"
    )


    print(
        f"REPEAT {repeat_number:02d} / "
        f"FOLD {fold_number:02d}"
    )


    print(
        "=" * 88
    )


    print(
        "Outer training:",
        X_outer_train.shape,
    )


    print(
        "Outer validation:",
        X_outer_validation.shape,
    )


    print(
        "Split seed:",
        partition[
            "split_seed"
        ],
    )


    print(
        "Inner-CV seed:",
        get_hybrid_inner_cv_seed(
            repeat_number,
            fold_number,
        ),
    )


    print(
        "RF model seed:",
        get_hybrid_rf_model_seed(
            repeat_number,
            fold_number,
        ),
    )


    print(
        "RF search seed:",
        get_hybrid_rf_search_seed(
            repeat_number,
            fold_number,
        ),
    )


    # ========================================================
    # 7C. INNER SEARCH
    # ========================================================

    candidate_manifest_path = (
        paths[
            "candidate_manifest"
        ]
    )


    progress_path = (
        paths[
            "inner_fit_progress"
        ]
    )


    search_complete_path = (
        paths[
            "search_complete"
        ]
    )


    # --------------------------------------------------------
    # Search already fully completed
    # --------------------------------------------------------

    if search_complete_path.exists():

        with open(
            search_complete_path,
            "r",
            encoding="utf-8",
        ) as file:

            search_summary = json.load(
                file
            )


        assert (
            search_summary[
                "status"
            ]
            == "completed"
        )


        assert (
            int(
                search_summary[
                    "repeat"
                ]
            )
            == repeat_number
        )


        assert (
            int(
                search_summary[
                    "outer_fold"
                ]
            )
            == fold_number
        )


        print(
            "\nInner RF search already COMPLETE "
            "-> loaded from disk."
        )


    # --------------------------------------------------------
    # Search is new or partially complete
    # --------------------------------------------------------

    else:

        # ====================================================
        # Candidate manifest
        # ====================================================

        candidate_manifest_df = (
            get_or_create_resnet50_rf_candidate_manifest(
                repeat_number,
                fold_number,
                candidate_manifest_path,
            )
        )


        # ====================================================
        # Load resumable individual-fit progress
        # ====================================================

        progress_df = (
            load_resnet50_rf_inner_progress(
                progress_path
            )
        )


        # ----------------------------------------------------
        # Ensure checkpoints belong to THIS outer fold
        # ----------------------------------------------------

        if len(
            progress_df
        ) > 0:

            assert (
                progress_df[
                    "repeat"
                ]
                .eq(
                    repeat_number
                )
                .all()
            )


            assert (
                progress_df[
                    "outer_fold"
                ]
                .eq(
                    fold_number
                )
                .all()
            )


        # ====================================================
        # Fixed inner splits
        # ====================================================

        inner_cv = (
            make_checkpointed_resnet50_rf_inner_cv(
                repeat_number,
                fold_number,
            )
        )


        inner_splits = list(
            inner_cv.split(
                X_outer_train,
                y_outer_train,
            )
        )


        assert (
            len(
                inner_splits
            )
            == 3
        )


        # ----------------------------------------------------
        # Every stage starts with these active IDs, then the
        # stage winner list becomes the input to next stage.
        # ----------------------------------------------------

        active_candidate_ids = (
            candidate_manifest_df[
                "candidate_id"
            ]
            .astype(
                int
            )
            .tolist()
        )


        model_seed = (
            get_hybrid_rf_model_seed(
                repeat_number,
                fold_number,
            )
        )


        all_stage_results = []


        # ====================================================
        # FOUR SUCCESSIVE-HALVING STAGES
        # ====================================================

        for (
            stage_number,
            number_of_trees,
        ) in enumerate(
            RESNET50_RF_STAGE_RESOURCES,
            start=1,
        ):

            expected_candidates_this_stage = (
                RESNET50_RF_EXPECTED_STAGE_CANDIDATES[
                    stage_number
                    - 1
                ]
            )


            assert (
                len(
                    active_candidate_ids
                )
                == expected_candidates_this_stage
            ), (
                f"Unexpected candidate count entering "
                f"Stage {stage_number}. "
                f"Expected "
                f"{expected_candidates_this_stage}, "
                f"received "
                f"{len(active_candidate_ids)}."
            )


            print(
                "\n"
                + "-" * 88
            )


            print(
                f"STAGE {stage_number} / 4"
            )


            print(
                "-" * 88
            )


            print(
                "Trees:",
                number_of_trees,
            )


            print(
                "Candidates entering:",
                len(
                    active_candidate_ids
                ),
            )


            # =================================================
            # CANDIDATES
            # =================================================

            for (
                candidate_position,
                candidate_id,
            ) in enumerate(
                active_candidate_ids,
                start=1,
            ):

                candidate_row = (
                    candidate_manifest_df[
                        candidate_manifest_df[
                            "candidate_id"
                        ]
                        == int(
                            candidate_id
                        )
                    ]
                    .iloc[
                        0
                    ]
                )


                candidate_parameters = (
                    resnet50_rf_candidate_parameters_from_row(
                        candidate_row
                    )
                )


                # =============================================
                # THREE INNER FOLDS
                # =============================================

                for (
                    inner_fold_number,
                    (
                        inner_training_indices,
                        inner_validation_indices,
                    ),
                ) in enumerate(
                    inner_splits,
                    start=1,
                ):

                    # -----------------------------------------
                    # Resume check
                    # -----------------------------------------

                    already_complete = (
                        resnet50_rf_inner_fit_exists(
                            progress_df,
                            stage_number,
                            candidate_id,
                            inner_fold_number,
                        )
                    )


                    if already_complete:

                        print(
                            f"Stage {stage_number} | "
                            f"Candidate "
                            f"{candidate_position}/"
                            f"{len(active_candidate_ids)} | "
                            f"ID {candidate_id:03d} | "
                            f"Inner fold "
                            f"{inner_fold_number}/3 "
                            "-> SKIPPED"
                        )


                        continue


                    # -----------------------------------------
                    # Fresh RF for THIS inner fit
                    #
                    # This is equivalent to cloning a fixed-
                    # seed estimator for each CV fit.
                    # -----------------------------------------

                    model = (
                        RandomForestClassifier(

                            **candidate_parameters,

                            n_estimators=
                                int(
                                    number_of_trees
                                ),

                            random_state=
                                model_seed,

                            # No search-level parallelism now,
                            # so use available CPU cores inside
                            # this individual RF fit.
                            n_jobs=-1,
                        )
                    )


                    fit_start_time = (
                        time.perf_counter()
                    )


                    model.fit(

                        X_outer_train[
                            inner_training_indices
                        ],

                        y_outer_train[
                            inner_training_indices
                        ],
                    )


                    inner_predictions = (
                        model.predict(

                            X_outer_train[
                                inner_validation_indices
                            ]
                        )
                    )


                    fit_seconds = (
                        time.perf_counter()
                        - fit_start_time
                    )


                    inner_macro_f1 = float(
                        f1_score(

                            y_outer_train[
                                inner_validation_indices
                            ],

                            inner_predictions,

                            average="macro",
                        )
                    )


                    assert np.isfinite(
                        inner_macro_f1
                    )


                    # =========================================
                    # CHECKPOINT THIS INDIVIDUAL FIT NOW
                    # =========================================

                    progress_df = (
                        checkpoint_resnet50_rf_inner_fit(

                            progress_df,

                            {
                                "repeat":
                                    int(
                                        repeat_number
                                    ),

                                "outer_fold":
                                    int(
                                        fold_number
                                    ),

                                "stage":
                                    int(
                                        stage_number
                                    ),

                                "n_estimators":
                                    int(
                                        number_of_trees
                                    ),

                                "candidate_id":
                                    int(
                                        candidate_id
                                    ),

                                "inner_fold":
                                    int(
                                        inner_fold_number
                                    ),

                                "macro_f1":
                                    float(
                                        inner_macro_f1
                                    ),

                                "fit_seconds":
                                    float(
                                        fit_seconds
                                    ),
                            },

                            progress_path,
                        )
                    )


                    print(
                        f"Stage {stage_number} | "
                        f"Candidate "
                        f"{candidate_position}/"
                        f"{len(active_candidate_ids)} | "
                        f"ID {candidate_id:03d} | "
                        f"Inner fold "
                        f"{inner_fold_number}/3 | "
                        f"F1={inner_macro_f1:.6f} | "
                        f"{fit_seconds / 60:.2f} min | "
                        "CHECKPOINT SAVED"
                    )


                    del model
                    del inner_predictions

                    gc.collect()


            # =================================================
            # STAGE COMPLETE
            # =================================================

            stage_results_df = (
                build_resnet50_rf_stage_results(

                    progress_df,
                    candidate_manifest_df,
                    active_candidate_ids,

                    stage_number,
                    number_of_trees,
                )
            )


            # -------------------------------------------------
            # Save stage result
            # -------------------------------------------------

            stage_results_path = (
                search_progress_directory
                / (
                    f"stage_{stage_number:02d}"
                    "_results.csv"
                )
            )


            resnet50_rf_save_dataframe_atomic(
                stage_results_df,
                stage_results_path,
            )


            all_stage_results.append(
                stage_results_df.copy()
            )


            # -------------------------------------------------
            # Determine survivors
            # -------------------------------------------------

            if stage_number < 4:

                number_to_keep = (
                    math.ceil(
                        len(
                            active_candidate_ids
                        )
                        /
                        RESNET50_RF_HALVING_FACTOR
                    )
                )


            else:

                number_to_keep = 1


            selected_candidate_ids = (
                stage_results_df[
                    "candidate_id"
                ]
                .head(
                    number_to_keep
                )
                .astype(
                    int
                )
                .tolist()
            )


            selected_candidates_df = (
                stage_results_df[
                    stage_results_df[
                        "candidate_id"
                    ]
                    .isin(
                        selected_candidate_ids
                    )
                ]
                .copy()
            )


            selected_path = (
                search_progress_directory
                / (
                    f"stage_{stage_number:02d}"
                    "_selected_candidates.csv"
                )
            )


            resnet50_rf_save_dataframe_atomic(
                selected_candidates_df,
                selected_path,
            )


            print(
                "\nStage completed and saved."
            )


            print(
                "Best stage macro-F1:",
                round(
                    float(
                        stage_results_df[
                            "mean_test_score"
                        ]
                        .iloc[
                            0
                        ]
                    ),
                    6,
                ),
            )


            print(
                "Candidates advancing:",
                number_to_keep,
            )


            print(
                "Advancing IDs:",
                selected_candidate_ids,
            )


            active_candidate_ids = (
                selected_candidate_ids
            )


        # ====================================================
        # INNER SEARCH WINNER
        # ====================================================

        assert (
            len(
                all_stage_results
            )
            == 4
        )


        final_stage_results_df = (
            all_stage_results[
                -1
            ]
            .copy()
        )


        assert (
            len(
                final_stage_results_df
            )
            == 4
        )


        winner_row = (
            final_stage_results_df
            .iloc[
                0
            ]
        )


        winning_candidate_id = int(
            winner_row[
                "candidate_id"
            ]
        )


        winning_candidate_row = (
            candidate_manifest_df[
                candidate_manifest_df[
                    "candidate_id"
                ]
                == winning_candidate_id
            ]
            .iloc[
                0
            ]
        )


        winning_parameters = (
            resnet50_rf_candidate_parameters_from_row(
                winning_candidate_row
            )
        )


        best_inner_macro_f1 = float(
            winner_row[
                "mean_test_score"
            ]
        )


        selected_n_estimators = 675


        # ----------------------------------------------------
        # Save complete inner search results in the SAME final
        # filename used by the previous Hybrid RF runner.
        # ----------------------------------------------------

        complete_search_results_df = (
            pd.concat(
                all_stage_results,
                ignore_index=True,
            )
        )


        assert (
            len(
                complete_search_results_df
            )
            == (
                100
                + 34
                + 12
                + 4
            )
        )


        resnet50_rf_save_dataframe_atomic(

            complete_search_results_df,

            paths[
                "search_results"
            ],
        )


        # ----------------------------------------------------
        # Inner search complete marker
        # ----------------------------------------------------

        search_summary = {

            "status":
                "completed",

            "model":
                "ResNet50_fixed_features_RF",

            "repeat":
                int(
                    repeat_number
                ),

            "outer_fold":
                int(
                    fold_number
                ),

            "winning_candidate_id":
                int(
                    winning_candidate_id
                ),

            "winning_parameters":
                winning_parameters,

            "selected_n_estimators":
                int(
                    selected_n_estimators
                ),

            "best_inner_macro_f1":
                float(
                    best_inner_macro_f1
                ),

            "inner_cv_seed":
                int(
                    get_hybrid_inner_cv_seed(
                        repeat_number,
                        fold_number,
                    )
                ),

            "model_seed":
                int(
                    get_hybrid_rf_model_seed(
                        repeat_number,
                        fold_number,
                    )
                ),

            "search_seed":
                int(
                    get_hybrid_rf_search_seed(
                        repeat_number,
                        fold_number,
                    )
                ),

            "required_inner_fits":
                int(
                    (
                        100
                        + 34
                        + 12
                        + 4
                    )
                    * 3
                ),
        }


        # ----------------------------------------------------
        # Written only after all four stages and the combined
        # search result file exist.
        # ----------------------------------------------------

        resnet50_rf_save_json_atomic(
            search_summary,
            search_complete_path,
        )


        print(
            "\n"
            + "=" * 88
        )


        print(
            "INNER SEARCH COMPLETE AND CHECKPOINTED"
        )


        print(
            "=" * 88
        )


        print(
            "Winning candidate:",
            winning_candidate_id,
        )


        print(
            "Winning parameters:",
            winning_parameters,
        )


        print(
            "Selected trees:",
            selected_n_estimators,
        )


        print(
            "Best inner macro-F1:",
            round(
                best_inner_macro_f1,
                6,
            ),
        )


    # ========================================================
    # 7D. LOAD SAVED WINNER
    #
    # Works both immediately after completing the search and
    # when restarting from search_complete.json.
    # ========================================================

    winning_candidate_id = int(
        search_summary[
            "winning_candidate_id"
        ]
    )


    winning_parameters = (
        search_summary[
            "winning_parameters"
        ]
    )


    selected_n_estimators = int(
        search_summary[
            "selected_n_estimators"
        ]
    )


    best_inner_macro_f1 = float(
        search_summary[
            "best_inner_macro_f1"
        ]
    )


    assert (
        selected_n_estimators
        == 675
    )


    # ========================================================
    # 7E. FINAL REFIT
    #
    # ONLY AFTER INNER MODEL SELECTION.
    #
    # Fit the selected model on all 4,480 outer-training
    # samples.
    # ========================================================

    print(
        "\nRefitting winning RF on all "
        "4,480 outer-training samples..."
    )


    final_refit_start = (
        time.perf_counter()
    )


    final_model = (
        RandomForestClassifier(

            **winning_parameters,

            n_estimators=
                selected_n_estimators,

            random_state=
                get_hybrid_rf_model_seed(
                    repeat_number,
                    fold_number,
                ),

            n_jobs=-1,
        )
    )


    final_model.fit(
        X_outer_train,
        y_outer_train,
    )


    final_refit_seconds = (
        time.perf_counter()
        - final_refit_start
    )


    # ========================================================
    # 7F. OUTER VALIDATION — ONCE
    # ========================================================

    outer_prediction_start = (
        time.perf_counter()
    )


    outer_predictions = (
        final_model.predict(
            X_outer_validation
        )
    )


    outer_prediction_seconds = (
        time.perf_counter()
        - outer_prediction_start
    )


    outer_predictions = np.asarray(
        outer_predictions,
        dtype=int,
    )


    assert (
        len(
            outer_predictions
        )
        == 1120
    )


    assert set(
        np.unique(
            outer_predictions
        )
    ).issubset(
        {
            0,
            1,
            2,
            3,
        }
    )


    # ========================================================
    # 7G. OUTER METRICS
    # ========================================================

    outer_accuracy = float(
        accuracy_score(
            y_outer_validation,
            outer_predictions,
        )
    )


    outer_balanced_accuracy = float(
        balanced_accuracy_score(
            y_outer_validation,
            outer_predictions,
        )
    )


    outer_macro_precision = float(
        precision_score(
            y_outer_validation,
            outer_predictions,
            average="macro",
            zero_division=0,
        )
    )


    outer_macro_recall = float(
        recall_score(
            y_outer_validation,
            outer_predictions,
            average="macro",
            zero_division=0,
        )
    )


    outer_macro_f1 = float(
        f1_score(
            y_outer_validation,
            outer_predictions,
            average="macro",
        )
    )


    outer_confusion_matrix = (
        confusion_matrix(
            y_outer_validation,
            outer_predictions,
            labels=[
                0,
                1,
                2,
                3,
            ],
        )
    )


    outer_classification_report = (
        classification_report(
            y_outer_validation,
            outer_predictions,
            labels=[
                0,
                1,
                2,
                3,
            ],
            target_names=
                CLASS_NAMES,
            output_dict=True,
            zero_division=0,
        )
    )


    # ========================================================
    # 7H. PREDICTIONS TABLE
    # ========================================================

    predictions_df = pd.DataFrame(
        {
            "relative_path":
                outer_validation_paths,

            "true_label":
                y_outer_validation,

            "predicted_label":
                outer_predictions,
        }
    )


    predictions_df[
        "true_class"
    ] = (
        predictions_df[
            "true_label"
        ]
        .map(
            INDEX_TO_CLASS
        )
    )


    predictions_df[
        "predicted_class"
    ] = (
        predictions_df[
            "predicted_label"
        ]
        .map(
            INDEX_TO_CLASS
        )
    )


    assert (
        len(
            predictions_df
        )
        == 1120
    )


    assert (
        predictions_df[
            "relative_path"
        ]
        .nunique()
        == 1120
    )


    assert (
        predictions_df[
            "true_class"
        ]
        .notna()
        .all()
    )


    assert (
        predictions_df[
            "predicted_class"
        ]
        .notna()
        .all()
    )


    # ========================================================
    # 7I. TOTAL INNER FIT TIME FROM CHECKPOINTS
    # ========================================================

    saved_progress_df = (
        pd.read_csv(
            progress_path
        )
    )


    cumulative_inner_fit_seconds = float(
        saved_progress_df[
            "fit_seconds"
        ]
        .sum()
    )


    # ========================================================
    # 7J. SELECTED PARAMETERS
    #
    # Final schema intentionally remains compatible with the
    # previous ResNet50 + RF Hybrid output.
    # ========================================================

    selected_parameters = {

        "model":
            "ResNet50_fixed_features_RF",

        "feature_dimension":
            2048,

        "repeat":
            int(
                repeat_number
            ),

        "fold":
            int(
                fold_number
            ),

        "outer_split_seed":
            int(
                partition[
                    "split_seed"
                ]
            ),

        "inner_cv_seed":
            int(
                get_hybrid_inner_cv_seed(
                    repeat_number,
                    fold_number,
                )
            ),

        "rf_model_seed":
            int(
                get_hybrid_rf_model_seed(
                    repeat_number,
                    fold_number,
                )
            ),

        "rf_search_seed":
            int(
                get_hybrid_rf_search_seed(
                    repeat_number,
                    fold_number,
                )
            ),

        "inner_cv_folds":
            3,

        "selection_metric":
            "f1_macro",

        "search_method":
            "manually_checkpointed_successive_halving",

        "initial_candidates":
            100,

        "halving_factor":
            3,

        "resource":
            "n_estimators",

        "tree_resources":
            [
                25,
                75,
                225,
                675,
            ],

        "candidate_counts_by_iteration":
            {
                "0": 100,
                "1": 34,
                "2": 12,
                "3": 4,
            },

        "winning_candidate_id":
            int(
                winning_candidate_id
            ),

        "selected_n_estimators":
            int(
                selected_n_estimators
            ),

        "best_inner_macro_f1":
            float(
                best_inner_macro_f1
            ),

        "best_parameters":
            winning_parameters,
    }


    # ========================================================
    # 7K. OUTER METRICS
    # ========================================================

    outer_metrics = {

        "model":
            "ResNet50_fixed_features_RF",

        "feature_dimension":
            2048,

        "repeat":
            int(
                repeat_number
            ),

        "fold":
            int(
                fold_number
            ),

        "outer_split_seed":
            int(
                partition[
                    "split_seed"
                ]
            ),

        "inner_cv_seed":
            int(
                get_hybrid_inner_cv_seed(
                    repeat_number,
                    fold_number,
                )
            ),

        "rf_model_seed":
            int(
                get_hybrid_rf_model_seed(
                    repeat_number,
                    fold_number,
                )
            ),

        "rf_search_seed":
            int(
                get_hybrid_rf_search_seed(
                    repeat_number,
                    fold_number,
                )
            ),

        "outer_training_samples":
            4480,

        "outer_validation_samples":
            1120,

        "winning_candidate_id":
            int(
                winning_candidate_id
            ),

        "selected_n_estimators":
            int(
                selected_n_estimators
            ),

        "best_inner_macro_f1":
            float(
                best_inner_macro_f1
            ),

        "accuracy":
            float(
                outer_accuracy
            ),

        "balanced_accuracy":
            float(
                outer_balanced_accuracy
            ),

        "macro_precision":
            float(
                outer_macro_precision
            ),

        "macro_recall":
            float(
                outer_macro_recall
            ),

        "macro_f1":
            float(
                outer_macro_f1
            ),

        "confusion_matrix":
            outer_confusion_matrix.tolist(),

        "classification_report":
            outer_classification_report,

        "cumulative_inner_fit_seconds":
            float(
                cumulative_inner_fit_seconds
            ),

        "final_refit_seconds":
            float(
                final_refit_seconds
            ),

        "prediction_seconds":
            float(
                outer_prediction_seconds
            ),
    }


    # ========================================================
    # 7L. SAVE FINAL SUBSTANTIVE OUTPUTS
    #
    # inner_search_results.csv was already saved when the
    # inner search completed.
    # ========================================================

    assert (
        paths[
            "search_results"
        ]
        .exists()
    )


    resnet50_rf_save_json_atomic(
        selected_parameters,
        paths[
            "selected_parameters"
        ],
    )


    resnet50_rf_save_dataframe_atomic(
        predictions_df,
        paths[
            "outer_predictions"
        ],
    )


    resnet50_rf_save_json_atomic(
        outer_metrics,
        paths[
            "outer_metrics"
        ],
    )


    # ========================================================
    # 7M. READ EVERYTHING BACK BEFORE COMPLETION
    # ========================================================

    saved_search_results = (
        pd.read_csv(
            paths[
                "search_results"
            ]
        )
    )


    saved_predictions = (
        pd.read_csv(
            paths[
                "outer_predictions"
            ]
        )
    )


    with open(
        paths[
            "selected_parameters"
        ],
        "r",
        encoding="utf-8",
    ) as file:

        saved_selected_parameters = (
            json.load(
                file
            )
        )


    with open(
        paths[
            "outer_metrics"
        ],
        "r",
        encoding="utf-8",
    ) as file:

        saved_metrics = (
            json.load(
                file
            )
        )


    assert (
        len(
            saved_search_results
        )
        == 150
    )


    assert (
        sorted(
            saved_search_results[
                "n_resources"
            ]
            .astype(
                int
            )
            .unique()
            .tolist()
        )
        == [
            25,
            75,
            225,
            675,
        ]
    )


    assert (
        (
            saved_search_results[
                "iter"
            ]
            .astype(
                int
            )
            == 0
        )
        .sum()
        == 100
    )


    assert (
        (
            saved_search_results[
                "iter"
            ]
            .astype(
                int
            )
            == 1
        )
        .sum()
        == 34
    )


    assert (
        (
            saved_search_results[
                "iter"
            ]
            .astype(
                int
            )
            == 2
        )
        .sum()
        == 12
    )


    assert (
        (
            saved_search_results[
                "iter"
            ]
            .astype(
                int
            )
            == 3
        )
        .sum()
        == 4
    )


    assert (
        len(
            saved_predictions
        )
        == 1120
    )


    assert (
        saved_predictions[
            "relative_path"
        ]
        .nunique()
        == 1120
    )


    assert (
        int(
            saved_selected_parameters[
                "repeat"
            ]
        )
        == repeat_number
    )


    assert (
        int(
            saved_selected_parameters[
                "fold"
            ]
        )
        == fold_number
    )


    assert (
        int(
            saved_metrics[
                "repeat"
            ]
        )
        == repeat_number
    )


    assert (
        int(
            saved_metrics[
                "fold"
            ]
        )
        == fold_number
    )


    assert (
        int(
            saved_metrics[
                "outer_training_samples"
            ]
        )
        == 4480
    )


    assert (
        int(
            saved_metrics[
                "outer_validation_samples"
            ]
        )
        == 1120
    )


    assert np.isclose(
        float(
            saved_metrics[
                "macro_f1"
            ]
        ),
        outer_macro_f1,
        rtol=0.0,
        atol=1e-12,
    )


    # ========================================================
    # 7N. COMPLETED.JSON — MUST BE LAST
    # ========================================================

    completion_information = {

        "status":
            "completed",

        "model":
            "ResNet50_fixed_features_RF",

        "repeat":
            int(
                repeat_number
            ),

        "fold":
            int(
                fold_number
            ),

        "outer_split_seed":
            int(
                partition[
                    "split_seed"
                ]
            ),

        "inner_cv_seed":
            int(
                get_hybrid_inner_cv_seed(
                    repeat_number,
                    fold_number,
                )
            ),

        "rf_model_seed":
            int(
                get_hybrid_rf_model_seed(
                    repeat_number,
                    fold_number,
                )
            ),

        "rf_search_seed":
            int(
                get_hybrid_rf_search_seed(
                    repeat_number,
                    fold_number,
                )
            ),

        "inner_search_completed":
            True,

        "outer_evaluation_completed":
            True,

        "required_outputs_verified":
            True,
    }


    resnet50_rf_save_json_atomic(
        completion_information,
        paths[
            "completion_marker"
        ],
    )


    # ========================================================
    # 7O. FINAL COMPLETION VALIDATION
    # ========================================================

    assert (
        is_checkpointed_resnet50_rf_fold_complete(
            repeat_number,
            fold_number,
        )
    ), (
        "Completed ResNet50 + RF fold failed "
        "final validation."
    )


    print(
        "\n"
        + "=" * 88
    )


    print(
        f"RESNET50 + RF — REPEAT "
        f"{repeat_number:02d} / "
        f"FOLD {fold_number:02d} COMPLETE"
    )


    print(
        "=" * 88
    )


    print(
        "Winning candidate:",
        winning_candidate_id,
    )


    print(
        "Best inner macro-F1:",
        round(
            best_inner_macro_f1,
            6,
        ),
    )


    print(
        "Outer accuracy:",
        round(
            outer_accuracy,
            6,
        ),
    )


    print(
        "Outer balanced accuracy:",
        round(
            outer_balanced_accuracy,
            6,
        ),
    )


    print(
        "Outer macro precision:",
        round(
            outer_macro_precision,
            6,
        ),
    )


    print(
        "Outer macro recall:",
        round(
            outer_macro_recall,
            6,
        ),
    )


    print(
        "Outer macro F1:",
        round(
            outer_macro_f1,
            6,
        ),
    )


    print(
        "Accumulated inner-fit time:",
        round(
            cumulative_inner_fit_seconds
            / 60,
            2,
        ),
        "minutes",
    )


    print(
        "Final refit time:",
        round(
            final_refit_seconds
            / 60,
            2,
        ),
        "minutes",
    )


    print(
        "COMPLETED.json written LAST."
    )


    # --------------------------------------------------------
    # Cleanup
    # --------------------------------------------------------

    del final_model
    del outer_predictions

    del X_outer_train
    del y_outer_train

    del X_outer_validation
    del y_outer_validation

    del partition

    gc.collect()


    return "completed"


# ============================================================
# 8. REFRESH CONSOLIDATED RF SUMMARIES
#
# Uses only fully completed folds.
# ============================================================

def refresh_checkpointed_resnet50_rf_summaries():

    fold_records = []


    for repeat_number in range(
        1,
        11,
    ):

        for fold_number in range(
            1,
            6,
        ):

            if not (
                is_checkpointed_resnet50_rf_fold_complete(
                    repeat_number,
                    fold_number,
                )
            ):

                continue


            paths = (
                get_checkpointed_resnet50_rf_fold_paths(
                    repeat_number,
                    fold_number,
                )
            )


            with open(
                paths[
                    "outer_metrics"
                ],
                "r",
                encoding="utf-8",
            ) as file:

                metrics = json.load(
                    file
                )


            fold_records.append(
                {
                    "repeat":
                        int(
                            repeat_number
                        ),

                    "fold":
                        int(
                            fold_number
                        ),

                    "accuracy":
                        float(
                            metrics[
                                "accuracy"
                            ]
                        ),

                    "balanced_accuracy":
                        float(
                            metrics[
                                "balanced_accuracy"
                            ]
                        ),

                    "macro_precision":
                        float(
                            metrics[
                                "macro_precision"
                            ]
                        ),

                    "macro_recall":
                        float(
                            metrics[
                                "macro_recall"
                            ]
                        ),

                    "macro_f1":
                        float(
                            metrics[
                                "macro_f1"
                            ]
                        ),

                    "best_inner_macro_f1":
                        float(
                            metrics[
                                "best_inner_macro_f1"
                            ]
                        ),
                }
            )


    all_fold_results_df = pd.DataFrame(
        fold_records
    )


    if len(
        all_fold_results_df
    ) > 0:

        all_fold_results_df = (
            all_fold_results_df
            .sort_values(
                [
                    "repeat",
                    "fold",
                ]
            )
            .reset_index(
                drop=True
            )
        )


        resnet50_rf_save_dataframe_atomic(

            all_fold_results_df,

            RESNET50_RF_RESULTS_ROOT
            / "all_fold_results.csv",
        )


    # --------------------------------------------------------
    # Repeat-level summary only when all five folds exist
    # --------------------------------------------------------

    repeat_records = []


    if len(
        all_fold_results_df
    ) > 0:

        for repeat_number in range(
            1,
            11,
        ):

            repeat_df = (
                all_fold_results_df[
                    all_fold_results_df[
                        "repeat"
                    ]
                    == repeat_number
                ]
                .copy()
            )


            if len(
                repeat_df
            ) != 5:

                continue


            repeat_records.append(
                {
                    "repeat":
                        int(
                            repeat_number
                        ),

                    "mean_accuracy":
                        float(
                            repeat_df[
                                "accuracy"
                            ]
                            .mean()
                        ),

                    "mean_balanced_accuracy":
                        float(
                            repeat_df[
                                "balanced_accuracy"
                            ]
                            .mean()
                        ),

                    "mean_macro_precision":
                        float(
                            repeat_df[
                                "macro_precision"
                            ]
                            .mean()
                        ),

                    "mean_macro_recall":
                        float(
                            repeat_df[
                                "macro_recall"
                            ]
                            .mean()
                        ),

                    "mean_macro_f1":
                        float(
                            repeat_df[
                                "macro_f1"
                            ]
                            .mean()
                        ),

                    "sd_macro_f1":
                        float(
                            repeat_df[
                                "macro_f1"
                            ]
                            .std(
                                ddof=1
                            )
                        ),

                    "wilcoxon_value":
                        float(
                            repeat_df[
                                "macro_f1"
                            ]
                            .mean()
                        ),
                }
            )


    repeat_summary_df = pd.DataFrame(
        repeat_records
    )


    if len(
        repeat_summary_df
    ) > 0:

        repeat_summary_df = (
            repeat_summary_df
            .sort_values(
                "repeat"
            )
            .reset_index(
                drop=True
            )
        )


        resnet50_rf_save_dataframe_atomic(

            repeat_summary_df,

            RESNET50_RF_RESULTS_ROOT
            / "repeat_level_summary.csv",
        )


    return (
        all_fold_results_df,
        repeat_summary_df,
    )


# ============================================================
# 9. RUN ALL 10 REPEATS × 5 OUTER FOLDS
# ============================================================

newly_completed_folds = 0

previously_completed_folds = 0


master_start_time = (
    time.perf_counter()
)


for repeat_number in range(
    1,
    11,
):

    print(
        "\n"
        + "#" * 88
    )


    print(
        f"STARTING REPEAT "
        f"{repeat_number} / 10"
    )


    print(
        "#" * 88
    )


    for fold_number in range(
        1,
        6,
    ):

        fold_status = (
            run_checkpointed_resnet50_rf_outer_fold(
                repeat_number,
                fold_number,
            )
        )


        if (
            fold_status
            == "completed"
        ):

            newly_completed_folds += 1


        elif (
            fold_status
            == "skipped"
        ):

            previously_completed_folds += 1


        # ----------------------------------------------------
        # Update persistent global summaries after every fold
        # ----------------------------------------------------

        (
            current_fold_results,
            current_repeat_summary,
        ) = (
            refresh_checkpointed_resnet50_rf_summaries()
        )


        print(
            "\nCURRENT RESNET50 + RF PROGRESS:",
            len(
                current_fold_results
            ),
            "/ 50 outer folds complete",
        )


        print(
            "Completed full repeats:",
            len(
                current_repeat_summary
            ),
            "/ 10",
        )


# ============================================================
# 10. FINAL SUMMARY
# ============================================================

(
    final_rf_fold_results,
    final_rf_repeat_summary,
) = (
    refresh_checkpointed_resnet50_rf_summaries()
)


master_elapsed_seconds = (
    time.perf_counter()
    - master_start_time
)


print(
    "\n"
    + "=" * 88
)


print(
    "RESNET50 FIXED-FEATURE + RF MASTER RUN FINISHED"
)


print(
    "=" * 88
)


print(
    "Completed outer folds:",
    len(
        final_rf_fold_results
    ),
    "/ 50",
)


print(
    "Completed full repeats:",
    len(
        final_rf_repeat_summary
    ),
    "/ 10",
)


print(
    "New outer folds completed this session:",
    newly_completed_folds,
)


print(
    "Previously completed outer folds skipped:",
    previously_completed_folds,
)


print(
    "Current-session elapsed time:",
    round(
        master_elapsed_seconds
        / 60,
        2,
    ),
    "minutes",
)


print(
    "\nResults root:"
)


print(
    RESNET50_RF_RESULTS_ROOT
)


if (
    len(
        final_rf_fold_results
    )
    == 50
):

    assert (
        len(
            final_rf_repeat_summary
        )
        == 10
    )


    print(
        "\nALL 50 RESNET50 + RF OUTER FOLDS "
        "ARE COMPLETE."
    )


    print(
        "\nFold-level summary:"
    )


    print(
        RESNET50_RF_RESULTS_ROOT
        / "all_fold_results.csv"
    )


    print(
        "\nRepeat-level summary:"
    )


    print(
        RESNET50_RF_RESULTS_ROOT
        / "repeat_level_summary.csv"
    )


else:

    print(
        "\nThe experiment stopped before all "
        "50 outer folds completed."
    )


    print(
        "Rerun THIS SAME CELL after reconnecting."
    )


    print(
        "Completed outer folds will be skipped."
    )


    print(
        "Completed inner RF fits in the current "
        "incomplete fold will also be skipped."
    )


print(
    "\nTesting partition was NEVER accessed."
)


print(
    "\nRESNET50 + RF CHECKPOINTED MASTER RUNNER: PASSED"
)

########################################################################################
STARTING REPEAT 1 / 10
########################################################################################

Repeat 01 / Fold 01 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 01 / Fold 02 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 01 / Fold 03 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 01 / Fold 04 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 01 / Fold 05 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

########################################################################################
STARTING REPEAT 2 / 10
########################################################################################

Repeat 02 / Fold 01 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 02 / Fold 02 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 02 / Fold 03 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 02 / Fold 04 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 02 / Fold 05 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

########################################################################################
STARTING REPEAT 3 / 10
########################################################################################

Repeat 03 / Fold 01 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 03 / Fold 02 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 03 / Fold 03 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 03 / Fold 04 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 03 / Fold 05 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

########################################################################################
STARTING REPEAT 4 / 10
########################################################################################

Repeat 04 / Fold 01 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 04 / Fold 02 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 04 / Fold 03 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 04 / Fold 04 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 04 / Fold 05 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

########################################################################################
STARTING REPEAT 5 / 10
########################################################################################

Repeat 05 / Fold 01 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 05 / Fold 02 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 05 / Fold 03 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 05 / Fold 04 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 05 / Fold 05 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

########################################################################################
STARTING REPEAT 6 / 10
########################################################################################

Repeat 06 / Fold 01 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 06 / Fold 02 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 06 / Fold 03 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 06 / Fold 04 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 06 / Fold 05 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

########################################################################################
STARTING REPEAT 7 / 10
########################################################################################

Repeat 07 / Fold 01 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 07 / Fold 02 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 07 / Fold 03 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 07 / Fold 04 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 07 / Fold 05 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

########################################################################################
STARTING REPEAT 8 / 10
########################################################################################

Repeat 08 / Fold 01 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 08 / Fold 02 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 08 / Fold 03 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 08 / Fold 04 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 08 / Fold 05 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

########################################################################################
STARTING REPEAT 9 / 10
########################################################################################

Repeat 09 / Fold 01 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 09 / Fold 02 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 09 / Fold 03 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 09 / Fold 04 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 09 / Fold 05 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

########################################################################################
STARTING REPEAT 10 / 10
########################################################################################

Repeat 10 / Fold 01 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

Repeat 10 / Fold 02 already COMPLETE -> SKIPPED

CURRENT RESNET50 + RF PROGRESS: 47 / 50 outer folds complete
Completed full repeats: 9 / 10

========================================================================================
RESNET50 FIXED FEATURES + RF
REPEAT 10 / FOLD 03
========================================================================================
Outer training: (4480, 2048)
Outer validation: (1120, 2048)
Split seed: 202610
Inner-CV seed: 304003
RF model seed: 405003
RF search seed: 415003
Loaded existing candidate manifest.
Loaded existing checkpoint progress: 445 completed inner fits

----------------------------------------------------------------------------------------
STAGE 1 / 4
----------------------------------------------------------------------------------------
Trees: 25
Candidates entering: 100
Stage 1 | Candidate 1/100 | ID 001 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 1/100 | ID 001 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 1/100 | ID 001 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 2/100 | ID 002 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 2/100 | ID 002 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 2/100 | ID 002 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 3/100 | ID 003 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 3/100 | ID 003 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 3/100 | ID 003 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 4/100 | ID 004 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 4/100 | ID 004 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 4/100 | ID 004 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 5/100 | ID 005 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 5/100 | ID 005 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 5/100 | ID 005 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 6/100 | ID 006 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 6/100 | ID 006 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 6/100 | ID 006 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 7/100 | ID 007 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 7/100 | ID 007 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 7/100 | ID 007 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 8/100 | ID 008 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 8/100 | ID 008 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 8/100 | ID 008 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 9/100 | ID 009 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 9/100 | ID 009 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 9/100 | ID 009 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 10/100 | ID 010 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 10/100 | ID 010 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 10/100 | ID 010 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 11/100 | ID 011 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 11/100 | ID 011 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 11/100 | ID 011 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 12/100 | ID 012 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 12/100 | ID 012 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 12/100 | ID 012 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 13/100 | ID 013 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 13/100 | ID 013 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 13/100 | ID 013 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 14/100 | ID 014 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 14/100 | ID 014 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 14/100 | ID 014 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 15/100 | ID 015 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 15/100 | ID 015 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 15/100 | ID 015 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 16/100 | ID 016 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 16/100 | ID 016 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 16/100 | ID 016 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 17/100 | ID 017 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 17/100 | ID 017 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 17/100 | ID 017 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 18/100 | ID 018 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 18/100 | ID 018 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 18/100 | ID 018 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 19/100 | ID 019 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 19/100 | ID 019 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 19/100 | ID 019 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 20/100 | ID 020 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 20/100 | ID 020 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 20/100 | ID 020 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 21/100 | ID 021 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 21/100 | ID 021 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 21/100 | ID 021 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 22/100 | ID 022 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 22/100 | ID 022 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 22/100 | ID 022 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 23/100 | ID 023 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 23/100 | ID 023 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 23/100 | ID 023 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 24/100 | ID 024 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 24/100 | ID 024 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 24/100 | ID 024 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 25/100 | ID 025 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 25/100 | ID 025 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 25/100 | ID 025 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 26/100 | ID 026 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 26/100 | ID 026 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 26/100 | ID 026 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 27/100 | ID 027 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 27/100 | ID 027 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 27/100 | ID 027 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 28/100 | ID 028 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 28/100 | ID 028 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 28/100 | ID 028 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 29/100 | ID 029 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 29/100 | ID 029 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 29/100 | ID 029 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 30/100 | ID 030 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 30/100 | ID 030 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 30/100 | ID 030 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 31/100 | ID 031 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 31/100 | ID 031 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 31/100 | ID 031 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 32/100 | ID 032 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 32/100 | ID 032 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 32/100 | ID 032 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 33/100 | ID 033 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 33/100 | ID 033 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 33/100 | ID 033 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 34/100 | ID 034 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 34/100 | ID 034 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 34/100 | ID 034 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 35/100 | ID 035 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 35/100 | ID 035 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 35/100 | ID 035 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 36/100 | ID 036 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 36/100 | ID 036 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 36/100 | ID 036 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 37/100 | ID 037 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 37/100 | ID 037 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 37/100 | ID 037 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 38/100 | ID 038 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 38/100 | ID 038 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 38/100 | ID 038 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 39/100 | ID 039 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 39/100 | ID 039 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 39/100 | ID 039 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 40/100 | ID 040 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 40/100 | ID 040 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 40/100 | ID 040 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 41/100 | ID 041 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 41/100 | ID 041 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 41/100 | ID 041 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 42/100 | ID 042 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 42/100 | ID 042 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 42/100 | ID 042 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 43/100 | ID 043 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 43/100 | ID 043 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 43/100 | ID 043 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 44/100 | ID 044 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 44/100 | ID 044 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 44/100 | ID 044 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 45/100 | ID 045 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 45/100 | ID 045 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 45/100 | ID 045 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 46/100 | ID 046 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 46/100 | ID 046 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 46/100 | ID 046 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 47/100 | ID 047 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 47/100 | ID 047 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 47/100 | ID 047 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 48/100 | ID 048 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 48/100 | ID 048 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 48/100 | ID 048 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 49/100 | ID 049 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 49/100 | ID 049 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 49/100 | ID 049 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 50/100 | ID 050 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 50/100 | ID 050 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 50/100 | ID 050 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 51/100 | ID 051 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 51/100 | ID 051 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 51/100 | ID 051 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 52/100 | ID 052 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 52/100 | ID 052 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 52/100 | ID 052 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 53/100 | ID 053 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 53/100 | ID 053 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 53/100 | ID 053 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 54/100 | ID 054 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 54/100 | ID 054 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 54/100 | ID 054 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 55/100 | ID 055 | Inner fold 1/3 -> SKIPPED
Stage 1 | Candidate 55/100 | ID 055 | Inner fold 2/3 -> SKIPPED
Stage 1 | Candidate 55/100 | ID 055 | Inner fold 3/3 -> SKIPPED
Stage 1 | Candidate 56/100 | ID 056 | Inner fold 1/3 -> SKIPPED

In [ ]:
# ============================================================
# HYBRID EXPERIMENT SETUP AND REPRODUCIBILITY
# ============================================================

import os
import random
import numpy as np
import pandas as pd
import tensorflow as tf
import time


# ============================================================
# Reproducibility
# ============================================================


# Set the seed for random number
RANDOM_SEED = 42

# Making experiment runs reproducible
os.environ["PYTHONHASHSEED"] = str(RANDOM_SEED)
random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)
tf.random.set_seed(RANDOM_SEED)

# Making determenistic TesnsorFlow operations where supported
try:
  tf.config.experimental.enable_op_determinism()
  determinism_status = "enabled"

except Exception as error:
  determinism_status = ("requested but TensorFlow returned:" f" {error}")

# Keep TensorFlow/Keras calculations in float 32
tf.keras.backend.set_floatx("float32")


# ============================================================
# 2. Fixed experiment configuration
# ============================================================

IMAGE_HEIGHT = 224
IMAGE_WIDTH = 224
IMAGE_CHANNELS = 3

NUMBER_OF_CLASSES = 4

CLASS_NAMES = ["glioma", "meningioma", "notumor", "pituitary"]

CLASS_TO_INDEX = {
    class_name: index
    for index, class_name in enumerate(CLASS_NAMES)
}

INDEX_TO_CLASS = {
    index: class_name
    for index, class_name in enumerate(CLASS_NAMES)
}


# ============================================================
# 3. Verify experiment configuration
# ============================================================

print("=" * 70)
print("HYBRID EXPERIMENT SETUP")
print("=" * 70)
print("Random seed:", RANDOM_SEED)
print("Deterministic TensorFlow operations:", determinism_status)
print("Keras float type:", tf.keras.backend.floatx())
print("Input shape:", (IMAGE_HEIGHT, IMAGE_WIDTH, IMAGE_CHANNELS))
print("Number of classes:", NUMBER_OF_CLASSES)
print("Class mapping:", CLASS_TO_INDEX)

======================================================================
HYBRID EXPERIMENT SETUP
======================================================================
Random seed: 42
Deterministic TensorFlow operations: enabled
Keras float type: float32
Input shape: (224, 224, 3)
Number of classes: 4
Class mapping: {'glioma': 0, 'meningioma': 1, 'notumor': 2, 'pituitary': 3}

In [ ]:
# ============================================================
# LOAD AND VALIDATE THE FIXED FIVE-FOLD ASSIGNMENTS
# ============================================================

import pandas as pd

# Load the fixed five-fold Training assignments
assignments = pd.read_csv(FOLDS_FILE)


# ============================================================
# 1. Validate the table structure
# ============================================================

# Define the columns that must exist in the fold-assignment file
required_columns = {"relative_path", "class", "fold"}


# Find any required columns that are missing
missing_columns = (required_columns - set(assignments.columns))


# Stop if any required column is missing
if missing_columns:
    raise ValueError("The fold file is missing columns: "f"{sorted(missing_columns)}")



# ============================================================
# 2. Create class indices and complete image paths
# ============================================================

# Assign the fixed numeric class index to every Training image
assignments["class_index"] = (assignments["class"].map(CLASS_TO_INDEX))


# Create the complete path to every Training image
assignments["image_path"] = (assignments["relative_path"].apply(
        lambda path:
        DATA_DIR
        / Path(path)))


# ============================================================
# 3. Validate paths and assignments
# ============================================================

# Find any Training images that do not exist
missing_image_paths = [
    image_path
    for image_path
    in assignments["image_path"]
    if not image_path.exists()
]


# Find any class names that do not belong to the four expected classes
unexpected_classes = sorted(set(assignments["class"]) - set(CLASS_NAMES))


# Find any fold values outside the fixed folds 1 to 5
unexpected_folds = sorted(set(assignments["fold"]) - {1, 2, 3, 4, 5})


# Count duplicate Training image paths
duplicate_paths = (assignments["relative_path"].duplicated().sum())


# Count missing values in the required columns
missing_values = (
    assignments[["relative_path", "class", "fold"]].isna().sum())


# Check whether any class failed to receive a numeric class index
missing_class_indices = (assignments["class_index"].isna().sum())


# ============================================================
# 4. Verify the fixed fold distribution
# ============================================================

# Count how many images from every class belong to each outer fold
fold_distribution = pd.crosstab(assignments["fold"], assignments["class"])


# Put the class columns into the fixed project class order
fold_distribution = (fold_distribution.reindex(
        columns=CLASS_NAMES,
        fill_value=0))


# Add the total number of images in each fold
fold_distribution["total"] = (fold_distribution.sum(axis=1))


# Each of the five fixed folds must contain 280 images from every class
expected_fold_distribution = pd.DataFrame(
    {
        class_name: [280] * 5
        for class_name in CLASS_NAMES
    },
    index=[1, 2, 3, 4, 5])


expected_fold_distribution["total"] = 1120


# ============================================================
# 5. Display the validation results
# ============================================================

print("=" * 70)
print("FIXED FIVE-FOLD ASSIGNMENT VALIDATION")
print("=" * 70)
print("Rows:", len(assignments))
print("Columns:", assignments.columns.tolist())
print("\n--- Assignment checks ---")
print("Duplicate relative paths:", duplicate_paths)
print("Missing image files:", len(missing_image_paths))
print("Unexpected classes:", unexpected_classes)
print("Unexpected fold values:", unexpected_folds)
print("Missing class indices:", missing_class_indices)
print("\nMissing values:")
print(missing_values)
print("\n--- Images per fold and class ---")
display(fold_distribution)
print("\n--- Sample records ---")
display(
    assignments[["relative_path", "class", "class_index", "fold", "image_path"]].head())


# ============================================================
# 6. Stop if any validation check failed
# ============================================================

# The fold file must contain exactly 5,600 Training images
if len(assignments) != 5600:
    raise ValueError("Expected 5,600 Training images, "f"but found {len(assignments)}.")


# Every Training image path must be unique
if duplicate_paths != 0:
    raise ValueError("Duplicate paths were found in the fold file.")


# Every Training image listed in the CSV must exist
if missing_image_paths:
    raise FileNotFoundError(f"{len(missing_image_paths)} Training image files are missing.")


# Only the expected four classes are allowed
if unexpected_classes:
    raise ValueError(f"Unexpected classes found: {unexpected_classes}")


# Only folds 1 to 5 are allowed
if unexpected_folds:
    raise ValueError(f"Unexpected fold values found: {unexpected_folds}")


# Required columns must not contain missing values
if missing_values.sum() != 0:
    raise ValueError("Missing values were found in the fold file.")


# Every class must map successfully to its fixed numeric index
if missing_class_indices != 0:
    raise ValueError(
        "One or more Training classes could not be mapped to a class index.")


# Verify the exact fixed five-fold class distribution
if not fold_distribution.equals(expected_fold_distribution):
    raise ValueError(
        "The fixed five-fold class distribution does not match the expected "
        "280 images per class and 1,120 images per fold.")

print("\nFixed five-fold assignment validation passed.")

======================================================================
FIXED FIVE-FOLD ASSIGNMENT VALIDATION
======================================================================
Rows: 5600
Columns: ['relative_path', 'class', 'fold', 'class_index', 'image_path']

--- Assignment checks ---
Duplicate relative paths: 0
Missing image files: 0
Unexpected classes: []
Unexpected fold values: []
Missing class indices: 0

Missing values:
relative_path    0
class            0
fold             0
dtype: int64

--- Images per fold and class ---

class  glioma  meningioma  notumor  pituitary  total
fold
1         280         280      280        280   1120
2         280         280      280        280   1120
3         280         280      280        280   1120
4         280         280      280        280   1120
5         280         280      280        280   1120

--- Sample records ---

,relative_path,class,class_index,fold,image_path
0,Training/glioma/Tr-gl_100.png,glioma,0,1,/content/brain-tumour-mri-classification/proce...
1,Training/glioma/Tr-gl_1001.png,glioma,0,1,/content/brain-tumour-mri-classification/proce...
2,Training/glioma/Tr-gl_1003.png,glioma,0,1,/content/brain-tumour-mri-classification/proce...
3,Training/glioma/Tr-gl_1014.png,glioma,0,1,/content/brain-tumour-mri-classification/proce...
4,Training/glioma/Tr-gl_1015.png,glioma,0,1,/content/brain-tumour-mri-classification/proce...

Fixed five-fold assignment validation passed.

In [ ]:
# ============================================================
# CREATING THE FIXED IMAGENET RESNET50 FEATURE EXTRACTOR
# ============================================================


# Creating a fresh ImageNet-pretrained ResNet50 model to extract features from MRI images
resnet50_feature_extractor = tf.keras.applications.ResNet50(
    include_top=False,     # Remove ResNet50's original ImageNet classification head
    weights="imagenet",    # The ImageNet weights are used
    input_shape=(IMAGE_HEIGHT, IMAGE_WIDTH, IMAGE_CHANNELS),    # Dimentions of the image
    pooling="avg",    # Convert the final feature maps into 2,048 average feature values
)

# Freeze every ResNet50 layer
resnet50_feature_extractor.trainable = False

# Expected number of features produced for each MRI image
FEATURE_DIMENSION = 2048


# ============================================================
# VERIFY THE FEATURE EXTRACTOR
# ============================================================

print("=" * 70)
print("FIXED IMAGENET RESNET50 FEATURE EXTRACTOR")
print("=" * 70)

print("Model name:", resnet50_feature_extractor.name)
print("Input shape:", resnet50_feature_extractor.input_shape)
print("Output shape:", resnet50_feature_extractor.output_shape)
print("Trainable:", resnet50_feature_extractor.trainable)
print("Trainable parameters:",
    sum(np.prod(variable.shape) for variable in resnet50_feature_extractor.trainable_weights))


# The feature extractor must produce exactly 2,048 features
if resnet50_feature_extractor.output_shape[-1] != FEATURE_DIMENSION:
    raise ValueError(
        f"Expected {FEATURE_DIMENSION} features, "
        f"but got {resnet50_feature_extractor.output_shape[-1]}.")


# Checking for trainable weights
if resnet50_feature_extractor.trainable_weights:
  raise RuntimeError("The feature extractor must not have any trainable weights.")


print("\nFixed feature extractor validation passed.")

Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/resnet/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5
94765736/94765736 ━━━━━━━━━━━━━━━━━━━━ 5s 0us/step
======================================================================
FIXED IMAGENET RESNET50 FEATURE EXTRACTOR
======================================================================
Model name: resnet50
Input shape: (None, 224, 224, 3)
Output shape: (None, 2048)
Trainable: False
Trainable parameters: 0

Fixed feature extractor validation passed.

In [ ]:
# ============================================================
# DEFINING RESNET50 IMAGE PREPROCESSING FOR FEATURE EXTRACTION
# ============================================================

def load_and_preprocess_resnet50_image(image_path, class_index):
  """
  Load one grayscale MRI image, convert it to pseudo-RGB and apply the ImageNet50 preprocessing function
  """

  # Reading the PNG image file
  image_bytes = tf.io.read_file(image_path)

  # Decoding as a single-channel grayscale image
  grayscale_image = tf.io.decode_png(image_bytes, channels = 1)

  # Confirming the expected grayscale image shape
  grayscale_image = tf.ensure_shape(grayscale_image, (IMAGE_HEIGHT, IMAGE_WIDTH, 1))

  # Repeat the grayscale channel three times
  pseudo_rgb_image = tf.image.grayscale_to_rgb(grayscale_image)

  # Convert pixel values to float32
  pseudo_rgb_image = tf.cast(pseudo_rgb_image, tf.float32)

  # Apply the ImageNet50 preprocessing required by ImageNet ResNet50
  preprocessed_image = tf.keras.applications.resnet50.preprocess_input(pseudo_rgb_image)

  # Confirm the final ResNet50 input shape
  resnet50_image = tf.ensure_shape(preprocessed_image, (IMAGE_HEIGHT, IMAGE_WIDTH, IMAGE_CHANNELS))

  return resnet50_image, class_index

In [ ]:
# ============================================================
# CREATE THE RESNET50 FEATURE-EXTRACTION DATASET
# ============================================================

def create_resnet50_feature_dataset(image_paths, class_indices, batch_size):
    """
    Create a deterministic TensorFlow dataset for fixed ResNet50 feature extraction without shuffling.
    """

    # Creating the dataset from image paths and class indices
    dataset = tf.data.Dataset.from_tensor_slices((image_paths, class_indices))

    # Keeping dataset processing deterministic
    dataset_options = tf.data.Options()
    dataset_options.experimental_deterministic = True

    dataset = dataset.with_options(dataset_options)

    # Loading and preprocessing each MRI image
    dataset = dataset.map(load_and_preprocess_resnet50_image, num_parallel_calls=tf.data.AUTOTUNE, deterministic=True)

    # Grouping images into batches without dropping the final batch
    dataset = dataset.batch(batch_size, drop_remainder=False)

    # Preparing upcoming batches in advance
    dataset = dataset.prefetch(tf.data.AUTOTUNE)

    return dataset

In [ ]:
# ============================================================
# DEFINE RESNET50 FEATURE EXTRACTION
# ============================================================


def extract_resnet50_features(dataset, feature_extractor):
  """
  Extract fixed ResNet50 features and preserve the corresponding class indices in dataset order.
  """

  feature_batches = []
  class_index_batches = []

  # Process the dataset one batch at a time
  for resnet50_image_batch, class_index_batch in dataset:

    # Extract fixed ImageNet ResNet50 features
    feature_batch = feature_extractor(resnet50_image_batch, training=False)

    # Store the features and corresponding class indices
    feature_batches.append(feature_batch.numpy())
    class_index_batches.append(class_index_batch.numpy())


  # Combining all batches into complete NumPy arrays
  features = np.concatenate(feature_batches, axis = 0).astype(np.float32)

  class_indices = np.concatenate(class_index_batches, axis = 0).astype(np.int32)

  return features, class_indices

In [ ]:
from numpy._core.multiarray import dtype

# ============================================================
# PREPARE THE TRAINING DATA FOR FEATURE EXTRACTION
# ============================================================

# Storing the Training image paths in fold-assignment row order
training_image_paths = assignments["image_path"].astype(str).to_numpy()


# Storing the Training class indices in fold-assignment row order
training_class_indices = assignments["class_index"].to_numpy(dtype = np.int32)


# Storing the corresponding fixed outer-fold assignments
training_fold_assignments = assignments["fold"].to_numpy(dtype = np.int32)


# Storing the relative paths for later feature-cache verification
training_relative_paths = assignments["relative_path"].astype(str).to_numpy()


# Verifying that all Training arrays contain the expected 5,600 rows
if not(len(training_image_paths) == len(training_class_indices) == len(training_fold_assignments)
    == len(training_relative_paths) == 5600):

  raise RuntimeError("The prepared Training arrays do not all the expected 5,600 images")


print("Training images prepared.", len(training_image_paths) )

Training images prepared. 5600

In [ ]:
# ============================================================
# CREATING THE TRAINING FEATURE EXTRACTION DATASET
# ============================================================

FEATURE_EXTRACTION_BATCH_SIZE = 64

training_feature_dataset = create_resnet50_feature_dataset(
    image_paths=training_image_paths,
    class_indices=training_class_indices,
    batch_size=FEATURE_EXTRACTION_BATCH_SIZE)

print("Training feature dataset created.")

Training feature dataset created.

In [ ]:
# ============================================================
# EXTRACTING RESNET50 FEATURES FROM THE TRAINING PARTITION
# ============================================================

training_feature_extraction_start = time.perf_counter()

# features and the class number
training_features, extracted_training_class_indices = extract_resnet50_features(
    dataset = training_feature_dataset, feature_extractor = resnet50_feature_extractor)


# Time taken for feature extraction
training_feature_extraction_seconds = (time.perf_counter() - training_feature_extraction_start)


if training_features.shape != (5600, FEATURE_DIMENSION):
    raise RuntimeError("Unexpected Training feature matrix shape: "f"{training_features.shape}")


if not np.array_equal(extracted_training_class_indices, training_class_indices):
    raise RuntimeError("Extracted Training class indices do not match the original Training class indices.")


if not np.isfinite(training_features).all():
    raise RuntimeError("Non-finite values were found in the Training feature matrix.")


print("Training images:", training_features.shape[0])
print("Features per image:", training_features.shape[1])
print("Feature matrix shape:", training_features.shape)
print("Class-index alignment verified:", True)
print("Training feature extraction time:", f"{training_feature_extraction_seconds:.2f}s")

Training images: 5600
Features per image: 2048
Feature matrix shape: (5600, 2048)
Class-index alignment verified: True
Training feature extraction time: 24.04s

In [ ]:
# ============================================================
# SAVING THE TRAINING RESNET50 FEATURES
# ============================================================

# Create the persistent hybrid-model results directory
HYBRID_RESULTS_DIR = (
    Path("/content/drive/MyDrive/brain_tumour_colab")
    / "results"
    / "resnet50_fixed_features")

HYBRID_RESULTS_DIR.mkdir(parents=True, exist_ok=True)


# Create the path for the cached Training features
TRAINING_FEATURES_PATH = (HYBRID_RESULTS_DIR / "training_resnet50_features.npz")


# Save the features together with their labels, folds,
# and relative image paths
np.savez_compressed(
    TRAINING_FEATURES_PATH,
    features=training_features,
    class_indices=training_class_indices,
    fold_assignments=training_fold_assignments,
    relative_paths=training_relative_paths,
)


print("Training feature cache saved:", TRAINING_FEATURES_PATH)
print("Feature matrix shape:", training_features.shape)

Training feature cache saved: /content/drive/MyDrive/brain_tumour_colab/results/resnet50_fixed_features/training_resnet50_features.npz
Feature matrix shape: (5600, 2048)

In [ ]:
# ============================================================
# DEFINING THE SVM HYPERPARAMETER SEARCH
# ============================================================

from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC


# Define the SVM pipeline
svm_pipeline = Pipeline(steps=[("scaler", StandardScaler()), ("classifier", SVC())])


# Define the fixed SVM search grid
SVM_PARAMETER_GRID = {
    "classifier__C": [0.01, 0.1, 1, 10, 100],
    "classifier__gamma": ["scale", 1e-5, 1e-4, 1e-3, 1e-2]}


# Define the Training-only inner cross-validation
svm_inner_cross_validation = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_SEED)


# Create the SVM grid search
svm_grid_search = GridSearchCV(estimator=svm_pipeline, param_grid=SVM_PARAMETER_GRID, scoring="f1_macro", cv=svm_inner_cross_validation,
    n_jobs=-1, refit=True, return_train_score=False)


print("SVM hyperparameter combinations:", 25)
print("Inner cross-validation folds:", 3)
print("Selection metric: macro F1")

SVM hyperparameter combinations: 25
Inner cross-validation folds: 3
Selection metric: macro F1

In [ ]:
# ============================================================
# RUN NESTED FIVE-FOLD CROSS-VALIDATION FOR THE SVM
# ============================================================

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

svm_nested_cv_start = time.perf_counter()

# Store the outer-fold results
svm_fold_results = []

svm_oof_predictions = np.empty(len(training_class_indices), dtype=np.int32)

# Going through each predefined outer validation fold
for validation_fold in range(1, 6):

    print("=" * 70)
    print(f"SVM OUTER FOLD {validation_fold}")
    print("=" * 70)

    # Identifying the outer Training and validation rows
    outer_training_mask = training_fold_assignments != validation_fold
    outer_validation_mask = training_fold_assignments == validation_fold


    # Create the outer Training data
    outer_training_features = training_features[outer_training_mask]
    outer_training_class_indices = training_class_indices[outer_training_mask]


    # Create the outer validation data
    outer_validation_features = training_features[outer_validation_mask]
    outer_validation_class_indices = training_class_indices[outer_validation_mask]


    print("Outer Training images:", len(outer_training_class_indices))
    print("Outer validation images:", len(outer_validation_class_indices))


    # Run the 3-fold Training-only SVM hyperparameter search
    svm_grid_search.fit(outer_training_features, outer_training_class_indices)


    # Predict the held-out outer validation fold
    fold_predictions = svm_grid_search.predict(outer_validation_features)


    # Store the predictions in their original Training-row positions
    svm_oof_predictions[outer_validation_mask] = fold_predictions


    # Calculate outer-fold metrics
    fold_accuracy = accuracy_score(outer_validation_class_indices, fold_predictions)

    fold_macro_precision = precision_score(outer_validation_class_indices, fold_predictions, average="macro", zero_division=0)

    fold_macro_recall = recall_score(outer_validation_class_indices, fold_predictions, average="macro", zero_division=0)

    fold_macro_f1 = f1_score(outer_validation_class_indices, fold_predictions, average="macro", zero_division=0)


    # Save the result for this outer fold
    svm_fold_results.append(
        {
            "fold": validation_fold,
            "accuracy": fold_accuracy,
            "macro_precision": fold_macro_precision,
            "macro_recall": fold_macro_recall,
            "macro_f1": fold_macro_f1,
            "best_C": svm_grid_search.best_params_["classifier__C"],
            "best_gamma": svm_grid_search.best_params_["classifier__gamma"],
            "best_inner_macro_f1": (svm_grid_search.best_score_),
        }
    )


    print("Best parameters:", svm_grid_search.best_params_)
    print("Outer-fold macro F1:", round(fold_macro_f1, 6))

svm_nested_cv_seconds = (time.perf_counter() - svm_nested_cv_start)

print("SVM nested cross-validation time:", f"{svm_nested_cv_seconds:.2f}s")
print("\nSVM five-fold nested cross-validation completed.")

======================================================================
SVM OUTER FOLD 1
======================================================================
Outer Training images: 4480
Outer validation images: 1120
Best parameters: {'classifier__C': 100, 'classifier__gamma': 0.0001}
Outer-fold macro F1: 0.958303
======================================================================
SVM OUTER FOLD 2
======================================================================
Outer Training images: 4480
Outer validation images: 1120
Best parameters: {'classifier__C': 100, 'classifier__gamma': 0.0001}
Outer-fold macro F1: 0.944799
======================================================================
SVM OUTER FOLD 3
======================================================================
Outer Training images: 4480
Outer validation images: 1120
Best parameters: {'classifier__C': 100, 'classifier__gamma': 0.0001}
Outer-fold macro F1: 0.951314
======================================================================
SVM OUTER FOLD 4
======================================================================
Outer Training images: 4480
Outer validation images: 1120
Best parameters: {'classifier__C': 10, 'classifier__gamma': 'scale'}
Outer-fold macro F1: 0.964308
======================================================================
SVM OUTER FOLD 5
======================================================================
Outer Training images: 4480
Outer validation images: 1120
Best parameters: {'classifier__C': 10, 'classifier__gamma': 'scale'}
Outer-fold macro F1: 0.953714

SVM five-fold nested cross-validation completed.

In [ ]:
# ======================================================================
# SUMMARIZE THE SVM NESTED CROSS-VALIDATION RESULTS
# ======================================================================

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix

# Converting the five outer-fold results into a DataFrame
svm_fold_results_dataframe = pd.DataFrame(svm_fold_results)


# Calculating the mean outer-fold metrics
svm_mean_accuracy = svm_fold_results_dataframe["accuracy"].mean()
svm_mean_macro_precision = svm_fold_results_dataframe["macro_precision"].mean()
svm_mean_macro_recall = svm_fold_results_dataframe["macro_recall"].mean()
svm_mean_macro_f1 = svm_fold_results_dataframe["macro_f1"].mean()


# Calculating sample standard deviations across the five folds
svm_std_accuracy = svm_fold_results_dataframe["accuracy"].std(ddof=1)
svm_std_macro_precision = svm_fold_results_dataframe["macro_precision"].std(ddof=1)
svm_std_macro_recall = svm_fold_results_dataframe["macro_recall"].std(ddof=1)
svm_std_macro_f1 = svm_fold_results_dataframe["macro_f1"].std(ddof=1)


# Calculating pooled out-of-fold metrics
svm_oof_accuracy = accuracy_score(training_class_indices, svm_oof_predictions)
svm_oof_macro_precision = precision_score(training_class_indices, svm_oof_predictions, average="macro", zero_division=0)
svm_oof_macro_recall = recall_score(training_class_indices, svm_oof_predictions, average="macro", zero_division=0)
svm_oof_macro_f1 = f1_score(training_class_indices, svm_oof_predictions, average="macro", zero_division=0)


# Create the pooled OOF confusion matrix
svm_oof_confusion_matrix = confusion_matrix(
    training_class_indices,
    svm_oof_predictions,
    labels=list(range(NUMBER_OF_CLASSES)))



# DISPLAY THE RESULTS

display(svm_fold_results_dataframe)
print("\n--- Five-fold mean ± sample SD ---")
print("Accuracy:", f"{svm_mean_accuracy:.6f} ± {svm_std_accuracy:.6f}")
print("Macro precision:",
    f"{svm_mean_macro_precision:.6f} ± "
    f"{svm_std_macro_precision:.6f}")
print("Macro recall:",
    f"{svm_mean_macro_recall:.6f} ± "
    f"{svm_std_macro_recall:.6f}"
print("Macro F1:",
    f"{svm_mean_macro_f1:.6f} ± "
    f"{svm_std_macro_f1:.6f}")
print("\n--- Pooled OOF metrics ---")
print("Accuracy:", f"{svm_oof_accuracy:.6f}")
print("Macro precision:", f"{svm_oof_macro_precision:.6f}")
print("Macro recall:", f"{svm_oof_macro_recall:.6f}")
print("Macro F1:", f"{svm_oof_macro_f1:.6f}")
print("\nPooled OOF confusion matrix:")
print(svm_oof_confusion_matrix)

NameError: name 'svm_fold_results' is not defined

In [ ]:
# ======================================================================
# SELECT THE FINAL SVM HYPERPARAMETERS USING ALL TRAINING FEATURES
# ======================================================================

# Create the final SVM pipeline
final_svm_grid_search = GridSearchCV(estimator=svm_pipeline, param_grid=SVM_PARAMETER_GRID, scoring="f1_macro",
    cv=StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_SEED),
    n_jobs=-1, refit=True, return_train_score=False)


final_svm_search_start = time.perf_counter()

# Running the final training-only hyperparameter search on all 5600 images
final_svm_grid_search.fit(training_features, training_class_indices)

final_svm_search_seconds = (time.perf_counter() - final_svm_search_start)

print("Final SVM hyperparameters:", final_svm_grid_search.best_params_)
print("Best training CV macro F1", round(final_svm_grid_search.best_score_, 6))
print("Final SVM hyperparameter search time:", f"{final_svm_search_seconds:.2f}s")

KeyboardInterrupt:

In [ ]:
# ======================================================================
# SAVE THE FINAL TRAINED SVM
# ======================================================================

import joblib

# The final SVM already refitted on all 5600 images
final_svm_model = final_svm_grid_search.best_estimator_

# The path for the final trained SVM
FINAL_SVM_MODEL_PATH = (HYBRID_RESULTS_DIR / "final_svm_model.joblib")

# Saving the final SVM
joblib.dump(final_svm_model, FINAL_SVM_MODEL_PATH)

print("Final SVM parameters:", final_svm_grid_search.best_params_)
print("Final SVM model saved:", FINAL_SVM_MODEL_PATH)

AttributeError: 'GridSearchCV' object has no attribute 'best_estimator_'

In [ ]:
# ======================================================================
# DEFINE THE RANDOM FOREST SUCCESSIVE-HALVING SEARCH
# ======================================================================

from sklearn.ensemble import RandomForestClassifier
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingRandomSearchCV, StratifiedKFold

# Original Random Forest search space
RF_PARAMETER_DISTRIBUTIONS = {
    "criterion": ["gini", "entropy"],
    "max_depth": [None, 20,  40,  60,  80],
    "min_samples_split": [2, 5, 10, 20],
    "min_samples_leaf": [1, 2, 4, 8],
    "max_features": ["sqrt", "log2", 0.02, 0.05, 0.1, 0.2],
    "bootstrap": [True, False]
}

# Succesive halving configuration
HALVING_INITIAL_CANDIDATES = 100
HALVING_FACTOR = 3
HALVING_MINIMUM_TREES = 25
HALVING_MAXIMUM_TREES = 675

# Random Forest classifier
random_forest_classifier = RandomForestClassifier(random_state=RANDOM_SEED, n_jobs=1)


# Inner cross-validation
rf_inner_cross_validation = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_SEED)


# Create the RF grid search
rf_halving_search = HalvingRandomSearchCV(
    estimator=random_forest_classifier,
    param_distributions=RF_PARAMETER_DISTRIBUTIONS,
    n_candidates=HALVING_INITIAL_CANDIDATES,
    factor=HALVING_FACTOR,
    resource="n_estimators",
    min_resources=HALVING_MINIMUM_TREES,
    max_resources=HALVING_MAXIMUM_TREES,
    scoring="f1_macro",
    cv=rf_inner_cross_validation,
    random_state=RANDOM_SEED,
    n_jobs=-1,
    refit=True,
    return_train_score=False,
)


print("Initial RF candidates:", HALVING_INITIAL_CANDIDATES)
print("Halving factor:", HALVING_FACTOR)
print("Tree resources: 25 -> 75 -> 225 -> 675")
print("Inner CV folds:", 3)
print("Selection metric: macro F1")
print("Feature standardisation:", False)

Initial RF candidates: 100
Halving factor: 3
Tree resources: 25 -> 75 -> 225 -> 675
Inner CV folds: 3
Selection metric: macro F1
Feature standardisation: False

In [ ]:
HYBRID_RESULTS_DIR = (
    Path("/content/drive/MyDrive/brain_tumour_colab")
    / "results"
    / "resnet50_fixed_features"
)

In [ ]:
# ======================================================================
# RUN NESTED FIVE-FOLD CROSS-VALIDATION FOR THE RANDOM FOREST
# ======================================================================

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
import time

# Create a directory for saving each completed RF fold
RF_CV_RESULTS_DIR = (HYBRID_RESULTS_DIR / "random_forest" / "cross_validation")

RF_CV_RESULTS_DIR.mkdir(parents=True, exist_ok=True)


# Store the outer-fold results
rf_fold_results = []

rf_oof_predictions = np.empty(len(training_class_indices), dtype=np.int32)

# Start time for the RF evaluation
rf_nested_cv_start = time.perf_counter()

# Going through each predefined outer validation fold
for validation_fold in range(1, 6):

    print("=" * 70)
    print(f"RF OUTER FOLD {validation_fold}")
    print("=" * 70)

    # Start timing the current outer fold
    outer_fold_start = time.perf_counter()


    # Ientifying the outer training and validation rows
    outer_training_mask = training_fold_assignments != validation_fold
    outer_validation_mask = training_fold_assignments == validation_fold


    # Create the outer Training data
    outer_training_features = training_features[outer_training_mask]
    outer_training_class_indices = training_class_indices[outer_training_mask]


    # Create the outer validation data
    outer_validation_features = training_features[outer_validation_mask]
    outer_validation_class_indices = training_class_indices[outer_validation_mask]

    print("Outer Training images:", len(outer_training_class_indices))
    print("Outer validation images:", len(outer_validation_class_indices))

    # Running a 3-fold training only succesive halving search
    rf_halving_search.fit(outer_training_features, outer_training_class_indices)

    # Predict the untouched outer validation fold
    fold_predictions = rf_halving_search.predict(outer_validation_features)

    # Store the predictions in their original Training-row positions
    rf_oof_predictions[outer_validation_mask] = fold_predictions


    # Calculate outer-fold metrics
    fold_accuracy = accuracy_score(outer_validation_class_indices, fold_predictions)

    fold_macro_precision = precision_score(outer_validation_class_indices, fold_predictions, average="macro", zero_division=0)

    fold_macro_recall = recall_score(outer_validation_class_indices, fold_predictions, average="macro", zero_division=0)

    fold_macro_f1 = f1_score(outer_validation_class_indices, fold_predictions, average="macro", zero_division=0)

    # Record the selected hyperparameters
    best_parameters = rf_halving_search.best_params_


    # Calculate the time taken for this outer fold
    outer_fold_seconds = (time.perf_counter() - outer_fold_start)
    print("Outer fold time:", f"{outer_fold_seconds:.2f}s")


    # Storing the selected RF configuration
    fold_results = {
            "fold": validation_fold,
            "accuracy": fold_accuracy,
            "macro_precision": fold_macro_precision,
            "macro_recall": fold_macro_recall,
            "macro_f1": fold_macro_f1,
            "best_n_estimators": (rf_halving_search.best_estimator_.n_estimators),
            "best_criterion": best_parameters["criterion"],
            "best_max_depth": best_parameters["max_depth"],
            "best_min_samples_split": (best_parameters["min_samples_split"]),
            "best_min_samples_leaf": (best_parameters["min_samples_leaf"]),
            "best_max_features": (best_parameters["max_features"]),
            "best_bootstrap": (best_parameters["bootstrap"]),
            "best_inner_macro_f1": (rf_halving_search.best_score_),
            "outer_fold_time": outer_fold_seconds,
            }

    rf_fold_results.append(fold_results)


    # ================================================================
    # SAVE THIS COMPLETED FOLD IMMEDIATELY
    # ================================================================

    fold_result_path = (RF_CV_RESULTS_DIR / f"fold_{validation_fold}_results.csv")
    fold_predictions_path = (RF_CV_RESULTS_DIR / f"fold_{validation_fold}_predictions.npz")


    # Save the fold metrics and selected hyperparameters
    pd.DataFrame([fold_results]).to_csv(fold_result_path, index=False)


    # Save the true labels and predictions for this outer fold
    np.savez_compressed(
        fold_predictions_path,
        true_class_indices=outer_validation_class_indices,
        predicted_class_indices=fold_predictions,
        relative_paths=training_relative_paths[outer_validation_mask])


    print("Best parameters:", rf_halving_search.best_params_)
    print("Selected trees:", rf_halving_search.best_estimator_.n_estimators)
    print("Outer-fold macro F1:", round(fold_macro_f1, 6))
    print("Fold time:", f"{outer_fold_seconds:.2f}s")
    print("Fold saved:", fold_result_path)


# Stop timing
rf_nested_cv_seconds = (time.perf_counter() - rf_nested_cv_start)

print("RF nested cross-validation time:", f"{rf_nested_cv_seconds:.2f}s")
print("\nRF five-fold nested cross-validation completed.")

======================================================================
RF OUTER FOLD 4
======================================================================
Outer Training images: 4480
Outer validation images: 1120
Outer fold time: 7202.23s
Best parameters: {'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.2, 'max_depth': 40, 'criterion': 'gini', 'bootstrap': False, 'n_estimators': 675}
Selected trees: 675
Outer-fold macro F1: 0.931033
Fold time: 7202.23s
Fold saved: /content/drive/MyDrive/brain_tumour_colab/results/resnet50_fixed_features/random_forest/cross_validation/fold_4_results.csv
======================================================================
RF OUTER FOLD 5
======================================================================
Outer Training images: 4480
Outer validation images: 1120
Outer fold time: 6999.63s
Best parameters: {'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.2, 'max_depth': 40, 'criterion': 'gini', 'bootstrap': False, 'n_estimators': 675}
Selected trees: 675
Outer-fold macro F1: 0.928574
Fold time: 6999.63s
Fold saved: /content/drive/MyDrive/brain_tumour_colab/results/resnet50_fixed_features/random_forest/cross_validation/fold_5_results.csv
RF nested cross-validation time: 14201.90s

RF five-fold nested cross-validation completed.

In [ ]:
from sklearn.metrics import confusion_matrix

# ======================================================================
# RECONSTRUCT AND SUMMARIZE ALL FIVE SAVED RF OUTER FOLDS
# ======================================================================


# Store the five saved fold-result tables
saved_rf_fold_results = []

# Reconstruct pooled OOF predictions
reconstructed_rf_oof_predictions = np.empty(len(training_class_indices), dtype=np.int32)

# Track which Training rows receive an OOF prediction
oof_prediction_assigned = np.zeros(len(training_class_indices), dtype=bool)


# Load all five completed folds from Drive
for validation_fold in range(1, 6):

    fold_result_path = RF_CV_RESULTS_DIR / f"fold_{validation_fold}_results.csv"

    fold_predictions_path = RF_CV_RESULTS_DIR / f"fold_{validation_fold}_predictions.npz"


    # Load fold metrics and selected hyperparameters
    fold_result_dataframe = pd.read_csv(fold_result_path)

    saved_rf_fold_results.append(fold_result_dataframe)


    # Load saved validation predictions
    with np.load(fold_predictions_path, allow_pickle=False) as fold_prediction_data:

        fold_true_class_indices = fold_prediction_data["true_class_indices"]

        fold_predicted_class_indices = fold_prediction_data["predicted_class_indices"]

    # Identify the original rows belonging to this validation fold
    outer_validation_mask = training_fold_assignments == validation_fold

    # Verify that the saved labels match the fixed fold assignments
    expected_true_class_indices = training_class_indices[outer_validation_mask]

    if not np.array_equal(fold_true_class_indices, expected_true_class_indices):
        raise RuntimeError("Saved RF labels mismatch.")


    # Restore the saved predictions to their original position
    reconstructed_rf_oof_predictions[outer_validation_mask] = fold_predicted_class_indices

    print(f"Loaded RF fold {validation_fold}:", len(fold_predicted_class_indices), "predictions")

    # Mark these rows as successfully reconstructed
    oof_prediction_assigned[outer_validation_mask] = True


# Combine the five fold-result tables
rf_fold_results_dataframe = pd.concat(saved_rf_fold_results,
    ignore_index=True).sort_values("fold").reset_index(drop=True)

# Verify that five folds were loaded
if len(rf_fold_results_dataframe) != 5:
    raise RuntimeError("Five folds not loaded.")

# Verify that all 5,6000 images received an OOF prediction
if not oof_prediction_assigned.all():
    raise RuntimeError("OOF predictions not assigned.")

# ======================================================================
# FIVE-FOLD MEAN ± SAMPLE STANDARD DEVIATION
# ======================================================================

rf_mean_accuracy = (rf_fold_results_dataframe["accuracy"].mean())

rf_std_accuracy = (rf_fold_results_dataframe["accuracy"].std(ddof=1))

rf_mean_macro_precision = (rf_fold_results_dataframe["macro_precision"].mean())

rf_std_macro_precision = (rf_fold_results_dataframe["macro_precision"].std(ddof=1))

rf_mean_macro_recall = (rf_fold_results_dataframe["macro_recall"].mean())

rf_std_macro_recall = (rf_fold_results_dataframe["macro_recall"].std(ddof=1))

rf_mean_macro_f1 = (rf_fold_results_dataframe["macro_f1"].mean())

rf_std_macro_f1 = (rf_fold_results_dataframe["macro_f1"].std(ddof=1))


# ======================================================================
# POOLED OOF METRICS
# ======================================================================

rf_oof_accuracy = accuracy_score(training_class_indices, reconstructed_rf_oof_predictions)

rf_oof_macro_precision = precision_score(training_class_indices, reconstructed_rf_oof_predictions, average="macro", zero_division=0)

rf_oof_macro_recall = recall_score(training_class_indices, reconstructed_rf_oof_predictions, average="macro", zero_division=0)

rf_oof_macro_f1 = f1_score(training_class_indices, reconstructed_rf_oof_predictions, average="macro", zero_division=0)

rf_oof_confusion_matrix = confusion_matrix(training_class_indices, reconstructed_rf_oof_predictions, labels=list(range(NUMBER_OF_CLASSES)))


# Complete time across all five saved outer folds
rf_total_outer_fold_seconds = (rf_fold_results_dataframe["outer_fold_time"].sum())


# ======================================================================
# DISPLAY RESULTS
# ======================================================================

display(rf_fold_results_dataframe)
print("\n--- Five-fold mean ± sample SD ---")
print("Accuracy:", f"{rf_mean_accuracy:.6f} ± {rf_std_accuracy:.6f}")
print("Macro precision:", f"{rf_mean_macro_precision:.6f} ± "f"{rf_std_macro_precision:.6f}")
print("Macro recall:", f"{rf_mean_macro_recall:.6f} ± "f"{rf_std_macro_recall:.6f}")
print("Macro F1:", f"{rf_mean_macro_f1:.6f} ± {rf_std_macro_f1:.6f}")
print("\n--- Pooled OOF metrics ---")
print("Accuracy:", f"{rf_oof_accuracy:.6f}")
print("Macro precision:", f"{rf_oof_macro_precision:.6f}")
print("Macro recall:", f"{rf_oof_macro_recall:.6f}")
print("Macro F1:", f"{rf_oof_macro_f1:.6f}")
print("\nPooled OOF confusion matrix:")
print(rf_oof_confusion_matrix)
print("\nTotal time across all five outer folds:",f"{rf_total_outer_fold_seconds:.2f}s")
print("All 5,600 OOF predictions reconstructed:",oof_prediction_assigned.all())

Loaded RF fold 1: 1120 predictions
Loaded RF fold 2: 1120 predictions
Loaded RF fold 3: 1120 predictions
Loaded RF fold 4: 1120 predictions
Loaded RF fold 5: 1120 predictions

,fold,accuracy,macro_precision,macro_recall,macro_f1,best_n_estimators,best_criterion,best_max_depth,best_min_samples_split,best_min_samples_leaf,best_max_features,best_bootstrap,best_inner_macro_f1,outer_fold_time
0,1,0.916071,0.920241,0.916071,0.916362,675,gini,NaN,2,1,0.2,False,0.906870,7632.748800
1,2,0.905357,0.907375,0.905357,0.904888,675,gini,40.0,2,1,0.2,False,0.909750,7530.042221
2,3,0.916071,0.918549,0.916071,0.916511,675,entropy,40.0,5,1,0.1,False,0.904863,5639.339466
3,4,0.931250,0.932130,0.931250,0.931033,675,gini,40.0,2,2,0.2,False,0.905929,7202.233179
4,5,0.928571,0.929719,0.928571,0.928574,675,gini,40.0,2,1,0.2,False,0.907286,6999.625524

--- Five-fold mean ± sample SD ---
Accuracy: 0.919464 ± 0.010534
Macro precision: 0.921603 ± 0.009878
Macro recall: 0.919464 ± 0.010534
Macro F1: 0.919474 ± 0.010578

--- Pooled OOF metrics ---
Accuracy: 0.919464
Macro precision: 0.921416
Macro recall: 0.919464
Macro F1: 0.919495

Pooled OOF confusion matrix:
[[1208  175    0   17]
 [  35 1226   49   90]
 [   1   20 1366   13]
 [   9   41    1 1349]]

Total time across all five outer folds: 35003.99s
All 5,600 OOF predictions reconstructed: True

In [ ]:
# ======================================================================
# SELECT THE FINAL RANDOM FOREST HYPERPARAMETERS USING ALL 5,600 TRAINING FEATURES
# ======================================================================

# Create a fresh Random Forest classifier
final_random_forest_classifier = RandomForestClassifier(random_state=RANDOM_SEED, n_jobs=1)


# Create the final 3-fold Training-only cross-validation
final_rf_inner_cross_validation = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_SEED)


# Create a fresh successive-halving search
final_rf_halving_search = HalvingRandomSearchCV(
    estimator=final_random_forest_classifier,
    param_distributions=RF_PARAMETER_DISTRIBUTIONS,
    n_candidates=HALVING_INITIAL_CANDIDATES,
    factor=HALVING_FACTOR,
    resource="n_estimators",
    min_resources=HALVING_MINIMUM_TREES,
    max_resources=HALVING_MAXIMUM_TREES,
    scoring="f1_macro",
    cv=final_rf_inner_cross_validation,
    random_state=RANDOM_SEED,
    n_jobs=-1,
    refit=True,
    return_train_score=False,
)


# Start timing the final RF search
final_rf_search_start = time.perf_counter()


# Run the final Training-only search on all 5,600 feature vectors
final_rf_halving_search.fit(training_features, training_class_indices)


# Stop timing
final_rf_search_seconds = time.perf_counter() - final_rf_search_start


# Record the refit time for the selected final model
final_rf_refit_seconds = final_rf_halving_search.refit_time_



print("Final RF hyperparameters:", final_rf_halving_search.best_params_)
print("Selected trees:", final_rf_halving_search.best_estimator_.n_estimators)
print("Best Training CV macro F1:", round(final_rf_halving_search.best_score_, 6))
print("Final RF hyperparameter search time:", f"{final_rf_search_seconds:.2f}s")
print("Final RF refit time:", f"{final_rf_refit_seconds:.2f}s")

Final RF hyperparameters: {'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.2, 'max_depth': None, 'criterion': 'gini', 'bootstrap': False, 'n_estimators': 675}
Selected trees: 675
Best Training CV macro F1: 0.913683
Final RF hyperparameter search time: 10227.56s
Final RF refit time: 3352.03s

In [ ]:
# ======================================================================
# SAVE THE FINAL TRAINED RANDOM FOREST
# ======================================================================

import joblib


# The final RF is already refitted on all 5,600 Training features
final_rf_model = final_rf_halving_search.best_estimator_


# Path for the final trained ResNet50 + RF model
FINAL_RF_MODEL_PATH = HYBRID_RESULTS_DIR / "final_resnet50_random_forest.joblib"


# Save the final RF model
joblib.dump(final_rf_model, FINAL_RF_MODEL_PATH)


print("Final RF parameters:", final_rf_halving_search.best_params_)
print("Final RF model saved:", FINAL_RF_MODEL_PATH)

Final RF parameters: {'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.2, 'max_depth': None, 'criterion': 'gini', 'bootstrap': False, 'n_estimators': 675}
Final RF model saved: /content/drive/MyDrive/brain_tumour_colab/results/resnet50_fixed_features/final_resnet50_random_forest.joblib

In [ ]:
# ======================================================================
# LOAD THE LOCKED FINAL RESNET50 HYBRID CLASSIFIERS
# ======================================================================

import joblib
from pathlib import Path


HYBRID_RESULTS_DIR = Path("/content/drive/MyDrive/brain_tumour_colab") / "results" / "resnet50_fixed_features"


FINAL_SVM_MODEL_PATH = HYBRID_RESULTS_DIR / "final_svm_model.joblib"

FINAL_RF_MODEL_PATH = HYBRID_RESULTS_DIR / "final_resnet50_random_forest.joblib"


# Load the two locked final classifiers
final_svm_model = joblib.load(FINAL_SVM_MODEL_PATH)

final_rf_model = joblib.load(FINAL_RF_MODEL_PATH)


print("Final ResNet50 SVM loaded:", FINAL_SVM_MODEL_PATH)
print("Final ResNet50 RF loaded:", FINAL_RF_MODEL_PATH)

Final ResNet50 SVM loaded: /content/drive/MyDrive/brain_tumour_colab/results/resnet50_fixed_features/final_svm_model.joblib
Final ResNet50 RF loaded: /content/drive/MyDrive/brain_tumour_colab/results/resnet50_fixed_features/final_resnet50_random_forest.joblib

In [ ]:
# ======================================================================
# PREPARING THE HELD-OUT TESTING PARTITION
# ======================================================================

# Testing directory
TESTING_DIR = DATA_DIR / "Testing"

# Collect Testing image paths in the fixed class order
testing_image_paths = []
testing_class_indices = []
testing_relative_paths = []

for class_index, class_name in enumerate(CLASS_NAMES):
    class_directory = TESTING_DIR / class_name

    class_image_paths = sorted(class_directory.glob("*.png"))

    print(f"{class_name} Testing images:", len(class_image_paths))

    for image_path in class_image_paths:
        testing_image_paths.append(image_path)
        testing_class_indices.append(class_index)
        testing_relative_paths.append(str(image_path.relative_to(DATA_DIR)))


# Converting to NumPy arrays
testing_image_paths = np.array(testing_image_paths, dtype = str)
testing_class_indices = np.array(testing_class_indices, dtype = np.int32)
testing_relative_paths = np.array(testing_relative_paths, dtype = str)


# ======================================================================
# VERIFY TESTING PARTITION
# ======================================================================

if len(testing_image_paths) != 1598:
  raise RuntimeError("Wrong number of testing images.")

expected_testing_class_counts = {
    0: 400, # glioma
    1: 400, # meningioma
    2: 398, # notumor
    3: 400, # pituitary

}

for class_index, expected_count in expected_testing_class_counts.items():
    actual_count = np.sum(testing_class_indices == class_index)

    if actual_count != expected_count:
        raise RuntimeError(f"Unexpected Testing count for class {class_index}.")


print("\nTesting images:", len(testing_image_paths))
print("Testing partition verification passed")

glioma Testing images: 400
meningioma Testing images: 400
notumor Testing images: 398
pituitary Testing images: 400

Testing images: 1598
Testing partition verification passed

In [ ]:
# ======================================================================
# CREATE THE RESNET50 FEATURE DATASET FOR THE HELD-OUT TESTING PARTITION
# ======================================================================

FEATURE_EXTRACTION_BATCH_SIZE = 64

testing_feature_dataset = create_resnet50_feature_dataset(
    image_paths = testing_image_paths,
    class_indices = testing_class_indices,
    batch_size = FEATURE_EXTRACTION_BATCH_SIZE)

print("Testing images:", len(testing_image_paths))
print("Feature extraction batch size", FEATURE_EXTRACTION_BATCH_SIZE)
print("Testing feature dataset:", testing_feature_dataset)
print("Testing feature dataset verified")

Testing images: 1598
Feature extraction batch size 64
Testing feature dataset: <_PrefetchDataset element_spec=(TensorSpec(shape=(None, 224, 224, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>
Testing feature dataset verified

In [ ]:
# ======================================================================
# EXTRACT RESNET50 FEATURES FROM THE HELD-OUT TESTING PARTITION
# ======================================================================

# Start timing the feature extraction
testing_feature_extraction_start = time.perf_counter()

# Extract fixed ResNet50 features
testing_features, extracted_testing_class_indices = extract_resnet50_features(
    dataset = testing_feature_dataset,
    feature_extractor = resnet50_feature_extractor)

# Stop the timing
testing_feature_extraction_seconds = time.perf_counter() - testing_feature_extraction_start


# ======================================================================
# VERIFY THE EXTRACTED TESTING FEATURES
# ======================================================================

if testing_features.shape != (len(testing_class_indices), FEATURE_DIMENSION):
    raise RuntimeError("Unexpected testing feature matrix")

if not np.array_equal(extracted_testing_class_indices, testing_class_indices):
    raise RuntimeError("Unexpected testing class indices")

if not np.isfinite(testing_features).all():
    raise RuntimeError("Non-finite testing features")

print("Testing images:", testing_features.shape[0])
print("Features per image:", testing_features.shape[1])
print("Testing feature matrix shape:", testing_features.shape)
print("Testing feature extraction time:", f"{testing_feature_extraction_seconds:.2f}s")
print("Class-index alignment verified:", True)

Testing images: 1598
Features per image: 2048
Testing feature matrix shape: (1598, 2048)
Testing feature extraction time: 6.33s
Class-index alignment verified: True

In [ ]:
# ======================================================================
# FINAL HELD-OUT TESTING EVALUATION: RESNET50 + SVM
# ======================================================================

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

# Start timing classifier prediction only
svm_testing_prediction_start = time.perf_counter()

# Predict the held-out Testing partition
svm_testing_predictions = final_svm_model.predict(testing_features)

# Stop the timing
svm_testing_prediction_seconds = time.perf_counter() - svm_testing_prediction_start

# End to end testing time: ResNet50 feature extraction + SVM prediction
svm_testing_end_to_end_seconds = testing_feature_extraction_seconds + svm_testing_prediction_seconds


# ======================================================================
# CALCULATE FINAL TESTING METRICS
# ======================================================================

svm_testing_accuracy = accuracy_score(testing_class_indices, svm_testing_predictions)

svm_testing_macro_precision = precision_score(testing_class_indices, svm_testing_predictions, average="macro", zero_division=0)

svm_testing_macro_recall = recall_score(testing_class_indices, svm_testing_predictions, average="macro", zero_division=0)

svm_testing_macro_f1 = f1_score(testing_class_indices, svm_testing_predictions, average="macro", zero_division=0)

svm_testing_confusion_matrix = confusion_matrix(testing_class_indices, svm_testing_predictions, labels=list(range(NUMBER_OF_CLASSES)))

svm_testing_classification_report = classification_report(testing_class_indices, svm_testing_predictions, labels = list(range(NUMBER_OF_CLASSES)), target_names=CLASS_NAMES, zero_division=0, digits = 6)


# ======================================================================
# DISPLAY THE FINAL TESTING RESULTS
# ======================================================================

print("--- ResNet50 + SVM: Held-out Testing results ---")
print("Accuracy:", f"{svm_testing_accuracy:.6f}")
print("Macro precision:", f"{svm_testing_macro_precision:.6f}")
print("Macro recall:", f"{svm_testing_macro_recall:.6f}")
print("Macro F1:", f"{svm_testing_macro_f1:.6f}")
print("\nClassification report:")
print(svm_testing_classification_report)
print("Confusion matrix:")
print(svm_testing_confusion_matrix)
print("\nSVM prediction time:", f"{svm_testing_prediction_seconds:.4f}s")
print("ResNet50 Testing feature extraction time:", f"{testing_feature_extraction_seconds:.2f}s")
print("End-to-end Testing time:", f"{svm_testing_end_to_end_seconds:.2f}s")

--- ResNet50 + SVM: Held-out Testing results ---
Accuracy: 0.936796
Macro precision: 0.941051
Macro recall: 0.936875
Macro F1: 0.935316

Classification report:
              precision    recall  f1-score   support

      glioma   0.975155  0.785000  0.869806       400
  meningioma   0.860619  0.972500  0.913146       400
     notumor   0.940898  1.000000  0.969549       398
   pituitary   0.987531  0.990000  0.988764       400

    accuracy                       0.936796      1598
   macro avg   0.941051  0.936875  0.935316      1598
weighted avg   0.941051  0.936796  0.935273      1598

Confusion matrix:
[[314  61  22   3]
 [  6 389   3   2]
 [  0   0 398   0]
 [  2   2   0 396]]

SVM prediction time: 10.1743s
ResNet50 Testing feature extraction time: 6.33s
End-to-end Testing time: 16.51s

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

cm_resnet50_svm = np.array([
    [314, 61, 22, 3],
    [6, 389, 3, 2],
    [0, 0, 398, 0],
    [2, 2, 0, 396]
])

class_names = [
    "Glioma",
    "Meningioma",
    "No tumour",
    "Pituitary"
]

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_resnet50_svm,
    display_labels=class_names
)

fig, ax = plt.subplots(figsize=(7, 6))

disp.plot(
    ax=ax,
    cmap="Blues",
    values_format="d",
    colorbar=False
)

ax.set_title("ResNet50 + SVM – Held-out Testing Set")
ax.set_xlabel("Predicted class")
ax.set_ylabel("Actual class")

plt.tight_layout()

plt.savefig(
    "resnet50_svm_testing_confusion_matrix.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

In [ ]:
# ======================================================================
# FINAL HELD-OUT TESTING EVALUATION: RESNET50 + RANDOM FOREST
# ======================================================================

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

# Start timing classifier prediction only
rf_testing_prediction_start = time.perf_counter()

# Predict the held-out Testing partition
rf_testing_predictions = final_rf_model.predict(testing_features)

# Stop the timing
rf_testing_prediction_seconds = time.perf_counter() - rf_testing_prediction_start

# End to end testing time: ResNet50 feature extraction + RF prediction
rf_testing_end_to_end_seconds = testing_feature_extraction_seconds + rf_testing_prediction_seconds


# ======================================================================
# CALCULATE FINAL TESTING METRICS
# ======================================================================

rf_testing_accuracy = accuracy_score(testing_class_indices, rf_testing_predictions)

rf_testing_macro_precision = precision_score(testing_class_indices, rf_testing_predictions, average="macro", zero_division=0)

rf_testing_macro_recall = recall_score(testing_class_indices, rf_testing_predictions, average="macro", zero_division=0)

rf_testing_macro_f1 = f1_score(testing_class_indices, rf_testing_predictions, average="macro", zero_division=0)

rf_testing_confusion_matrix = confusion_matrix(testing_class_indices, rf_testing_predictions, labels=list(range(NUMBER_OF_CLASSES)))

rf_testing_classification_report = classification_report(testing_class_indices, rf_testing_predictions, labels = list(range(NUMBER_OF_CLASSES)), target_names=CLASS_NAMES, zero_division=0, digits = 6)


# ======================================================================
# DISPLAY THE FINAL TESTING RESULTS
# ======================================================================

print("--- ResNet50 + Random Forest: Held-out Testing results ---")
print("Accuracy:", f"{rf_testing_accuracy:.6f}")
print("Macro precision:", f"{rf_testing_macro_precision:.6f}")
print("Macro recall:", f"{rf_testing_macro_recall:.6f}")
print("Macro F1:", f"{rf_testing_macro_f1:.6f}")
print("\nClassification report:")
print(rf_testing_classification_report)
print("Confusion matrix:")
print(rf_testing_confusion_matrix)
print("\nRF prediction time:", f"{rf_testing_prediction_seconds:.4f}s")
print("ResNet50 Testing feature extraction time:", f"{testing_feature_extraction_seconds:.2f}s")
print("End-to-end Testing time:", f"{rf_testing_end_to_end_seconds:.2f}s")

--- ResNet50 + Random Forest: Held-out Testing results ---
Accuracy: 0.895494
Macro precision: 0.904624
Macro recall: 0.895625
Macro F1: 0.892233

Classification report:
              precision    recall  f1-score   support

      glioma   0.961268  0.682500  0.798246       400
  meningioma   0.785263  0.932500  0.852571       400
     notumor   0.923434  1.000000  0.960193       398
   pituitary   0.948529  0.967500  0.957921       400

    accuracy                       0.895494      1598
   macro avg   0.904624  0.895625  0.892233      1598
weighted avg   0.904600  0.895494  0.892148      1598

Confusion matrix:
[[273  91  30   6]
 [  9 373   3  15]
 [  0   0 398   0]
 [  2  11   0 387]]

RF prediction time: 0.2463s
ResNet50 Testing feature extraction time: 6.33s
End-to-end Testing time: 6.58s

In [ ]:
# ======================================================================
# SAVE THE FINAL RESNET50 HYBRID TESTING RESULTS
# ======================================================================

RESNET50_TESTING_RESULTS_DIR = HYBRID_RESULTS_DIR / "testing"


RESNET50_TESTING_RESULTS_DIR.mkdir(parents=True, exist_ok=True)


# ======================================================================
# SAVE SUMMARY METRICS
# ======================================================================

resnet50_testing_summary = pd.DataFrame(
    [
        {
            "classifier": "SVM",
            "accuracy": svm_testing_accuracy,
            "macro_precision": svm_testing_macro_precision,
            "macro_recall": svm_testing_macro_recall,
            "macro_f1": svm_testing_macro_f1,
            "prediction_time_seconds": svm_testing_prediction_seconds,
            "feature_extraction_time_seconds": testing_feature_extraction_seconds,
            "end_to_end_time_seconds": svm_testing_end_to_end_seconds,
        },
        {
            "classifier": "Random Forest",
            "accuracy": rf_testing_accuracy,
            "macro_precision": rf_testing_macro_precision,
            "macro_recall": rf_testing_macro_recall,
            "macro_f1": rf_testing_macro_f1,
            "prediction_time_seconds": rf_testing_prediction_seconds,
            "feature_extraction_time_seconds": testing_feature_extraction_seconds,
            "end_to_end_time_seconds": rf_testing_end_to_end_seconds,
        },
    ]
)


TESTING_SUMMARY_PATH = (RESNET50_TESTING_RESULTS_DIR / "resnet50_hybrid_testing_summary.csv")

resnet50_testing_summary.to_csv(TESTING_SUMMARY_PATH, index=False)


# ======================================================================
# SAVE TESTING PREDICTIONS
# ======================================================================

TESTING_PREDICTIONS_PATH = (RESNET50_TESTING_RESULTS_DIR / "resnet50_hybrid_testing_predictions.npz")

np.savez_compressed(
    TESTING_PREDICTIONS_PATH,
    true_class_indices=testing_class_indices,
    svm_predictions=svm_testing_predictions,
    rf_predictions=rf_testing_predictions,
    relative_paths=testing_relative_paths,
)


# ======================================================================
# SAVE CONFUSION MATRICES
# ======================================================================

np.save(RESNET50_TESTING_RESULTS_DIR / "svm_testing_confusion_matrix.npy", svm_testing_confusion_matrix)

np.save(RESNET50_TESTING_RESULTS_DIR / "rf_testing_confusion_matrix.npy", rf_testing_confusion_matrix)


print("Testing summary saved:", TESTING_SUMMARY_PATH)
print("Testing predictions saved:", TESTING_PREDICTIONS_PATH)
print("ResNet50 hybrid Testing results saved successfully.")

Testing summary saved: /content/drive/MyDrive/brain_tumour_colab/results/resnet50_fixed_features/testing/resnet50_hybrid_testing_summary.csv
Testing predictions saved: /content/drive/MyDrive/brain_tumour_colab/results/resnet50_fixed_features/testing/resnet50_hybrid_testing_predictions.npz
ResNet50 hybrid Testing results saved successfully.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

cm_resnet50_rf = np.array([
    [273, 91, 30, 6],
    [9, 373, 3, 15],
    [0, 0, 398, 0],
    [2, 11, 0, 387]
])

class_names = [
    "Glioma",
    "Meningioma",
    "No tumour",
    "Pituitary"
]

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_resnet50_rf,
    display_labels=class_names
)

fig, ax = plt.subplots(figsize=(7, 6))

disp.plot(
    ax=ax,
    cmap="Blues",
    values_format="d",
    colorbar=False
)

ax.set_title("ResNet50 + Random Forest – Held-out Testing Set")
ax.set_xlabel("Predicted class")
ax.set_ylabel("Actual class")

plt.tight_layout()

plt.savefig(
    "resnet50_rf_testing_confusion_matrix.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

In [2]:
# ============================================================
# RESNET50 FEATURES + RANDOM FOREST
# REPEATED-CV TIMING SUMMARY
# ============================================================

from pathlib import Path
import json
import pandas as pd


# ------------------------------------------------------------
# Find the local project automatically
# ------------------------------------------------------------

current_directory = Path.cwd()

possible_roots = [
    current_directory,
    *current_directory.parents,
]

PROJECT_ROOT = next(
    (
        path
        for path in possible_roots
        if (
            path
            / "results"
            / "repeated_nested_cv_local"
            / "resnet50_rf"
        ).exists()
    ),
    None,
)

if PROJECT_ROOT is None:
    raise FileNotFoundError(
        "Could not find "
        "'results/repeated_nested_cv_local/resnet50_rf'."
    )


RESULTS_ROOT = (
    PROJECT_ROOT
    / "results"
    / "repeated_nested_cv_local"
    / "resnet50_rf"
)

print("ResNet50 + RF results:")
print(RESULTS_ROOT)


# ------------------------------------------------------------
# Read all 50 completed outer-fold files
# ------------------------------------------------------------

timing_rows = []

for repeat_number in range(1, 11):

    for fold_number in range(1, 6):

        metrics_path = (
            RESULTS_ROOT
            / f"repeat_{repeat_number:02d}"
            / f"fold_{fold_number:02d}"
            / "outer_metrics.json"
        )

        if not metrics_path.exists():
            raise FileNotFoundError(
                f"Missing file: {metrics_path}"
            )

        with metrics_path.open(
            "r",
            encoding="utf-8",
        ) as file:
            metrics = json.load(file)

        search_seconds = float(
            metrics["cumulative_inner_fit_seconds"]
        )

        refit_seconds = float(
            metrics["final_refit_seconds"]
        )

        timing_rows.append({
            "repeat": repeat_number,
            "fold": fold_number,
            "search_seconds": search_seconds,
            "refit_seconds": refit_seconds,
            "search_plus_refit_seconds":
                search_seconds + refit_seconds,
        })


timings = pd.DataFrame(timing_rows)


# ------------------------------------------------------------
# Sum the five folds within each repeat
# ------------------------------------------------------------

repeat_timings = (
    timings
    .groupby(
        "repeat",
        as_index=False,
    )["search_plus_refit_seconds"]
    .sum()
)

repeat_timings["runtime_minutes"] = (
    repeat_timings["search_plus_refit_seconds"] / 60
)

repeat_timings["runtime_hours"] = (
    repeat_timings["search_plus_refit_seconds"] / 3600
)


# ------------------------------------------------------------
# Save and display
# ------------------------------------------------------------

output_path = (
    RESULTS_ROOT
    / "repeated_cv_timing_summary.csv"
)

repeat_timings.to_csv(
    output_path,
    index=False,
)

display(repeat_timings)

print(
    "\nMean runtime per 5-fold repeat:",
    round(
        repeat_timings["runtime_hours"].mean(),
        3,
    ),
    "hours",
)

print(
    "SD across 10 repeats:",
    round(
        repeat_timings["runtime_hours"].std(ddof=1),
        3,
    ),
    "hours",
)

print(
    "Total recorded time across all 50 folds:",
    round(
        timings["search_plus_refit_seconds"].sum()
        / 3600,
        3,
    ),
    "hours",
)

print("\nSaved to:")
print(output_path)

ResNet50 + RF results:
c:\Users\kwsta\OneDrive\Desktop\Desetation project\brain-tumour-mri-classification\results\repeated_nested_cv_local\resnet50_rf

   repeat  search_plus_refit_seconds  runtime_minutes  runtime_hours
0       1               26758.675526       445.977925       7.432965
1       2               25787.215924       429.786932       7.163116
2       3               24092.394949       401.539916       6.692332
3       4               26380.016133       439.666936       7.327782
4       5               25499.312599       424.988543       7.083142
5       6               23511.014728       391.850245       6.530837
6       7               26355.681440       439.261357       7.321023
7       8               24099.363057       401.656051       6.694268
8       9               31112.835981       518.547266       8.642454
9      10               24436.211426       407.270190       6.787837

Mean runtime per 5-fold repeat: 7.168 hours
SD across 10 repeats: 0.606 hours
Total recorded time across all 50 folds: 71.676 hours

Saved to:
c:\Users\kwsta\OneDrive\Desktop\Desetation project\brain-tumour-mri-classification\results\repeated_nested_cv_local\resnet50_rf\repeated_cv_timing_summary.csv